cp properties/*.properties c1/com/horstmann/violet/
cp properties/framework/*.properties c1/com/horstmann/violet/framework/
cp properties/*.properties c2/com/horstmann/violet/
cp properties/framework/*.properties c2/com/horstmann/violet/framework/
cp properties/*.properties c3/com/horstmann/violet/
cp properties/framework/*.properties c3/com/horstmann/violet/framework/
cp properties/*.properties c4/com/horstmann/violet/
cp properties/framework/*.properties c4/com/horstmann/violet/framework/
cp properties/*.properties c5/com/horstmann/violet/
cp properties/framework/*.properties c5/com/horstmann/violet/framework/
cp properties/*.properties c6/com/horstmann/violet/
cp properties/framework/*.properties c6/com/horstmann/violet/framework/
cp properties/*.properties c7/com/horstmann/violet/
cp properties/framework/*.properties c7/com/horstmann/violet/framework/
cp properties/*.properties c8/com/horstmann/violet/
cp properties/framework/*.properties c8/com/horstmann/violet/framework/
cp properties/*.properties c9/com/horstmann/violet/
cp properties/framework/*.properties c9/com/horstmann/violet/framework/