options {
	STATIC = false;
}

PARSER_BEGIN(StrategoParser)
package tmp.generated_stratego;

/* Wird glaub ich nicht benötigt! 
import java.io.*;
import java.util.*; 
*/

import cide.gast.*;
import cide.gparser.*;
import de.ovgu.cide.fstgen.ast.*;

public class StrategoParser extends AbstractFSTParser 
{
	public StrategoParser(){}
}

PARSER_END(StrategoParser)

/* WHITE SPACE */
SPECIAL_TOKEN : 
	{ " " | 
      "\t" | 
      "\n" | 
      "\r" | 
      "\f" 
    }

/* COMMENTS */
MORE : 
	{ "//" : IN_SINGLE_LINE_COMMENT |
      <"/**" ~["/"]> 
      	{ input_stream.backup(1); } : IN_FORMAL_COMMENT |
      "/*" : IN_MULTI_LINE_COMMENT
	}

<IN_SINGLE_LINE_COMMENT>
	SPECIAL_TOKEN : 
		{ <SINGLE_LINE_COMMENT: "\n" | "\r" | "\r\n" > : DEFAULT }

<IN_FORMAL_COMMENT>
	SPECIAL_TOKEN :
		{ <FORMAL_COMMENT: "*/" > : DEFAULT }

<IN_MULTI_LINE_COMMENT>
	SPECIAL_TOKEN : 
		{ <MULTI_LINE_COMMENT: "*/" > : DEFAULT }

<IN_SINGLE_LINE_COMMENT,IN_FORMAL_COMMENT,IN_MULTI_LINE_COMMENT>
	MORE :
	{ < ~[] > }

/* Reserved words and literals*/
TOKEN:
	{ < ALL: "all" > | 
	  < CONSTRUCTORS: "constructors" > | 
	  < FAIL: "fail" > |
	  < ID: "id" > | 
	  < IN: "in" > | 
	  < LET: "let" > |
	  < MODULE: "module" > |
	  < NOT: "not" > | 
	  < ONE: "one" > | 
	  < OVERLAYS: "overlays" > | 
	  < PRIM: "prim" > |
	  < RULES: "rules" > | 
	  < SCRIPT: "script" > | 
	  < SIGNATURE: "signature" > | 
	  < SOME: "some" > | 
	  < SORTS: "sorts" > | 
	  < STRATEGIES: "strategies" > | 
	  < STRATEGO: "stratego" > | 
	  < TEST: "test" > | 
	  < WHERE: "where" > | 
      < IMPORTTERM: "import-term" > | 
      < IMPORTS: "imports" > | 
      < CASE: "case" > |
	  < ELSE: "else" > | 
	  < END: "end" > | 
	  < EXTERNAL: "external" > | 
	  < IF: "if" > |
	  < OTHERWISE: "otherwise" > | 
	  < REC: "rec" > | 
	  < SWITCH: "switch" > | 
	  < THEN: "then" > | 
	  < EXTEND: "extend" > | 
	  < OVERRIDE: "override" > |
	  < INTERNAL: "internal" > | 
	  < SEALED: "sealed" > | 
	  < EXTENSIBLE: "extensible" > |
	  < OVERRIDABLE: "overrideable" >
	}

/* LITERALS */
TOKEN :
	{ < INTEGER_LITERAL:
		<DECIMAL_LITERAL> (["l","L"])? | 
	  	<HEX_LITERAL> (["l","L"])? | 
	  	<OCTAL_LITERAL> (["l","L"])? > |
	  < #DECIMAL_LITERAL: ["1"-"9"] (["0"-"9"])* > |
	  < #HEX_LITERAL: "0" ["x","X"] (["0"-"9","a"-"f","A"-"F"])+ > |
	  < #OCTAL_LITERAL: "0" (["0"-"7"])* > |
	  < FLOATING_POINT_LITERAL:
    	(["0"-"9"])+ "." (["0"-"9"])* (<EXPONENT>)? (["f","F","d","D"])? | 
    	"." (["0"-"9"])+ (<EXPONENT>)? (["f","F","d","D"])? | 
    	(["0"-"9"])+ <EXPONENT> (["f","F","d","D"])? | 
    	(["0"-"9"])+ (<EXPONENT>)? ["f","F","d","D"] > |
	  < #EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+ > |
	  < CHARACTER_LITERAL:
	  	"'" ( 
	  		(~["'","\\","\n","\r"]) | 
				("\\"
					( ["n","t","b","r","f","u","\\","'","\""] | 
					  ["0"-"7"] ( ["0"-"7"] )? | 
			          ["0"-"3"] ["0"-"7"] ["0"-"7"]
					)
				)
    		)
    	"'" > |
	  < STRING_LITERAL:
    	"\"" (
    		(~["\"","\\","\n","\r"]) | 
				("\\"
					( ["n","t","b","r","f","u","\\","'","\""] | 
					  ["0"-"7"] ( ["0"-"7"] )? | 
					  ["0"-"3"] ["0"-"7"] ["0"-"7"]
            		)
        		)
    		)*
    	"\"" >
	}

/* IDENTIFIERS */
TOKEN :
	{ < IDENTIFIER: <LETTER> (<LETTER>|<DIGIT>)* > |
	  < #LETTER:
	  	[ "\u0024",
	  	  "\u0027",
    	  "\u0041"-"\u005a",
    	  "\u005f",
    	  "\u0061"-"\u007a",
    	  "\u00c0"-"\u00d6",
    	  "\u00d8"-"\u00f6",
    	  "\u00f8"-"\u00ff",
    	  "\u0100"-"\u1fff",
    	  "\u3040"-"\u318f",
    	  "\u3300"-"\u337f",
    	  "\u3400"-"\u3d2d",
    	  "\u4e00"-"\u9fff",
    	  "\uf900"-"\ufaff"
    	] > |
	  < #DIGIT:
    	[ "\u0030"-"\u0039",
		  "\u0660"-"\u0669",
    	  "\u06f0"-"\u06f9",
    	  "\u0966"-"\u096f",
    	  "\u09e6"-"\u09ef",
    	  "\u0a66"-"\u0a6f",
    	  "\u0ae6"-"\u0aef",
    	  "\u0b66"-"\u0b6f",
    	  "\u0be7"-"\u0bef",
    	  "\u0c66"-"\u0c6f",
    	  "\u0ce6"-"\u0cef",
    	  "\u0d66"-"\u0d6f",
    	  "\u0e50"-"\u0e59",
    	  "\u0ed0"-"\u0ed9",
    	  "\u1040"-"\u1049"
    	] >
	}

/* SEPARATORS */
TOKEN :
	{ < LPAREN: "(" > | 
	  < RPAREN: ")" > | 
	  < LBRACE: "{" > | 
	  < RBRACE: "}" > | 
	  < LBRACKET: "[" > | 
	  < RBRACKET: "]" > | 
	  < COMMA: "," > | 
	  < DOT: "." >
	}

/* OPERATORS */
TOKEN :
	{ < PLUS: "+" > | 
	  < MINUS: "-" > | 
	  < STAR : "*" > | 
	  < SLASH: "/" >
	}
FSTInfo Digit(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"0"  {return productionEndTerminal("Digit1","-","-","Replacement","Default",first,token);}
 |
	"1"  {return productionEndTerminal("Digit2","-","-","Replacement","Default",first,token);}
 |
	"2"  {return productionEndTerminal("Digit3","-","-","Replacement","Default",first,token);}
 |
	"3"  {return productionEndTerminal("Digit4","-","-","Replacement","Default",first,token);}
 |
	"4"  {return productionEndTerminal("Digit5","-","-","Replacement","Default",first,token);}
 |
	"5"  {return productionEndTerminal("Digit6","-","-","Replacement","Default",first,token);}
 |
	"6"  {return productionEndTerminal("Digit7","-","-","Replacement","Default",first,token);}
 |
	"7"  {return productionEndTerminal("Digit8","-","-","Replacement","Default",first,token);}
 |
	"8"  {return productionEndTerminal("Digit9","-","-","Replacement","Default",first,token);}
 |
	"9"  {return productionEndTerminal("Digit10","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo NatInteger(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<INTEGER_LITERAL> {return productionEndTerminal("NatInteger","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo RealDigit(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<INTEGER_LITERAL> <DOT> <INTEGER_LITERAL> {return productionEndTerminal("RealDigit","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Int(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"-" n=NatInteger(true){ replaceName(n);} {return productionEndTerminal("Int1","-","-","Replacement","Default",first,token);}
 |
	n=NatInteger(true){ replaceName(n);} {return productionEndTerminal("Int2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Real(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"-" n=RealDigit(true){ replaceName(n);} {return productionEndTerminal("Real1","-","-","Replacement","Default",first,token);}
 |
	n=RealDigit(true){ replaceName(n);} {return productionEndTerminal("Real2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo String(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<STRING_LITERAL> {return productionEndTerminal("String","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo lowerLetter(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"a"  {return productionEndTerminal("lowerLetter1","-","-","Replacement","Default",first,token);}
 |
	"b"  {return productionEndTerminal("lowerLetter2","-","-","Replacement","Default",first,token);}
 |
	"c"  {return productionEndTerminal("lowerLetter3","-","-","Replacement","Default",first,token);}
 |
	"d"  {return productionEndTerminal("lowerLetter4","-","-","Replacement","Default",first,token);}
 |
	"e"  {return productionEndTerminal("lowerLetter5","-","-","Replacement","Default",first,token);}
 |
	"f"  {return productionEndTerminal("lowerLetter6","-","-","Replacement","Default",first,token);}
 |
	"g"  {return productionEndTerminal("lowerLetter7","-","-","Replacement","Default",first,token);}
 |
	"h"  {return productionEndTerminal("lowerLetter8","-","-","Replacement","Default",first,token);}
 |
	"i"  {return productionEndTerminal("lowerLetter9","-","-","Replacement","Default",first,token);}
 |
	"j"  {return productionEndTerminal("lowerLetter10","-","-","Replacement","Default",first,token);}
 |
	"k"  {return productionEndTerminal("lowerLetter11","-","-","Replacement","Default",first,token);}
 |
	"l"  {return productionEndTerminal("lowerLetter12","-","-","Replacement","Default",first,token);}
 |
	"m"  {return productionEndTerminal("lowerLetter13","-","-","Replacement","Default",first,token);}
 |
	"n"  {return productionEndTerminal("lowerLetter14","-","-","Replacement","Default",first,token);}
 |
	"o"  {return productionEndTerminal("lowerLetter15","-","-","Replacement","Default",first,token);}
 |
	"p"  {return productionEndTerminal("lowerLetter16","-","-","Replacement","Default",first,token);}
 |
	"q"  {return productionEndTerminal("lowerLetter17","-","-","Replacement","Default",first,token);}
 |
	"r"  {return productionEndTerminal("lowerLetter18","-","-","Replacement","Default",first,token);}
 |
	"s"  {return productionEndTerminal("lowerLetter19","-","-","Replacement","Default",first,token);}
 |
	"t"  {return productionEndTerminal("lowerLetter20","-","-","Replacement","Default",first,token);}
 |
	"u"  {return productionEndTerminal("lowerLetter21","-","-","Replacement","Default",first,token);}
 |
	"v"  {return productionEndTerminal("lowerLetter22","-","-","Replacement","Default",first,token);}
 |
	"w"  {return productionEndTerminal("lowerLetter23","-","-","Replacement","Default",first,token);}
 |
	"x"  {return productionEndTerminal("lowerLetter24","-","-","Replacement","Default",first,token);}
 |
	"y"  {return productionEndTerminal("lowerLetter25","-","-","Replacement","Default",first,token);}
 |
	"z"  {return productionEndTerminal("lowerLetter26","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo upperLetter(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"A"  {return productionEndTerminal("upperLetter1","-","-","Replacement","Default",first,token);}
 |
	"B"  {return productionEndTerminal("upperLetter2","-","-","Replacement","Default",first,token);}
 |
	"C"  {return productionEndTerminal("upperLetter3","-","-","Replacement","Default",first,token);}
 |
	"D"  {return productionEndTerminal("upperLetter4","-","-","Replacement","Default",first,token);}
 |
	"E"  {return productionEndTerminal("upperLetter5","-","-","Replacement","Default",first,token);}
 |
	"F"  {return productionEndTerminal("upperLetter6","-","-","Replacement","Default",first,token);}
 |
	"G"  {return productionEndTerminal("upperLetter7","-","-","Replacement","Default",first,token);}
 |
	"H"  {return productionEndTerminal("upperLetter8","-","-","Replacement","Default",first,token);}
 |
	"I"  {return productionEndTerminal("upperLetter9","-","-","Replacement","Default",first,token);}
 |
	"J"  {return productionEndTerminal("upperLetter10","-","-","Replacement","Default",first,token);}
 |
	"K"  {return productionEndTerminal("upperLetter11","-","-","Replacement","Default",first,token);}
 |
	"L"  {return productionEndTerminal("upperLetter12","-","-","Replacement","Default",first,token);}
 |
	"M"  {return productionEndTerminal("upperLetter13","-","-","Replacement","Default",first,token);}
 |
	"N"  {return productionEndTerminal("upperLetter14","-","-","Replacement","Default",first,token);}
 |
	"O"  {return productionEndTerminal("upperLetter15","-","-","Replacement","Default",first,token);}
 |
	"P"  {return productionEndTerminal("upperLetter16","-","-","Replacement","Default",first,token);}
 |
	"Q"  {return productionEndTerminal("upperLetter17","-","-","Replacement","Default",first,token);}
 |
	"R"  {return productionEndTerminal("upperLetter18","-","-","Replacement","Default",first,token);}
 |
	"S"  {return productionEndTerminal("upperLetter19","-","-","Replacement","Default",first,token);}
 |
	"T"  {return productionEndTerminal("upperLetter20","-","-","Replacement","Default",first,token);}
 |
	"U"  {return productionEndTerminal("upperLetter21","-","-","Replacement","Default",first,token);}
 |
	"V"  {return productionEndTerminal("upperLetter22","-","-","Replacement","Default",first,token);}
 |
	"W"  {return productionEndTerminal("upperLetter23","-","-","Replacement","Default",first,token);}
 |
	"X"  {return productionEndTerminal("upperLetter24","-","-","Replacement","Default",first,token);}
 |
	"Y"  {return productionEndTerminal("upperLetter25","-","-","Replacement","Default",first,token);}
 |
	"Z"  {return productionEndTerminal("upperLetter26","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CharClass1(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=lowerLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass11","-","-","Replacement","Default",first,token);}
 |
	n=upperLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass12","-","-","Replacement","Default",first,token);}
 |
	"."  {return productionEndTerminal("CharClass13","-","-","Replacement","Default",first,token);}
 |
	"_"  {return productionEndTerminal("CharClass14","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CharClass2(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=lowerLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass21","-","-","Replacement","Default",first,token);}
 |
	n=upperLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass22","-","-","Replacement","Default",first,token);}
 |
	n=Digit(true){ replaceName(n);} {return productionEndTerminal("CharClass23","-","-","Replacement","Default",first,token);}
 |
	"'"  {return productionEndTerminal("CharClass24","-","-","Replacement","Default",first,token);}
 |
	"."  {return productionEndTerminal("CharClass25","-","-","Replacement","Default",first,token);}
 |
	"-"  {return productionEndTerminal("CharClass26","-","-","Replacement","Default",first,token);}
 |
	"_"  {return productionEndTerminal("CharClass27","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CharClass3(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=lowerLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass31","-","-","Replacement","Default",first,token);}
 |
	n=upperLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass32","-","-","Replacement","Default",first,token);}
 |
	"_"  {return productionEndTerminal("CharClass33","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CharClass4(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=lowerLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass41","-","-","Replacement","Default",first,token);}
 |
	n=upperLetter(true){ replaceName(n);} {return productionEndTerminal("CharClass42","-","-","Replacement","Default",first,token);}
 |
	n=Digit(true){ replaceName(n);} {return productionEndTerminal("CharClass43","-","-","Replacement","Default",first,token);}
 |
	"'"  {return productionEndTerminal("CharClass44","-","-","Replacement","Default",first,token);}
 |
	"-"  {return productionEndTerminal("CharClass45","-","-","Replacement","Default",first,token);}
 |
	"_"  {return productionEndTerminal("CharClass46","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ModNamePart(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=CharClass1(true){ replaceName(n);} (n=CharClass2(true){ replaceName(n);})* {return productionEndTerminal("ModNamePart","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ModName(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=ModNamePart(true){ replaceName(n);} "/")+ {return productionEndTerminal("ModName","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Id(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=CharClass3(true){ replaceName(n);} (n=CharClass4(true){ replaceName(n);})* {return productionEndTerminal("Id1","-","-","Replacement","Default",first,token);}
 |
	"'" (n=lowerLetter(true){ replaceName(n);})+ {return productionEndTerminal("Id2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo LId(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=CharClass3(true){ replaceName(n);} (n=CharClass4(true){ replaceName(n);})* "*" {return productionEndTerminal("LId","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo LCID(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=lowerLetter(true){ replaceName(n);} (n=CharClass4(true){ replaceName(n);})* {return productionEndTerminal("LCID","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo UCID(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=upperLetter(true){ replaceName(n);} (n=CharClass4(true){ replaceName(n);})* {return productionEndTerminal("UCID","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Var(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} {return productionEndTerminal("Var1","-","-","Replacement","Default",first,token);}
 |
	n=LId(true){ replaceName(n);} {return productionEndTerminal("Var2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ID(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} {return productionEndTerminal("ID1","-","-","Replacement","Default",first,token);}
 |
	n=LId(true){ replaceName(n);} {return productionEndTerminal("ID2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Wld(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"_"  {return productionEndTerminal("Wld","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Term(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Var(true){ replaceName(n);} {return productionEndTerminal("Term1","-","-","Replacement","Default",first,token);}
 |
	n=Wld(true){ replaceName(n);} {return productionEndTerminal("Term2","-","-","Replacement","Default",first,token);}
 |
	n=PreTerm(true){ replaceName(n);} "{^" n=PreTerm(true){ replaceName(n);} "}" {return productionEndTerminal("Term3","-","-","Replacement","Default",first,token);}
 |
	n=Var(true){ replaceName(n);} "@" n=Term(true){ replaceName(n);} {return productionEndTerminal("Term4","-","-","Replacement","Default",first,token);}
 |
	"_" n=Term(true){ replaceName(n);} {return productionEndTerminal("Term5","-","-","Replacement","Default",first,token);}
 |
	n=PreTerm(true){ replaceName(n);} "{" (n=Term(true){ replaceName(n);} ",")* "}" {return productionEndTerminal("Term6","-","-","Replacement","Default",first,token);}
 |
	n=PreTerm(true){ replaceName(n);} {return productionEndTerminal("Term7","-","-","Replacement","Default",first,token);}
 |
	n=StrategyAngle(true){ replaceName(n);} n=Term(true){ replaceName(n);} {return productionEndTerminal("Term8","-","-","Replacement","Default",first,token);}
 |
	n=StrategyAngle(true){ replaceName(n);} {return productionEndTerminal("Term9","-","-","Replacement","Default",first,token);}
 |
	n=Var(true){ replaceName(n);} "@" n=Term(true){ replaceName(n);} {return productionEndTerminal("Term10","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo PreTerm(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Var(true){ replaceName(n);} {return productionEndTerminal("PreTerm1","-","-","Replacement","Default",first,token);}
 |
	n=Wld(true){ replaceName(n);} {return productionEndTerminal("PreTerm2","-","-","Replacement","Default",first,token);}
 |
	n=Int(true){ replaceName(n);} {return productionEndTerminal("PreTerm3","-","-","Replacement","Default",first,token);}
 |
	n=Real(true){ replaceName(n);} {return productionEndTerminal("PreTerm4","-","-","Replacement","Default",first,token);}
 |
	n=String(true){ replaceName(n);} {return productionEndTerminal("PreTerm5","-","-","Replacement","Default",first,token);}
 |
	n=Var(true){ replaceName(n);} "@" n=PreTerm(true){ replaceName(n);} {return productionEndTerminal("PreTerm6","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("PreTerm7","-","-","Replacement","Default",first,token);}
 |
	n=String(true){ replaceName(n);} "(" (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("PreTerm8","-","-","Replacement","Default",first,token);}
 |
	"_" n=PreTerm(true){ replaceName(n);} {return productionEndTerminal("PreTerm9","-","-","Replacement","Default",first,token);}
 |
	n=StrategyAngle(true){ replaceName(n);} n=Term(true){ replaceName(n);} {return productionEndTerminal("PreTerm10","-","-","Replacement","Default",first,token);}
 |
	n=StrategyAngle(true){ replaceName(n);} {return productionEndTerminal("PreTerm11","-","-","Replacement","Default",first,token);}
 |
	"(" (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("PreTerm12","-","-","Replacement","Default",first,token);}
 |
	"[" (n=Term(true){ replaceName(n);} ",")* "]" {return productionEndTerminal("PreTerm13","-","-","Replacement","Default",first,token);}
 |
	"[" (n=Term(true){ replaceName(n);} ",")* "|" n=Term(true){ replaceName(n);} "]" {return productionEndTerminal("PreTerm14","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Sort(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=LCID(true){ replaceName(n);} {return productionEndTerminal("Sort1","-","-","Replacement","Default",first,token);}
 |
	n=UCID(true){ replaceName(n);} {return productionEndTerminal("Sort2","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Sort(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Sort3","-","-","Replacement","Default",first,token);}
 |
	"[" (n=Sort(true){ replaceName(n);} ",")* "]" {return productionEndTerminal("Sort4","-","-","Replacement","Default",first,token);}
 |
	"[" (n=Sort(true){ replaceName(n);} ",")* "|" n=Sort(true){ replaceName(n);} "]" {return productionEndTerminal("Sort5","-","-","Replacement","Default",first,token);}
 |
	"(" (n=Sort(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Sort6","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Opdecl(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} ":" n=Type(true){ replaceName(n);} {return productionEndTerminal("Opdecl1","-","-","Replacement","Default",first,token);}
 |
	n=String(true){ replaceName(n);} ":" n=Type(true){ replaceName(n);} {return productionEndTerminal("Opdecl2","-","-","Replacement","Default",first,token);}
 |
	":" n=Type(true){ replaceName(n);} {return productionEndTerminal("Opdecl3","-","-","Replacement","Default",first,token);}
 |
	"external" n=Id(true){ replaceName(n);} ":" n=Type(true){ replaceName(n);} {return productionEndTerminal("Opdecl4","-","-","Replacement","Default",first,token);}
 |
	"external" n=String(true){ replaceName(n);} ":" n=Type(true){ replaceName(n);} {return productionEndTerminal("Opdecl5","-","-","Replacement","Default",first,token);}
 |
	"external" ":" n=Type(true){ replaceName(n);} {return productionEndTerminal("Opdecl6","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Sdecl(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"sorts" (n=Sort(true){ replaceName(n);})* {return productionEndTerminal("Sdecl1","-","-","Replacement","Default",first,token);}
 |
	"constructors" (n=Opdecl(true){ replaceName(n);})* {return productionEndTerminal("Sdecl2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Type(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=FunType(true){ replaceName(n);} {return productionEndTerminal("Type1","-","-","Replacement","Default",first,token);}
 |
	n=ConstType(true){ replaceName(n);} {return productionEndTerminal("Type2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ConstType(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Sort(true){ replaceName(n);} {return productionEndTerminal("ConstType","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ArgType(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"(" n=Type(true){ replaceName(n);} ")" {return productionEndTerminal("ArgType1","-","-","Replacement","Default",first,token);}
 |
	n=ConstType(true){ replaceName(n);} {return productionEndTerminal("ArgType2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo RetType(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Type(true){ replaceName(n);} {return productionEndTerminal("RetType","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo FunType(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=ArgType(true){ replaceName(n);} "*")+ "->" n=RetType(true){ replaceName(n);} {return productionEndTerminal("FunType","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Module(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"module" n=ModName(true){ replaceName(n);} (n=Decl(true){ replaceName(n);})* {return productionEndTerminal("Module1","-","-","Replacement","Default",first,token);}
 |
	"specification" (n=Decl(true){ replaceName(n);})* {return productionEndTerminal("Module2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ImportModName(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=ModName(true){ replaceName(n);} {return productionEndTerminal("ImportModName","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Decl(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"imports" (n=ImportModName(true){ replaceName(n);})* {return productionEndTerminal("Decl1","-","-","Replacement","Default",first,token);}
 |
	"strategies" (n=Def(true){ replaceName(n);})* {return productionEndTerminal("Decl2","-","-","Replacement","Default",first,token);}
 |
	"signatures" (n=Sdecl(true){ replaceName(n);})* {return productionEndTerminal("Decl3","-","-","Replacement","Default",first,token);}
 |
	"rules" (n=Def(true){ replaceName(n);})* {return productionEndTerminal("Decl4","-","-","Replacement","Default",first,token);}
 |
	"overlays" (n=Overlay(true){ replaceName(n);})* {return productionEndTerminal("Decl5","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Def(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=StrategyDef(true){ replaceName(n);} {return productionEndTerminal("Def1","-","-","Replacement","Default",first,token);}
 |
	(n=Anno(true){ replaceName(n);})+ n=StrategyDef(true){ replaceName(n);} {return productionEndTerminal("Def2","-","-","Replacement","Default",first,token);}
 |
	n=RuleDef(true){ replaceName(n);} {return productionEndTerminal("Def3","-","-","Replacement","Default",first,token);}
 |
	(n=Anno(true){ replaceName(n);})+ n=RuleDef(true){ replaceName(n);} {return productionEndTerminal("Def4","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo SVar(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} {return productionEndTerminal("SVar","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Strategy(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"let" (n=Def(true){ replaceName(n);})* "in" n=Strategy(true){ replaceName(n);} "end" {return productionEndTerminal("Strategy1","-","-","Replacement","Default",first,token);}
 |
	n=SVar(true){ replaceName(n);} "(" (n=Strategy(true){ replaceName(n);} ",")* "|" (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strategy2","-","-","Replacement","Default",first,token);}
 |
	"call" "(" n=Term(true){ replaceName(n);} "|" (n=Strategy(true){ replaceName(n);} ",")* "|" (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strategy3","-","-","Replacement","Default",first,token);}
 |
	"fail"  {return productionEndTerminal("Strategy4","-","-","Replacement","Default",first,token);}
 |
	"id"  {return productionEndTerminal("Strategy5","-","-","Replacement","Default",first,token);}
 |
	"proceed" "(" (n=Strategy(true){ replaceName(n);} ",")* "|" (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strategy6","-","-","Replacement","Default",first,token);}
 |
	"proceed"  {return productionEndTerminal("Strategy7","-","-","Replacement","Default",first,token);}
 |
	"?" n=Term(true){ replaceName(n);} {return productionEndTerminal("Strategy8","-","-","Replacement","Default",first,token);}
 |
	"!" n=Term(true){ replaceName(n);} {return productionEndTerminal("Strategy9","-","-","Replacement","Default",first,token);}
 |
	"{" (n=ID(true){ replaceName(n);} ",")* ":" n=Strategy(true){ replaceName(n);} "}" {return productionEndTerminal("Strategy10","-","-","Replacement","Default",first,token);}
 |
	"prim" "(" n=String(true){ replaceName(n);} "," (n=Strategy(true){ replaceName(n);} ",")* "|" (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strategy11","-","-","Replacement","Default",first,token);}
 |
	"some" "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy12","-","-","Replacement","Default",first,token);}
 |
	"one" "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy13","-","-","Replacement","Default",first,token);}
 |
	"all" "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy14","-","-","Replacement","Default",first,token);}
 |
	"import-term" "(" n=ModName(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy15","-","-","Replacement","Default",first,token);}
 |
	n=SVar(true){ replaceName(n);} "(" (n=Strategy(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strategy16","-","-","Replacement","Default",first,token);}
 |
	"{" n=Strategy(true){ replaceName(n);} "}" {return productionEndTerminal("Strategy17","-","-","Replacement","Default",first,token);}
 |
	n=StrategyAngle(true){ replaceName(n);} n=Term(true){ replaceName(n);} {return productionEndTerminal("Strategy18","-","-","Replacement","Default",first,token);}
 |
	"rec" n=Id(true){ replaceName(n);} "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy19","-","-","Replacement","Default",first,token);}
 |
	"not" "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy20","-","-","Replacement","Default",first,token);}
 |
	"where" "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy21","-","-","Replacement","Default",first,token);}
 |
	"with" "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy22","-","-","Replacement","Default",first,token);}
 |
	"test" "(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy23","-","-","Replacement","Default",first,token);}
 |
	"prim" "(" n=String(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy24","-","-","Replacement","Default",first,token);}
 |
	"prim" "(" n=String(true){ replaceName(n);} "," (n=Term(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strategy25","-","-","Replacement","Default",first,token);}
 |
	n=String(true){ replaceName(n);} {return productionEndTerminal("Strategy26","-","-","Replacement","Default",first,token);}
 |
	n=Int(true){ replaceName(n);} {return productionEndTerminal("Strategy27","-","-","Replacement","Default",first,token);}
 |
	n=Real(true){ replaceName(n);} {return productionEndTerminal("Strategy28","-","-","Replacement","Default",first,token);}
 |
	n=String(true){ replaceName(n);} "(" (n=Strategy(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strategy29","-","-","Replacement","Default",first,token);}
 |
	"(" n=Strategy(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy30","-","-","Replacement","Default",first,token);}
 |
	"(" n=Strategy(true){ replaceName(n);} "," (n=Strategy(true){ replaceName(n);} ",")+ ")" {return productionEndTerminal("Strategy31","-","-","Replacement","Default",first,token);}
 |
	"[" (n=Strategy(true){ replaceName(n);} ",")* "]" {return productionEndTerminal("Strategy32","-","-","Replacement","Default",first,token);}
 |
	"[" (n=Strategy(true){ replaceName(n);} ",")* "|" n=Strategy(true){ replaceName(n);} "]" {return productionEndTerminal("Strategy33","-","-","Replacement","Default",first,token);}
 |
	n=SVar(true){ replaceName(n);} {return productionEndTerminal("Strategy34","-","-","Replacement","Default",first,token);}
 |
	"\\" n=Rule(true){ replaceName(n);} "\\" {return productionEndTerminal("Strategy35","-","-","Replacement","Default",first,token);}
 |
	"(" n=Rule(true){ replaceName(n);} ")" {return productionEndTerminal("Strategy36","-","-","Replacement","Default",first,token);}
 |
	"proceed" "(" (n=Strategy(true){ replaceName(n);} ",")+ ")" {return productionEndTerminal("Strategy37","-","-","Replacement","Default",first,token);}
 |
	"if" n=Strategy(true){ replaceName(n);} "then" n=Strategy(true){ replaceName(n);} "else" n=Strategy(true){ replaceName(n);} "end" {return productionEndTerminal("Strategy38","-","-","Replacement","Default",first,token);}
 |
	"if" n=Strategy(true){ replaceName(n);} "then" n=Strategy(true){ replaceName(n);} "end" {return productionEndTerminal("Strategy39","-","-","Replacement","Default",first,token);}
 |
	"switch" n=Strategy(true){ replaceName(n);} (n=SwitchCase(true){ replaceName(n);})* "end" {return productionEndTerminal("Strategy40","-","-","Replacement","Default",first,token);}
 |
	"switch" n=Strategy(true){ replaceName(n);} (n=SwitchCase(true){ replaceName(n);})* "otherwise" ":" n=Strategy(true){ replaceName(n);} "end" {return productionEndTerminal("Strategy41","-","-","Replacement","Default",first,token);}
 |
	n=Term(true){ replaceName(n);} ":=" n=Term(true){ replaceName(n);} {return productionEndTerminal("Strategy42","-","-","Replacement","Default",first,token);}
 |
	"{|" n=ScopeLabels(true){ replaceName(n);} ":" n=Strategy(true){ replaceName(n);} "|}" {return productionEndTerminal("Strategy43","-","-","Replacement","Default",first,token);}
 |
	"rules" "(" (n=DynRuleDef(true){ replaceName(n);})* ")" "/" n=RuleNames(true){ replaceName(n);} "\\*" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("Strategy44","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo StrategyMid(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Strategy(true){ replaceName(n);} {return productionEndTerminal("StrategyMid","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo StrategyDef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* "|" (n=Typedid(true){ replaceName(n);} ",")* ")" "=" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("StrategyDef1","-","-","Replacement","Default",first,token);}
 |
	"external" n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* "|" (n=Typedid(true){ replaceName(n);} ",")* ")" "=" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("StrategyDef2","-","-","Replacement","Default",first,token);}
 |
	"external" n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* "|" (n=Typedid(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("StrategyDef3","-","-","Replacement","Default",first,token);}
 |
	"external" n=EmptyId(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* "|" (n=Typedid(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("StrategyDef4","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "=" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("StrategyDef5","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* ")" "=" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("StrategyDef6","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo EmptyId(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	 {return productionEndTerminal("EmptyId","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Typedid(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=ID(true){ replaceName(n);} ":" n=Type(true){ replaceName(n);} {return productionEndTerminal("Typedid1","-","-","Replacement","Default",first,token);}
 |
	n=ID(true){ replaceName(n);} {return productionEndTerminal("Typedid2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Anno(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extend"  {return productionEndTerminal("Anno1","-","-","Replacement","Default",first,token);}
 |
	"override"  {return productionEndTerminal("Anno2","-","-","Replacement","Default",first,token);}
 |
	"internal"  {return productionEndTerminal("Anno3","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Strat(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} "(" (n=Strat(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("Strat","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Overlay(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} "=" n=Term(true){ replaceName(n);} {return productionEndTerminal("Overlay1","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Id(true){ replaceName(n);} ",")* ")" "=" n=Term(true){ replaceName(n);} {return productionEndTerminal("Overlay2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo RuleDef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} ":" n=Rule(true){ replaceName(n);} {return productionEndTerminal("RuleDef1","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* ")" ":" n=Rule(true){ replaceName(n);} {return productionEndTerminal("RuleDef2","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* "|" (n=Typedid(true){ replaceName(n);} ",")* ")" ":" n=Rule(true){ replaceName(n);} {return productionEndTerminal("RuleDef3","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Rule(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Term(true){ replaceName(n);} "->" n=Term(true){ replaceName(n);} {return productionEndTerminal("Rule1","-","-","Replacement","Default",first,token);}
 |
	n=Term(true){ replaceName(n);} "->" n=Term(true){ replaceName(n);} "where" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("Rule2","-","-","Replacement","Default",first,token);}
 |
	n=Term(true){ replaceName(n);} "->" n=Term(true){ replaceName(n);} (n=RuleCond(true){ replaceName(n);})+ {return productionEndTerminal("Rule3","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo RuleCond(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"where" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("RuleCond1","-","-","Replacement","Default",first,token);}
 |
	"with" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("RuleCond2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Kind(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*"  {return productionEndTerminal("Kind1","-","-","Replacement","Default",first,token);}
 |
	"**"  {return productionEndTerminal("Kind2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo StrategyAngle(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<" n=Strategy(true){ replaceName(n);} ">" {return productionEndTerminal("StrategyAngle","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo StrategyCurly(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" n=Strategy(true){ replaceName(n);} "}" {return productionEndTerminal("StrategyCurly","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo SwitchCase(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"case" n=Strategy(true){ replaceName(n);} ":" n=Strategy(true){ replaceName(n);} {return productionEndTerminal("SwitchCase","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ScopeLabels(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=DynRuleScopeId(true){ replaceName(n);} ",")* {return productionEndTerminal("ScopeLabels1","-","-","Replacement","Default",first,token);}
 |
	"~" n=Term(true){ replaceName(n);} {return productionEndTerminal("ScopeLabels2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo DynRuleScopeId(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} "." n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleScopeId1","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} {return productionEndTerminal("DynRuleScopeId2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo RuleNames(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=Id(true){ replaceName(n);} ",")* {return productionEndTerminal("RuleNames1","-","-","Replacement","Default",first,token);}
 |
	"~" n=Term(true){ replaceName(n);} {return productionEndTerminal("RuleNames2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo RuleDec(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} {return productionEndTerminal("RuleDec1","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("RuleDec2","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} "(" (n=Typedid(true){ replaceName(n);} ",")* "|" (n=Typedid(true){ replaceName(n);} ",")* ")" {return productionEndTerminal("RuleDec3","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo DynRuleId(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=RuleDec(true){ replaceName(n);} "." n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleId1","-","-","Replacement","Default",first,token);}
 |
	n=RuleDec(true){ replaceName(n);} "+" n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleId2","-","-","Replacement","Default",first,token);}
 |
	n=RuleDec(true){ replaceName(n);} {return productionEndTerminal("DynRuleId3","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo DynRuleDef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} "+" n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef1","-","-","Replacement","Default",first,token);}
 |
	n=DynRuleId(true){ replaceName(n);} ":-" n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef2","-","-","Replacement","Default",first,token);}
 |
	n=DynRuleId(true){ replaceName(n);} ":" n=Rule(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef3","-","-","Replacement","Default",first,token);}
 |
	n=DynRuleId(true){ replaceName(n);} ":+" n=Rule(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef4","-","-","Replacement","Default",first,token);}
 |
	n=DynRuleId(true){ replaceName(n);} ":" n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef5","-","-","Replacement","Default",first,token);}
 |
	n=DynRuleId(true){ replaceName(n);} ":=" n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef6","-","-","Replacement","Default",first,token);}
 |
	n=DynRuleId(true){ replaceName(n);} ":+=" n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef7","-","-","Replacement","Default",first,token);}
 |
	n=DynRuleId(true){ replaceName(n);} ":" n=Rule(true){ replaceName(n);} "depends " "on" n=Term(true){ replaceName(n);} {return productionEndTerminal("DynRuleDef8","-","-","Replacement","Default",first,token);}

 )  }

