/* Generated By:JavaCC: Do not edit this line. StrategoParserConstants.java */
package tmp.generated_stratego;

public interface StrategoParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 10;
  int SINGLE_LINE_COMMENT_SDF = 11;
  int FORMAL_COMMENT = 12;
  int MULTI_LINE_COMMENT = 13;
  int MODULE = 15;
  int SPECIFICATION = 16;
  int IMPORTS = 17;
  int EXPORTS = 18;
  int HIDDENS = 19;
  int SORTS = 20;
  int STARTSYMBOL = 21;
  int SYNTAX = 22;
  int VARIABLES = 23;
  int LEXICALSYNTAX = 24;
  int CFREESYNTAX = 25;
  int LEXICALVARS = 26;
  int CONS = 27;
  int LEFT = 28;
  int ASSOC = 29;
  int AVOID = 30;
  int RIGHT = 31;
  int PREFER = 32;
  int BRACKET = 33;
  int REJECT = 34;
  int NONASSOC = 35;
  int RECOVER = 36;
  int DEPRECATED = 37;
  int INDENTPADDING = 38;
  int PRIORITIES = 39;
  int CFREEPRIORITIES = 40;
  int LEXICALRESTRICTIONS = 41;
  int CFREERESTRICTIONS = 42;
  int ALL = 43;
  int CONSTRUCTORS = 44;
  int FAIL = 45;
  int ID = 46;
  int IN = 47;
  int LET = 48;
  int NOT = 49;
  int ONE = 50;
  int ON = 51;
  int CALL = 52;
  int PROCEED = 53;
  int SIGNATURES = 54;
  int WITH = 55;
  int OVERLAYS = 56;
  int PRIM = 57;
  int RULES = 58;
  int SCRIPT = 59;
  int SIGNATURE = 60;
  int SOME = 61;
  int STRATEGIES = 62;
  int STRATEGO = 63;
  int TEST = 64;
  int WHERE = 65;
  int IMPORTTERM = 66;
  int CASE = 67;
  int ELSE = 68;
  int END = 69;
  int EXTERNAL = 70;
  int IF = 71;
  int OTHERWISE = 72;
  int REC = 73;
  int SWITCH = 74;
  int THEN = 75;
  int EXTEND = 76;
  int OVERRIDE = 77;
  int INTERNAL = 78;
  int SEALED = 79;
  int EXTENSIBLE = 80;
  int OVERRIDABLE = 81;
  int INTEGER_LITERAL = 82;
  int DECIMAL_LITERAL = 83;
  int HEX_LITERAL = 84;
  int OCTAL_LITERAL = 85;
  int FLOATING_POINT_LITERAL = 86;
  int EXPONENT = 87;
  int CHARACTER_LITERAL = 88;
  int STRING_LITERAL = 89;
  int IDENTIFIER = 90;
  int LETTER = 91;
  int LCCHAR = 92;
  int UCCHAR = 93;
  int DIGIT = 94;
  int LPAREN = 95;
  int RPAREN = 96;
  int LBRACE = 97;
  int RBRACE = 98;
  int LBRACKET = 99;
  int RBRACKET = 100;
  int DLBRACKET = 101;
  int DRBRACKET = 102;
  int LT = 103;
  int GT = 104;
  int PLUS = 105;
  int MINUS = 106;
  int STAR = 107;
  int SLASH = 108;
  int COMMA = 109;
  int SEMICOLON = 110;
  int DDOT = 111;
  int DOT = 112;
  int QUESTIONMARK = 113;
  int EXCLAMATIONMARK = 114;
  int NUMBERSIGN = 115;
  int AT = 116;
  int DOLLAR = 117;
  int VERTICALLINE = 118;
  int TILDE = 119;
  int AMPERSAND = 120;
  int PERCENTAGE = 121;
  int CIRCUMFLEXACCENT = 122;
  int GRAVEACCENT = 123;
  int APOSTROPHE = 124;
  int ARROW = 125;
  int ASSIGN = 126;
  int NOTALLOWED = 127;
  int LOWLINE = 128;
  int QUOTATIONMARK = 129;
  int BACKSLASH = 130;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_SINGLE_LINE_COMMENT_SDF = 2;
  int IN_FORMAL_COMMENT = 3;
  int IN_MULTI_LINE_COMMENT = 4;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"%%\"",
    "<token of kind 8>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<SINGLE_LINE_COMMENT_SDF>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 14>",
    "\"module\"",
    "\"specification\"",
    "\"imports\"",
    "\"exports\"",
    "\"hiddens\"",
    "\"sorts\"",
    "\"context-free start-symbols\"",
    "\"syntax\"",
    "\"variables\"",
    "\"lexical syntax\"",
    "\"context-free syntax\"",
    "\"lexical variables\"",
    "\"cons\"",
    "\"left\"",
    "\"assoc\"",
    "\"avoid\"",
    "\"right\"",
    "\"prefer\"",
    "\"bracket\"",
    "\"reject\"",
    "\"non-assoc\"",
    "\"recover\"",
    "\"deprecated\"",
    "\"indentpadding\"",
    "\"priorities\"",
    "\"context-free priorities\"",
    "\"lexical restrictions\"",
    "\"context-free restrictions\"",
    "\"all\"",
    "\"constructors\"",
    "\"fail\"",
    "\"id\"",
    "\"in\"",
    "\"let\"",
    "\"not\"",
    "\"one\"",
    "\"on\"",
    "\"call\"",
    "\"proceed\"",
    "\"signatures\"",
    "\"with\"",
    "\"overlays\"",
    "\"prim\"",
    "\"rules\"",
    "\"script\"",
    "\"signature\"",
    "\"some\"",
    "\"strategies\"",
    "\"stratego\"",
    "\"test\"",
    "\"where\"",
    "\"import-term\"",
    "\"case\"",
    "\"else\"",
    "\"end\"",
    "\"external\"",
    "\"if\"",
    "\"otherwise\"",
    "\"rec\"",
    "\"switch\"",
    "\"then\"",
    "\"extend\"",
    "\"override\"",
    "\"internal\"",
    "\"sealed\"",
    "\"extensible\"",
    "\"overrideable\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<LCCHAR>",
    "<UCCHAR>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"[[\"",
    "\"]]\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"?\"",
    "\"!\"",
    "\"#\"",
    "\"@\"",
    "\"$\"",
    "\"|\"",
    "\"~\"",
    "\"&\"",
    "\"%\"",
    "\"^\"",
    "\"`\"",
    "\"\\\'\"",
    "\"->\"",
    "\"=\"",
    "\"-/-\"",
    "\"_\"",
    "\"\\\"\"",
    "\"\\\\\"",
  };

}
