options {
	STATIC = false;
	FORCE_LA_CHECK = false;
	DEBUG_PARSER = false;
}

PARSER_BEGIN(SDFParser)
package tmp.generated_sdf;
import cide.gast.*;
import cide.gparser.*;
import de.ovgu.cide.fstgen.ast.*;

public class SDFParser extends AbstractFSTParser 
{
	public SDFParser(){}
}

PARSER_END(SDFParser)

/*****************************************************************************
 * WHITE SPACE                                                               *
 *****************************************************************************/
SPECIAL_TOKEN : 
	{ " " | 
      "\t" | 
      "\n" | 
      "\r" | 
      "\f" 
    }
/*****************************************************************************
 * COMMENTS                                                                  *
 *****************************************************************************/
MORE :
	{ "%%" : IN_SINGLE_LINE_COMMENT |
	  <"/**" ~["/"]> { input_stream.backup(1); } : IN_FORMAL_COMMENT |
	  "/*" : IN_MULTI_LINE_COMMENT 
	}
	<IN_SINGLE_LINE_COMMENT>
		SPECIAL_TOKEN :
			{ <SINGLE_LINE_COMMENT: "\n" | "\r" | "\r\n" > : DEFAULT }
	<IN_FORMAL_COMMENT>
		SPECIAL_TOKEN :
			{ <FORMAL_COMMENT: "*/" > : DEFAULT }
	<IN_MULTI_LINE_COMMENT>
		SPECIAL_TOKEN :
			{ <MULTI_LINE_COMMENT: "*/" > : DEFAULT }
	<IN_SINGLE_LINE_COMMENT,IN_FORMAL_COMMENT,IN_MULTI_LINE_COMMENT>
		MORE :
			{ < ~[] > }
/*****************************************************************************
 * RESERVED KEYWORDS AND LITERALS                                            *
 *****************************************************************************/
/*****************************************************************************
 * MODULE DECLARATION                                                        *
 *****************************************************************************/
TOKEN :
	{ < MODULE: "module" > |
	  < SPECIFICATION: "specification" > |
	  < IMPORTS: "imports" > | 
	  < EXPORTS: "exports" > |
	  < HIDDENS: "hiddens" >
	}
/*****************************************************************************
 * GRAMMAR DECLARATION                                                       *
 *****************************************************************************/
TOKEN :
	{ < SORTS: "sorts" > |
	  < STARTSYMBOL: "context-free start-symbols" > |
	  < CF: "CF" > |
	  < LEX: "LEX" >
	}
/*****************************************************************************
 * PRODUCTION DECLARATION                                                    *
 *****************************************************************************/
TOKEN :
	{ < SYNTAX: "syntax" > |
	  < VARIABLES: "variables" > |
	  < LEXICALSYNTAX: "lexical syntax" > |
	  < CFREESYNTAX: "context-free syntax"> |
	  < LEXICALVARS: "lexical variables" > |
	  < CONS: "cons" > 
	}
/*****************************************************************************
 * DISAMBIGUATION DECLARATION                                                *
 *****************************************************************************/
TOKEN :
	{ < LEFT: "left" > |
	  < ASSOC: "assoc" > |
	  < AVOID: "avoid" > |
	  < RIGHT: "right" > |
	  < PREFER: "prefer" > |
	  < BRACKET: "bracket" > |
	  < REJECT: "reject" > |
	  < NONASSOC: "non-assoc" > |
	  < RECOVER: "recover" > |
	  < DEPRECATED: "deprecated" > | 
	  < INDENTPADDING: "indentpadding" > |
	  < PRIORITIES: "priorities" > |
	  < CFREEPRIORITIES: "context-free priorities" > |
	  < LEXICALRESTRICTIONS: "lexical restrictions" > |
	  < CFREERESTRICTIONS: "context-free restrictions" > 
	}
/*****************************************************************************
 * LITERALS                                                                  *
 *****************************************************************************/
TOKEN :
	{ < INTEGER_LITERAL:
		<DECIMAL_LITERAL> (["l","L"])? | 
	  	<HEX_LITERAL> (["l","L"])? | 
	  	<OCTAL_LITERAL> (["l","L"])? > |
	  < #DECIMAL_LITERAL: ["1"-"9"] (["0"-"9"])* > |
	  < #HEX_LITERAL: "0" ["x","X"] (["0"-"9","a"-"f","A"-"F"])+ > |
	  < #OCTAL_LITERAL: "0" (["0"-"7"])* > |
	  < FLOATING_POINT_LITERAL:
    	(["0"-"9"])+ "." (["0"-"9"])* (<EXPONENT>)? (["f","F","d","D"])? | 
    	"." (["0"-"9"])+ (<EXPONENT>)? (["f","F","d","D"])? | 
    	(["0"-"9"])+ <EXPONENT> (["f","F","d","D"])? | 
    	(["0"-"9"])+ (<EXPONENT>)? ["f","F","d","D"] > |
	  < #EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+ > |
	  < CHARACTER_LITERAL:
	  	"'" ( (~["'","\\","\n","\r"]) | 
			("\\"
				( ["n","t","b","r","f","u","\\","'","\""] | 
				  ["0"-"7"] ( ["0"-"7"] )? | 
				  ["0"-"3"] ["0"-"7"] ["0"-"7"] ) ) ) "'" > |
	  < STRING_LITERAL:
    	"\"" ( (~["\"","\\"]) | 
			 ("\\"
				( ["n","t","b","r","f","u","\\","'","\""] | 
				  ["0"-"7"] ( ["0"-"7"] )? | 
				  ["0"-"3"] ["0"-"7"] ["0"-"7"] ) ) )* "\"" > |
	  < CHARCLASS_LITERAL:
		"\\" ( ["n","t","r"," ","\\","'","\""] |
			   ["0"-"9"] ) >
	}
/*****************************************************************************
 * IDENTIFIER                                                                *
 *****************************************************************************/
TOKEN :
	{ < IDENTIFIER: (<LETTER>|<DIGIT>) 
	                (<LETTER>|<DIGIT>|<APOSTROPHE>|<MINUS>)* > |
	  < LETTER: (<LCCHAR>|<UCCHAR>) > |
	  < LCCHAR: [ "a"-"z" ] > |
	  < UCCHAR: [ "A"-"Z" ] > |
	  < DIGIT: [ "0"-"9" ] >
	}
/*****************************************************************************
 * PARENTHESIS                                                               *
 *****************************************************************************/
TOKEN :
	{ < LPAREN: "(" > | 
	  < RPAREN: ")" > | 
	  < LBRACE: "{" > | 
	  < RBRACE: "}" > | 
	  < LBRACKET: "[" > |
	  < RBRACKET: "]" > |
	  < DLBRACKET: "[[" > | 
	  < DRBRACKET: "]]" > |
	  < LT: "<" > |
	  < GT: ">" > 
	}
/*****************************************************************************
 * OPERATORS                                                                 *
 *****************************************************************************/
TOKEN :
	{ < PLUS: "+" > |
	  < MINUS: "-" > |
	  < STAR: "*" > |
	  < SLASH: "/" >
	}
/*****************************************************************************
 * SEPARATORS                                                                *
 *****************************************************************************/
TOKEN :
	{ < COMMA: "," > |
	  < SEMICOLON: ";" > |
	  < DDOT: ":" > |
	  < DOT: "." > |
	  < QUESTIONMARK: "?" > |
	  < EXCLAMATIONMARK: "!" >
	}
/*****************************************************************************
 * SPECIAL SIGNS                                                             *
 *****************************************************************************/
TOKEN :
	{ < NUMBERSIGN: "#" > |
	  < AT: "@" > |
	  < DOLLAR: "$" > |
	  < VERTICALLINE: "|" > |
	  < TILDE: "~" > |
	  < AMPERSAND: "&" > |
	  < PERCENTAGE: "%" > |
	  < CIRCUMFLEXACCENT: "^" > |
	  < GRAVEACCENT: "`" > |
	  < APOSTROPHE: "'" > |
	  < ARROW: "->" > |
	  < ASSIGN: "=" > |
	  < NOTALLOWED: "-/-" > |
	  < LOWLINE: "_" > |
	  < QUOTATIONMARK: "\"" > |
	  < BACKSLASH: "\\" >
	}
FSTInfo NatInteger(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<INTEGER_LITERAL> {return productionEndTerminal("NatInteger","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo RealDigit(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<INTEGER_LITERAL> "." <INTEGER_LITERAL> {return productionEndTerminal("RealDigit","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Int(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[<MINUS>] n=NatInteger(true){ replaceName(n);} {return productionEndTerminal("Int","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Real(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[<MINUS>] n=RealDigit(true){ replaceName(n);} {return productionEndTerminal("Real","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo String(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<STRING_LITERAL> {return productionEndTerminal("String","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Char(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<CHARACTER_LITERAL> {return productionEndTerminal("Char","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CharClassLiteral(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<CHARCLASS_LITERAL> {return productionEndTerminal("CharClassLiteral","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Id(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	t=<IDENTIFIER>{ replaceName(new FSTInfo("<IDENTIFIER>",t.image));} {return productionEndTerminal("Id","{<IDENTIFIER>}","{<IDENTIFIER>}","Replacement","Default",first,token);}

 )  }

FSTInfo Module(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=ModuleDeclaration(true){ replaceName(n);} [n=ImportDeclaration(true){ replaceName(n);}] [n=ExportDeclaration(true){ replaceName(n);}] [n=HiddenDeclaration(true){ replaceName(n);}] <EOF> {return productionEndTerminal("Module","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ModName(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=ModNamePart(true){ replaceName(n);} [n=ModuleParameter(true){ replaceName(n);}] {return productionEndTerminal("ModName","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ModNamePart(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} (LOOKAHEAD(2) "/" n=Id(true){ replaceName(n);})* {return productionEndTerminal("ModNamePart","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ModuleParameter(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"[" (n=ModuleSort(true){ replaceName(n);})+ "]" {return productionEndTerminal("ModuleParameter","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ModuleSort(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Id(true){ replaceName(n);} {return productionEndTerminal("ModuleSort1","-","-","Replacement","Default",first,token);}
 |
	"[[" n=Id(true){ replaceName(n);} "]]" {return productionEndTerminal("ModuleSort2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ModuleDeclaration(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"module" n=ModName(true){ replaceName(n);} {return productionEndTerminal("ModuleDeclaration","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ImportDeclaration(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"imports" (n=ModName(true){ replaceName("ModName", n);}{ replaceName(n);})+ {return productionEndTerminal("ImportDeclaration","{ModName}{ImportModule}","{ModName}{ImportModule}","Replacement","Default",first,token);}

 )  }

FSTInfo ExportDeclaration(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"exports" (n=Grammer(true){ replaceName(n);})+ {return productionEndTerminal("ExportDeclaration","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo HiddenDeclaration(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"hiddens" (n=Grammer(true){ replaceName(n);})+ {return productionEndTerminal("HiddenDeclaration","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Grammer(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"sorts" (n=Sort(true){ replaceName(n);})+ {return productionEndTerminal("Grammer1","-","-","Replacement","Default",first,token);}
 |
	"context-free start-symbols" (n=Sort(true){ replaceName(n);})+ {return productionEndTerminal("Grammer2","-","-","Replacement","Default",first,token);}
 |
	n=Productions(true){ replaceName(n);} {return productionEndTerminal("Grammer3","-","-","Replacement","Default",first,token);}
 |
	n=Disambiguations(true){ replaceName(n);} {return productionEndTerminal("Grammer4","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Productions(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=ProdPart(true){ replaceName(n);} (n=Production(true){ replaceName(n);})* {return productionEndTerminal("Productions","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo ProdPart(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"syntax"  {return productionEndTerminal("ProdPart1","-","-","Replacement","Default",first,token);}
 |
	"lexical syntax"  {return productionEndTerminal("ProdPart2","-","-","Replacement","Default",first,token);}
 |
	"context-free syntax"  {return productionEndTerminal("ProdPart3","-","-","Replacement","Default",first,token);}
 |
	"variables"  {return productionEndTerminal("ProdPart4","-","-","Replacement","Default",first,token);}
 |
	"lexical variables"  {return productionEndTerminal("ProdPart5","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Disambiguations(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"context-free priorities" (n=Priority(true){ replaceName(n);})+ {return productionEndTerminal("Disambiguations1","-","-","Replacement","Default",first,token);}
 |
	"lexical restrictions" (n=Restriction(true){ replaceName(n);})+ {return productionEndTerminal("Disambiguations2","-","-","Replacement","Default",first,token);}
 |
	"context-free restrictions" (n=Restriction(true){ replaceName(n);})+ {return productionEndTerminal("Disambiguations3","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Production(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=Symbol(true){ replaceName(n);})* "->" (LOOKAHEAD(Symbol()) n=Symbol(true){ replaceName(n);})+ [LOOKAHEAD("{" Attribute()) n=OptAttributes(true){ replaceName(n);}] {return productionEndTerminal("Production","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Symbol(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD("(" Symbol() ")") "(" n=Symbol(true){ replaceName(n);} ")" [n=SortOp(true){ replaceName(n);}] [n=AlternativeSymbol(true){ replaceName(n);}] {return productionEndTerminal("Symbol1","-","-","Replacement","Default",first,token);}
 |
	n=Sort(true){ replaceName(n);} [n=AlternativeSymbol(true){ replaceName(n);}] {return productionEndTerminal("Symbol2","-","-","Replacement","Default",first,token);}
 |
	n=CharacterClass(true){ replaceName(n);} [n=AlternativeSymbol(true){ replaceName(n);}] {return productionEndTerminal("Symbol3","-","-","Replacement","Default",first,token);}
 |
	n=String(true){ replaceName(n);} [n=SortOp(true){ replaceName(n);}] [n=AlternativeSymbol(true){ replaceName(n);}] {return productionEndTerminal("Symbol4","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo AlternativeSymbol(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"|" n=Symbol(true){ replaceName(n);} {return productionEndTerminal("AlternativeSymbol","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Sort(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"[[" n=Id(true){ replaceName(n);} "]]" {return productionEndTerminal("Sort1","-","-","Replacement","Default",first,token);}
 |
	"<" n=Id(true){ replaceName(n);} [n=SortOp(true){ replaceName(n);}] ["-" n=CFOrLEX(true){ replaceName(n);}] ">" {return productionEndTerminal("Sort2","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} [n=SortOp(true){ replaceName(n);}] {return productionEndTerminal("Sort3","-","-","Replacement","Default",first,token);}
 |
	"{" n=Id(true){ replaceName(n);} n=String(true){ replaceName(n);} "}" [n=SortOp(true){ replaceName(n);}] {return productionEndTerminal("Sort4","-","-","Replacement","Default",first,token);}
 |
	"(" (n=Sort(true){ replaceName(n);})+ ")" [n=SortOp(true){ replaceName(n);}] {return productionEndTerminal("Sort5","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo SortOp(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*"  {return productionEndTerminal("SortOp1","-","-","Replacement","Default",first,token);}
 |
	"+"  {return productionEndTerminal("SortOp2","-","-","Replacement","Default",first,token);}
 |
	"?"  {return productionEndTerminal("SortOp3","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CFOrLEX(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"CF"  {return productionEndTerminal("CFOrLEX1","-","-","Replacement","Default",first,token);}
 |
	"LEX"  {return productionEndTerminal("CFOrLEX2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CharacterClass(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[<TILDE>] "[" (n=CharClass(true){ replaceName(n);})* "]" [n=SortOp(true){ replaceName(n);}] {return productionEndTerminal("CharacterClass","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo CharClass(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"\\" n=SpecialSign(true){ replaceName(n);} {return productionEndTerminal("CharClass1","-","-","Replacement","Default",first,token);}
 |
	n=Id(true){ replaceName(n);} {return productionEndTerminal("CharClass2","-","-","Replacement","Default",first,token);}
 |
	n=Int(true){ replaceName(n);} {return productionEndTerminal("CharClass3","-","-","Replacement","Default",first,token);}
 |
	n=CharClassLiteral(true){ replaceName(n);} {return productionEndTerminal("CharClass4","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo SpecialSign(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"("  {return productionEndTerminal("SpecialSign1","-","-","Replacement","Default",first,token);}
 |
	")"  {return productionEndTerminal("SpecialSign2","-","-","Replacement","Default",first,token);}
 |
	"{"  {return productionEndTerminal("SpecialSign3","-","-","Replacement","Default",first,token);}
 |
	"}"  {return productionEndTerminal("SpecialSign4","-","-","Replacement","Default",first,token);}
 |
	"["  {return productionEndTerminal("SpecialSign5","-","-","Replacement","Default",first,token);}
 |
	"]"  {return productionEndTerminal("SpecialSign6","-","-","Replacement","Default",first,token);}
 |
	","  {return productionEndTerminal("SpecialSign7","-","-","Replacement","Default",first,token);}
 |
	"<"  {return productionEndTerminal("SpecialSign8","-","-","Replacement","Default",first,token);}
 |
	">"  {return productionEndTerminal("SpecialSign9","-","-","Replacement","Default",first,token);}
 |
	":"  {return productionEndTerminal("SpecialSign10","-","-","Replacement","Default",first,token);}
 |
	"."  {return productionEndTerminal("SpecialSign11","-","-","Replacement","Default",first,token);}
 |
	"?"  {return productionEndTerminal("SpecialSign12","-","-","Replacement","Default",first,token);}
 |
	"!"  {return productionEndTerminal("SpecialSign13","-","-","Replacement","Default",first,token);}
 |
	"%"  {return productionEndTerminal("SpecialSign14","-","-","Replacement","Default",first,token);}
 |
	"_"  {return productionEndTerminal("SpecialSign15","-","-","Replacement","Default",first,token);}
 |
	"$"  {return productionEndTerminal("SpecialSign16","-","-","Replacement","Default",first,token);}
 |
	"@"  {return productionEndTerminal("SpecialSign17","-","-","Replacement","Default",first,token);}
 |
	"~"  {return productionEndTerminal("SpecialSign18","-","-","Replacement","Default",first,token);}
 |
	"/"  {return productionEndTerminal("SpecialSign19","-","-","Replacement","Default",first,token);}
 |
	"#"  {return productionEndTerminal("SpecialSign20","-","-","Replacement","Default",first,token);}
 |
	"|"  {return productionEndTerminal("SpecialSign21","-","-","Replacement","Default",first,token);}
 |
	"+"  {return productionEndTerminal("SpecialSign22","-","-","Replacement","Default",first,token);}
 |
	"-"  {return productionEndTerminal("SpecialSign23","-","-","Replacement","Default",first,token);}
 |
	"*"  {return productionEndTerminal("SpecialSign24","-","-","Replacement","Default",first,token);}
 |
	";"  {return productionEndTerminal("SpecialSign25","-","-","Replacement","Default",first,token);}
 |
	"`"  {return productionEndTerminal("SpecialSign26","-","-","Replacement","Default",first,token);}
 |
	"="  {return productionEndTerminal("SpecialSign27","-","-","Replacement","Default",first,token);}
 |
	"&"  {return productionEndTerminal("SpecialSign28","-","-","Replacement","Default",first,token);}
 |
	"^"  {return productionEndTerminal("SpecialSign29","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo OptAttributes(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" n=Attribute(true){ replaceName(n);} (LOOKAHEAD(2) "," n=Attribute(true){ replaceName(n);})* "}" {return productionEndTerminal("OptAttributes","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Attribute(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"bracket"  {return productionEndTerminal("Attribute1","-","-","Replacement","Default",first,token);}
 |
	"prefer"  {return productionEndTerminal("Attribute2","-","-","Replacement","Default",first,token);}
 |
	"avoid"  {return productionEndTerminal("Attribute3","-","-","Replacement","Default",first,token);}
 |
	"left"  {return productionEndTerminal("Attribute4","-","-","Replacement","Default",first,token);}
 |
	"right"  {return productionEndTerminal("Attribute5","-","-","Replacement","Default",first,token);}
 |
	"non-assoc"  {return productionEndTerminal("Attribute6","-","-","Replacement","Default",first,token);}
 |
	"assoc"  {return productionEndTerminal("Attribute7","-","-","Replacement","Default",first,token);}
 |
	"reject"  {return productionEndTerminal("Attribute8","-","-","Replacement","Default",first,token);}
 |
	"recover"  {return productionEndTerminal("Attribute9","-","-","Replacement","Default",first,token);}
 |
	"indentpadding"  {return productionEndTerminal("Attribute10","-","-","Replacement","Default",first,token);}
 |
	n=Constructor(true){ replaceName(n);} {return productionEndTerminal("Attribute11","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Constructor(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"cons" "(" n=String(true){ replaceName(n);} ")" {return productionEndTerminal("Constructor1","-","-","Replacement","Default",first,token);}
 |
	"deprecated" "(" n=String(true){ replaceName(n);} ")" {return productionEndTerminal("Constructor2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Priority(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(3) "{" [n=Attribute(true){ replaceName(n);} ":"] (n=Production(true){ replaceName(n);})+ "}" [LOOKAHEAD(2) ">" n=Priority(true){ replaceName(n);}] {return productionEndTerminal("Priority1","-","-","Replacement","Default",first,token);}
 |
	n=Production(true){ replaceName(n);} (LOOKAHEAD(2) ">" n=Priority(true){ replaceName(n);})* {return productionEndTerminal("Priority2","-","-","Replacement","Default",first,token);}

 )  }

FSTInfo Restriction(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=Symbol(true){ replaceName(n);})+ "-/-" n=CharacterClass(true){ replaceName(n);} (LOOKAHEAD(2) "." n=CharacterClass(true){ replaceName(n);})* {return productionEndTerminal("Restriction","-","-","Replacement","Default",first,token);}

 )  }

