// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

layer syntax ;

public class BaliParseNode extends BaliParse {

    final public static int ARG_LENGTH = 3 ;
    final public static int TOK_LENGTH = 1 /* Kludge! */ ;

    public Options getOptions () {
        
        AstNode node = arg[0].arg [0] ;
        return (node != null) ? (Options) node : null ;
    }

    public ParserCode getParserCode () {
        
        AstNode node = arg[1].arg [0] ;
        return (node != null) ? (ParserCode) node : null ;
    }

    public Statements getStatements () {
        
        AstNode node = arg[2].arg [0] ;
        return (node != null) ? (Statements) node : null ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, false, false} ;
    }

    public BaliParseNode setParms
    (AstOptNode arg0, AstOptNode arg1, AstOptNode arg2) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* [Options] */
        arg [1] = arg1 ;            /* [ParserCode] */
        arg [2] = arg2 ;            /* [Statements] */
        
        InitChildren () ;
        return (BaliParseNode) this ;
    }

}
