#!/bin/sh

EQUATION=$1
TARGET=`basename $EQUATION .equation`

if [ -e $TARGET ]; then
	rm -rf $TARGET
fi

composer --equation=$EQUATION
jak2java $TARGET/*.jak
javac $TARGET/*.java
java $TARGET.Notepad
