options {
  JAVA_UNICODE_ESCAPE = true;
  STATIC=false;
}


PARSER_BEGIN(JavaCCParser)
package tmp.generated_javacc;

import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;
import de.ovgu.cide.fstgen.ast.*;


public class JavaCCParser extends AbstractFSTParser {


  /*
   * Returns true if the next token is not in the FOLLOW list of "expansion".
   * It is used to decide when the end of an "expansion" has been reached.
   */
  private boolean notTailOfExpansionUnit() {
    Token t;
    t = getToken(1);
    if (t.kind == BIT_OR || t.kind == COMMA || t.kind == RPAREN || t.kind == RBRACE || t.kind == RBRACKET) return false;
    return true;
  }

}

PARSER_END(JavaCCParser)


/**********************************************
 * THE JAVACC TOKEN SPECIFICATION STARTS HERE *
 **********************************************/

/* JAVACC RESERVED WORDS: These are the only tokens in JavaCC but not in Java */

TOKEN :
{
  < _OPTIONS: "options" >
| < _LOOKAHEAD: "LOOKAHEAD" >
| < _IGNORE_CASE: "IGNORE_CASE" >
| < _PARSER_BEGIN: "PARSER_BEGIN" >
| < _PARSER_END: "PARSER_END" >
| < _JAVACODE: "JAVACODE" >
| < _TOKEN: "TOKEN" >
| < _SPECIAL_TOKEN: "SPECIAL_TOKEN" >
| < _MORE: "MORE" >
| < _SKIP: "SKIP" >
| < _TOKEN_MGR_DECLS: "TOKEN_MGR_DECLS" >
| < _EOF: "EOF" >
}

/*
 * The remainder of the tokens are exactly (except for the removal of tokens
 * containing ">>" and "<<") as in the Java grammar and must be diff equivalent
 * (again with the exceptions above) to it.
 */

/* WHITE SPACE */

SPECIAL_TOKEN :
{
  " "
| "\t"
| "\n"
| "\r"
| "\f"
| "/*@egen*/" : AFTER_EGEN
                        
}

<AFTER_EGEN> SPECIAL_TOKEN :
{
  <~[]>  : DEFAULT
}

/* COMMENTS */

MORE :
{
  "//" : IN_SINGLE_LINE_COMMENT
|
  <"/**" ~["/"]> : IN_FORMAL_COMMENT
|
  "/*" : IN_MULTI_LINE_COMMENT
|
  "/*@bgen(jjtree"
     : IN_MULTI_LINE_COMMENT
}

<IN_SINGLE_LINE_COMMENT>
SPECIAL_TOKEN :
{
  <SINGLE_LINE_COMMENT: "\n" | "\r" | "\r\n" > : DEFAULT
}

<IN_FORMAL_COMMENT>
SPECIAL_TOKEN :
{
  <FORMAL_COMMENT: "*/" > : DEFAULT
}

<IN_MULTI_LINE_COMMENT>
SPECIAL_TOKEN :
{
  <MULTI_LINE_COMMENT: "*/" > : DEFAULT
}

<IN_SINGLE_LINE_COMMENT,IN_FORMAL_COMMENT,IN_MULTI_LINE_COMMENT>
MORE :
{
  < ~[] >
}

/* JAVA RESERVED WORDS AND LITERALS */

TOKEN :
{
  < ABSTRACT: "abstract" >
| < ASSERT: "assert" >
| < BOOLEAN: "boolean" >
| < BREAK: "break" >
| < BYTE: "byte" >
| < CASE: "case" >
| < CATCH: "catch" >
| < CHAR: "char" >
| < CLASS: "class" >
| < CONST: "const" >
| < CONTINUE: "continue" >
| < _DEFAULT: "default" >
| < DO: "do" >
| < DOUBLE: "double" >
| < ELSE: "else" >
| < ENUM: "enum" >
| < EXTENDS: "extends" >
| < FALSE: "false" >
| < FINAL: "final" >
| < FINALLY: "finally" >
| < FLOAT: "float" >
| < FOR: "for" >
| < GOTO: "goto" >
| < IF: "if" >
| < IMPLEMENTS: "implements" >
| < IMPORT: "import" >
| < INSTANCEOF: "instanceof" >
| < INT: "int" >
| < INTERFACE: "interface" >
| < LONG: "long" >
| < NATIVE: "native" >
| < NEW: "new" >
| < NULL: "null" >
| < PACKAGE: "package">
| < PRIVATE: "private" >
| < PROTECTED: "protected" >
| < PUBLIC: "public" >
| < RETURN: "return" >
| < SHORT: "short" >
| < STATIC: "static" >
| < STRICTFP: "strictfp" >
| < SUPER: "super" >
| < SWITCH: "switch" >
| < SYNCHRONIZED: "synchronized" >
| < THIS: "this" >
| < THROW: "throw" >
| < THROWS: "throws" >
| < TRANSIENT: "transient" >
| < TRUE: "true" >
| < TRY: "try" >
| < VOID: "void" >
| < VOLATILE: "volatile" >
| < WHILE: "while" >
}

/* JAVA LITERALS */

TOKEN :
{
  < INTEGER_LITERAL:
        <DECIMAL_LITERAL> (["l","L"])?
      | <HEX_LITERAL> (["l","L"])?
      | <OCTAL_LITERAL> (["l","L"])?
  >
|
  < #DECIMAL_LITERAL: ["1"-"9"] (["0"-"9"])* >
|
  < #HEX_LITERAL: "0" ["x","X"] (["0"-"9","a"-"f","A"-"F"])+ >
|
  < #OCTAL_LITERAL: "0" (["0"-"7"])* >
|
  < FLOATING_POINT_LITERAL:
        <DECIMAL_FLOATING_POINT_LITERAL>
      | <HEXADECIMAL_FLOATING_POINT_LITERAL>
  >
|
  < #DECIMAL_FLOATING_POINT_LITERAL:
        (["0"-"9"])+ "." (["0"-"9"])* (<DECIMAL_EXPONENT>)? (["f","F","d","D"])?
      | "." (["0"-"9"])+ (<DECIMAL_EXPONENT>)? (["f","F","d","D"])?
      | (["0"-"9"])+ <DECIMAL_EXPONENT> (["f","F","d","D"])?
      | (["0"-"9"])+ (<DECIMAL_EXPONENT>)? ["f","F","d","D"]
  >
|
  < #DECIMAL_EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+ >
|
  < #HEXADECIMAL_FLOATING_POINT_LITERAL:
        "0" ["x", "X"] (["0"-"9","a"-"f","A"-"F"])+ (".")? <HEXADECIMAL_EXPONENT> (["f","F","d","D"])?
      | "0" ["x", "X"] (["0"-"9","a"-"f","A"-"F"])* "." (["0"-"9","a"-"f","A"-"F"])+ <HEXADECIMAL_EXPONENT> (["f","F","d","D"])?
  >
|
  < #HEXADECIMAL_EXPONENT: ["p","P"] (["+","-"])? (["0"-"9"])+ >
|
  < CHARACTER_LITERAL:
      "'"
      (   (~["'","\\","\n","\r"])
        | ("\\"
            ( ["n","t","b","r","f","u","\\","'","\""]
            | ["0"-"7"] ( ["0"-"7"] )?
            | ["0"-"3"] ["0"-"7"] ["0"-"7"]
            )
          )
      )
      "'"
  >
|
  < STRING_LITERAL:
      "\""
      (   (~["\"","\\","\n","\r"])
        | ("\\"
            ( ["n","t","b","r","f","u","\\","'","\""]
            | ["0"-"7"] ( ["0"-"7"] )?
            | ["0"-"3"] ["0"-"7"] ["0"-"7"]
            )
          )
      )*
      "\""
  >
}

/* SEPARATORS */

TOKEN :
{
  < LPAREN: "(" >
| < RPAREN: ")" >
| < LBRACE: "{" >
| < RBRACE: "}" >
| < LBRACKET: "[" >
| < RBRACKET: "]" >
| < SEMICOLON: ";" >
| < COMMA: "," >
| < DOT: "." >
}

/* OPERATORS */

TOKEN :
{
  < ASSIGN: "=" >
//| < GT: ">" >
| < LT: "<" >
| < BANG: "!" >
| < TILDE: "~" >
| < HOOK: "?" >
| < COLON: ":" >
| < EQ: "==" >
| < LE: "<=" >
| < GE: ">=" >
| < NE: "!=" >
| < SC_OR: "||" >
| < SC_AND: "&&" >
| < INCR: "++" >
| < DECR: "--" >
| < PLUS: "+" >
| < MINUS: "-" >
| < STAR: "*" >
| < SLASH: "/" >
| < BIT_AND: "&" >
| < BIT_OR: "|" >
| < XOR: "^" >
| < REM: "%" >
//	| < LSHIFT: "<<" >
//	| < RSIGNEDSHIFT: ">>" >
//	| < RUNSIGNEDSHIFT: ">>>" >
| < PLUSASSIGN: "+=" >
| < MINUSASSIGN: "-=" >
| < STARASSIGN: "*=" >
| < SLASHASSIGN: "/=" >
| < ANDASSIGN: "&=" >
| < ORASSIGN: "|=" >
| < XORASSIGN: "^=" >
| < REMASSIGN: "%=" >
//	| < LSHIFTASSIGN: "<<=" >
//	| < RSIGNEDSHIFTASSIGN: ">>=" >
//	| < RUNSIGNEDSHIFTASSIGN: ">>>=" >
}

/* >'s need special attention due to generics syntax. */
TOKEN :
{
  < RUNSIGNEDSHIFT: ">>>" >
| < RSIGNEDSHIFT: ">>" >
| < GT: ">" >
}



/* IDENTIFIERS */

TOKEN :
{
  < IDENTIFIER: <LETTER> (<PART_LETTER>)* >
|
  < #LETTER:
      [  // all chars for which Character.isIdentifierStart is true
         "$",
         "A"-"Z",
         "_",
         "a"-"z",
         "\u00a2"-"\u00a5",
         "\u00aa",
         "\u00b5",
         "\u00ba",
         "\u00c0"-"\u00d6",
         "\u00d8"-"\u00f6",
         "\u00f8"-"\u021f",
         "\u0222"-"\u0233",
         "\u0250"-"\u02ad",
         "\u02b0"-"\u02b8",
         "\u02bb"-"\u02c1",
         "\u02d0"-"\u02d1",
         "\u02e0"-"\u02e4",
         "\u02ee",
         "\u037a",
         "\u0386",
         "\u0388"-"\u038a",
         "\u038c",
         "\u038e"-"\u03a1",
         "\u03a3"-"\u03ce",
         "\u03d0"-"\u03d7",
         "\u03da"-"\u03f3",
         "\u0400"-"\u0481",
         "\u048c"-"\u04c4",
         "\u04c7"-"\u04c8",
         "\u04cb"-"\u04cc",
         "\u04d0"-"\u04f5",
         "\u04f8"-"\u04f9",
         "\u0531"-"\u0556",
         "\u0559",
         "\u0561"-"\u0587",
         "\u05d0"-"\u05ea",
         "\u05f0"-"\u05f2",
         "\u0621"-"\u063a",
         "\u0640"-"\u064a",
         "\u0671"-"\u06d3",
         "\u06d5",
         "\u06e5"-"\u06e6",
         "\u06fa"-"\u06fc",
         "\u0710",
         "\u0712"-"\u072c",
         "\u0780"-"\u07a5",
         "\u0905"-"\u0939",
         "\u093d",
         "\u0950",
         "\u0958"-"\u0961",
         "\u0985"-"\u098c",
         "\u098f"-"\u0990",
         "\u0993"-"\u09a8",
         "\u09aa"-"\u09b0",
         "\u09b2",
         "\u09b6"-"\u09b9",
         "\u09dc"-"\u09dd",
         "\u09df"-"\u09e1",
         "\u09f0"-"\u09f3",
         "\u0a05"-"\u0a0a",
         "\u0a0f"-"\u0a10",
         "\u0a13"-"\u0a28",
         "\u0a2a"-"\u0a30",
         "\u0a32"-"\u0a33",
         "\u0a35"-"\u0a36",
         "\u0a38"-"\u0a39",
         "\u0a59"-"\u0a5c",
         "\u0a5e",
         "\u0a72"-"\u0a74",
         "\u0a85"-"\u0a8b",
         "\u0a8d",
         "\u0a8f"-"\u0a91",
         "\u0a93"-"\u0aa8",
         "\u0aaa"-"\u0ab0",
         "\u0ab2"-"\u0ab3",
         "\u0ab5"-"\u0ab9",
         "\u0abd",
         "\u0ad0",
         "\u0ae0",
         "\u0b05"-"\u0b0c",
         "\u0b0f"-"\u0b10",
         "\u0b13"-"\u0b28",
         "\u0b2a"-"\u0b30",
         "\u0b32"-"\u0b33",
         "\u0b36"-"\u0b39",
         "\u0b3d",
         "\u0b5c"-"\u0b5d",
         "\u0b5f"-"\u0b61",
         "\u0b85"-"\u0b8a",
         "\u0b8e"-"\u0b90",
         "\u0b92"-"\u0b95",
         "\u0b99"-"\u0b9a",
         "\u0b9c",
         "\u0b9e"-"\u0b9f",
         "\u0ba3"-"\u0ba4",
         "\u0ba8"-"\u0baa",
         "\u0bae"-"\u0bb5",
         "\u0bb7"-"\u0bb9",
         "\u0c05"-"\u0c0c",
         "\u0c0e"-"\u0c10",
         "\u0c12"-"\u0c28",
         "\u0c2a"-"\u0c33",
         "\u0c35"-"\u0c39",
         "\u0c60"-"\u0c61",
         "\u0c85"-"\u0c8c",
         "\u0c8e"-"\u0c90",
         "\u0c92"-"\u0ca8",
         "\u0caa"-"\u0cb3",
         "\u0cb5"-"\u0cb9",
         "\u0cde",
         "\u0ce0"-"\u0ce1",
         "\u0d05"-"\u0d0c",
         "\u0d0e"-"\u0d10",
         "\u0d12"-"\u0d28",
         "\u0d2a"-"\u0d39",
         "\u0d60"-"\u0d61",
         "\u0d85"-"\u0d96",
         "\u0d9a"-"\u0db1",
         "\u0db3"-"\u0dbb",
         "\u0dbd",
         "\u0dc0"-"\u0dc6",
         "\u0e01"-"\u0e30",
         "\u0e32"-"\u0e33",
         "\u0e3f"-"\u0e46",
         "\u0e81"-"\u0e82",
         "\u0e84",
         "\u0e87"-"\u0e88",
         "\u0e8a",
         "\u0e8d",
         "\u0e94"-"\u0e97",
         "\u0e99"-"\u0e9f",
         "\u0ea1"-"\u0ea3",
         "\u0ea5",
         "\u0ea7",
         "\u0eaa"-"\u0eab",
         "\u0ead"-"\u0eb0",
         "\u0eb2"-"\u0eb3",
         "\u0ebd",
         "\u0ec0"-"\u0ec4",
         "\u0ec6",
         "\u0edc"-"\u0edd",
         "\u0f00",
         "\u0f40"-"\u0f47",
         "\u0f49"-"\u0f6a",
         "\u0f88"-"\u0f8b",
         "\u1000"-"\u1021",
         "\u1023"-"\u1027",
         "\u1029"-"\u102a",
         "\u1050"-"\u1055",
         "\u10a0"-"\u10c5",
         "\u10d0"-"\u10f6",
         "\u1100"-"\u1159",
         "\u115f"-"\u11a2",
         "\u11a8"-"\u11f9",
         "\u1200"-"\u1206",
         "\u1208"-"\u1246",
         "\u1248",
         "\u124a"-"\u124d",
         "\u1250"-"\u1256",
         "\u1258",
         "\u125a"-"\u125d",
         "\u1260"-"\u1286",
         "\u1288",
         "\u128a"-"\u128d",
         "\u1290"-"\u12ae",
         "\u12b0",
         "\u12b2"-"\u12b5",
         "\u12b8"-"\u12be",
         "\u12c0",
         "\u12c2"-"\u12c5",
         "\u12c8"-"\u12ce",
         "\u12d0"-"\u12d6",
         "\u12d8"-"\u12ee",
         "\u12f0"-"\u130e",
         "\u1310",
         "\u1312"-"\u1315",
         "\u1318"-"\u131e",
         "\u1320"-"\u1346",
         "\u1348"-"\u135a",
         "\u13a0"-"\u13f4",
         "\u1401"-"\u166c",
         "\u166f"-"\u1676",
         "\u1681"-"\u169a",
         "\u16a0"-"\u16ea",
         "\u1780"-"\u17b3",
         "\u17db",
         "\u1820"-"\u1877",
         "\u1880"-"\u18a8",
         "\u1e00"-"\u1e9b",
         "\u1ea0"-"\u1ef9",
         "\u1f00"-"\u1f15",
         "\u1f18"-"\u1f1d",
         "\u1f20"-"\u1f45",
         "\u1f48"-"\u1f4d",
         "\u1f50"-"\u1f57",
         "\u1f59",
         "\u1f5b",
         "\u1f5d",
         "\u1f5f"-"\u1f7d",
         "\u1f80"-"\u1fb4",
         "\u1fb6"-"\u1fbc",
         "\u1fbe",
         "\u1fc2"-"\u1fc4",
         "\u1fc6"-"\u1fcc",
         "\u1fd0"-"\u1fd3",
         "\u1fd6"-"\u1fdb",
         "\u1fe0"-"\u1fec",
         "\u1ff2"-"\u1ff4",
         "\u1ff6"-"\u1ffc",
         "\u203f"-"\u2040",
         "\u207f",
         "\u20a0"-"\u20af",
         "\u2102",
         "\u2107",
         "\u210a"-"\u2113",
         "\u2115",
         "\u2119"-"\u211d",
         "\u2124",
         "\u2126",
         "\u2128",
         "\u212a"-"\u212d",
         "\u212f"-"\u2131",
         "\u2133"-"\u2139",
         "\u2160"-"\u2183",
         "\u3005"-"\u3007",
         "\u3021"-"\u3029",
         "\u3031"-"\u3035",
         "\u3038"-"\u303a",
         "\u3041"-"\u3094",
         "\u309d"-"\u309e",
         "\u30a1"-"\u30fe",
         "\u3105"-"\u312c",
         "\u3131"-"\u318e",
         "\u31a0"-"\u31b7",
         "\u3400"-"\u4db5",
         "\u4e00"-"\u9fa5",
         "\ua000"-"\ua48c",
         "\uac00"-"\ud7a3",
         "\uf900"-"\ufa2d",
         "\ufb00"-"\ufb06",
         "\ufb13"-"\ufb17",
         "\ufb1d",
         "\ufb1f"-"\ufb28",
         "\ufb2a"-"\ufb36",
         "\ufb38"-"\ufb3c",
         "\ufb3e",
         "\ufb40"-"\ufb41",
         "\ufb43"-"\ufb44",
         "\ufb46"-"\ufbb1",
         "\ufbd3"-"\ufd3d",
         "\ufd50"-"\ufd8f",
         "\ufd92"-"\ufdc7",
         "\ufdf0"-"\ufdfb",
         "\ufe33"-"\ufe34",
         "\ufe4d"-"\ufe4f",
         "\ufe69",
         "\ufe70"-"\ufe72",
         "\ufe74",
         "\ufe76"-"\ufefc",
         "\uff04",
         "\uff21"-"\uff3a",
         "\uff3f",
         "\uff41"-"\uff5a",
         "\uff65"-"\uffbe",
         "\uffc2"-"\uffc7",
         "\uffca"-"\uffcf",
         "\uffd2"-"\uffd7",
         "\uffda"-"\uffdc",
         "\uffe0"-"\uffe1",
         "\uffe5"-"\uffe6"
      ]
  >
|
  < #PART_LETTER:
      [  // all chars for which Character.isIdentifierPart is true
         "\u0000"-"\u0008",
         "\u000e"-"\u001b",
         "$",
         "0"-"9",
         "A"-"Z",
         "_",
         "a"-"z",
         "\u007f"-"\u009f",
         "\u00a2"-"\u00a5",
         "\u00aa",
         "\u00b5",
         "\u00ba",
         "\u00c0"-"\u00d6",
         "\u00d8"-"\u00f6",
         "\u00f8"-"\u021f",
         "\u0222"-"\u0233",
         "\u0250"-"\u02ad",
         "\u02b0"-"\u02b8",
         "\u02bb"-"\u02c1",
         "\u02d0"-"\u02d1",
         "\u02e0"-"\u02e4",
         "\u02ee",
         "\u0300"-"\u034e",
         "\u0360"-"\u0362",
         "\u037a",
         "\u0386",
         "\u0388"-"\u038a",
         "\u038c",
         "\u038e"-"\u03a1",
         "\u03a3"-"\u03ce",
         "\u03d0"-"\u03d7",
         "\u03da"-"\u03f3",
         "\u0400"-"\u0481",
         "\u0483"-"\u0486",
         "\u048c"-"\u04c4",
         "\u04c7"-"\u04c8",
         "\u04cb"-"\u04cc",
         "\u04d0"-"\u04f5",
         "\u04f8"-"\u04f9",
         "\u0531"-"\u0556",
         "\u0559",
         "\u0561"-"\u0587",
         "\u0591"-"\u05a1",
         "\u05a3"-"\u05b9",
         "\u05bb"-"\u05bd",
         "\u05bf",
         "\u05c1"-"\u05c2",
         "\u05c4",
         "\u05d0"-"\u05ea",
         "\u05f0"-"\u05f2",
         "\u0621"-"\u063a",
         "\u0640"-"\u0655",
         "\u0660"-"\u0669",
         "\u0670"-"\u06d3",
         "\u06d5"-"\u06dc",
         "\u06df"-"\u06e8",
         "\u06ea"-"\u06ed",
         "\u06f0"-"\u06fc",
         "\u070f"-"\u072c",
         "\u0730"-"\u074a",
         "\u0780"-"\u07b0",
         "\u0901"-"\u0903",
         "\u0905"-"\u0939",
         "\u093c"-"\u094d",
         "\u0950"-"\u0954",
         "\u0958"-"\u0963",
         "\u0966"-"\u096f",
         "\u0981"-"\u0983",
         "\u0985"-"\u098c",
         "\u098f"-"\u0990",
         "\u0993"-"\u09a8",
         "\u09aa"-"\u09b0",
         "\u09b2",
         "\u09b6"-"\u09b9",
         "\u09bc",
         "\u09be"-"\u09c4",
         "\u09c7"-"\u09c8",
         "\u09cb"-"\u09cd",
         "\u09d7",
         "\u09dc"-"\u09dd",
         "\u09df"-"\u09e3",
         "\u09e6"-"\u09f3",
         "\u0a02",
         "\u0a05"-"\u0a0a",
         "\u0a0f"-"\u0a10",
         "\u0a13"-"\u0a28",
         "\u0a2a"-"\u0a30",
         "\u0a32"-"\u0a33",
         "\u0a35"-"\u0a36",
         "\u0a38"-"\u0a39",
         "\u0a3c",
         "\u0a3e"-"\u0a42",
         "\u0a47"-"\u0a48",
         "\u0a4b"-"\u0a4d",
         "\u0a59"-"\u0a5c",
         "\u0a5e",
         "\u0a66"-"\u0a74",
         "\u0a81"-"\u0a83",
         "\u0a85"-"\u0a8b",
         "\u0a8d",
         "\u0a8f"-"\u0a91",
         "\u0a93"-"\u0aa8",
         "\u0aaa"-"\u0ab0",
         "\u0ab2"-"\u0ab3",
         "\u0ab5"-"\u0ab9",
         "\u0abc"-"\u0ac5",
         "\u0ac7"-"\u0ac9",
         "\u0acb"-"\u0acd",
         "\u0ad0",
         "\u0ae0",
         "\u0ae6"-"\u0aef",
         "\u0b01"-"\u0b03",
         "\u0b05"-"\u0b0c",
         "\u0b0f"-"\u0b10",
         "\u0b13"-"\u0b28",
         "\u0b2a"-"\u0b30",
         "\u0b32"-"\u0b33",
         "\u0b36"-"\u0b39",
         "\u0b3c"-"\u0b43",
         "\u0b47"-"\u0b48",
         "\u0b4b"-"\u0b4d",
         "\u0b56"-"\u0b57",
         "\u0b5c"-"\u0b5d",
         "\u0b5f"-"\u0b61",
         "\u0b66"-"\u0b6f",
         "\u0b82"-"\u0b83",
         "\u0b85"-"\u0b8a",
         "\u0b8e"-"\u0b90",
         "\u0b92"-"\u0b95",
         "\u0b99"-"\u0b9a",
         "\u0b9c",
         "\u0b9e"-"\u0b9f",
         "\u0ba3"-"\u0ba4",
         "\u0ba8"-"\u0baa",
         "\u0bae"-"\u0bb5",
         "\u0bb7"-"\u0bb9",
         "\u0bbe"-"\u0bc2",
         "\u0bc6"-"\u0bc8",
         "\u0bca"-"\u0bcd",
         "\u0bd7",
         "\u0be7"-"\u0bef",
         "\u0c01"-"\u0c03",
         "\u0c05"-"\u0c0c",
         "\u0c0e"-"\u0c10",
         "\u0c12"-"\u0c28",
         "\u0c2a"-"\u0c33",
         "\u0c35"-"\u0c39",
         "\u0c3e"-"\u0c44",
         "\u0c46"-"\u0c48",
         "\u0c4a"-"\u0c4d",
         "\u0c55"-"\u0c56",
         "\u0c60"-"\u0c61",
         "\u0c66"-"\u0c6f",
         "\u0c82"-"\u0c83",
         "\u0c85"-"\u0c8c",
         "\u0c8e"-"\u0c90",
         "\u0c92"-"\u0ca8",
         "\u0caa"-"\u0cb3",
         "\u0cb5"-"\u0cb9",
         "\u0cbe"-"\u0cc4",
         "\u0cc6"-"\u0cc8",
         "\u0cca"-"\u0ccd",
         "\u0cd5"-"\u0cd6",
         "\u0cde",
         "\u0ce0"-"\u0ce1",
         "\u0ce6"-"\u0cef",
         "\u0d02"-"\u0d03",
         "\u0d05"-"\u0d0c",
         "\u0d0e"-"\u0d10",
         "\u0d12"-"\u0d28",
         "\u0d2a"-"\u0d39",
         "\u0d3e"-"\u0d43",
         "\u0d46"-"\u0d48",
         "\u0d4a"-"\u0d4d",
         "\u0d57",
         "\u0d60"-"\u0d61",
         "\u0d66"-"\u0d6f",
         "\u0d82"-"\u0d83",
         "\u0d85"-"\u0d96",
         "\u0d9a"-"\u0db1",
         "\u0db3"-"\u0dbb",
         "\u0dbd",
         "\u0dc0"-"\u0dc6",
         "\u0dca",
         "\u0dcf"-"\u0dd4",
         "\u0dd6",
         "\u0dd8"-"\u0ddf",
         "\u0df2"-"\u0df3",
         "\u0e01"-"\u0e3a",
         "\u0e3f"-"\u0e4e",
         "\u0e50"-"\u0e59",
         "\u0e81"-"\u0e82",
         "\u0e84",
         "\u0e87"-"\u0e88",
         "\u0e8a",
         "\u0e8d",
         "\u0e94"-"\u0e97",
         "\u0e99"-"\u0e9f",
         "\u0ea1"-"\u0ea3",
         "\u0ea5",
         "\u0ea7",
         "\u0eaa"-"\u0eab",
         "\u0ead"-"\u0eb9",
         "\u0ebb"-"\u0ebd",
         "\u0ec0"-"\u0ec4",
         "\u0ec6",
         "\u0ec8"-"\u0ecd",
         "\u0ed0"-"\u0ed9",
         "\u0edc"-"\u0edd",
         "\u0f00",
         "\u0f18"-"\u0f19",
         "\u0f20"-"\u0f29",
         "\u0f35",
         "\u0f37",
         "\u0f39",
         "\u0f3e"-"\u0f47",
         "\u0f49"-"\u0f6a",
         "\u0f71"-"\u0f84",
         "\u0f86"-"\u0f8b",
         "\u0f90"-"\u0f97",
         "\u0f99"-"\u0fbc",
         "\u0fc6",
         "\u1000"-"\u1021",
         "\u1023"-"\u1027",
         "\u1029"-"\u102a",
         "\u102c"-"\u1032",
         "\u1036"-"\u1039",
         "\u1040"-"\u1049",
         "\u1050"-"\u1059",
         "\u10a0"-"\u10c5",
         "\u10d0"-"\u10f6",
         "\u1100"-"\u1159",
         "\u115f"-"\u11a2",
         "\u11a8"-"\u11f9",
         "\u1200"-"\u1206",
         "\u1208"-"\u1246",
         "\u1248",
         "\u124a"-"\u124d",
         "\u1250"-"\u1256",
         "\u1258",
         "\u125a"-"\u125d",
         "\u1260"-"\u1286",
         "\u1288",
         "\u128a"-"\u128d",
         "\u1290"-"\u12ae",
         "\u12b0",
         "\u12b2"-"\u12b5",
         "\u12b8"-"\u12be",
         "\u12c0",
         "\u12c2"-"\u12c5",
         "\u12c8"-"\u12ce",
         "\u12d0"-"\u12d6",
         "\u12d8"-"\u12ee",
         "\u12f0"-"\u130e",
         "\u1310",
         "\u1312"-"\u1315",
         "\u1318"-"\u131e",
         "\u1320"-"\u1346",
         "\u1348"-"\u135a",
         "\u1369"-"\u1371",
         "\u13a0"-"\u13f4",
         "\u1401"-"\u166c",
         "\u166f"-"\u1676",
         "\u1681"-"\u169a",
         "\u16a0"-"\u16ea",
         "\u1780"-"\u17d3",
         "\u17db",
         "\u17e0"-"\u17e9",
         "\u180b"-"\u180e",
         "\u1810"-"\u1819",
         "\u1820"-"\u1877",
         "\u1880"-"\u18a9",
         "\u1e00"-"\u1e9b",
         "\u1ea0"-"\u1ef9",
         "\u1f00"-"\u1f15",
         "\u1f18"-"\u1f1d",
         "\u1f20"-"\u1f45",
         "\u1f48"-"\u1f4d",
         "\u1f50"-"\u1f57",
         "\u1f59",
         "\u1f5b",
         "\u1f5d",
         "\u1f5f"-"\u1f7d",
         "\u1f80"-"\u1fb4",
         "\u1fb6"-"\u1fbc",
         "\u1fbe",
         "\u1fc2"-"\u1fc4",
         "\u1fc6"-"\u1fcc",
         "\u1fd0"-"\u1fd3",
         "\u1fd6"-"\u1fdb",
         "\u1fe0"-"\u1fec",
         "\u1ff2"-"\u1ff4",
         "\u1ff6"-"\u1ffc",
         "\u200c"-"\u200f",
         "\u202a"-"\u202e",
         "\u203f"-"\u2040",
         "\u206a"-"\u206f",
         "\u207f",
         "\u20a0"-"\u20af",
         "\u20d0"-"\u20dc",
         "\u20e1",
         "\u2102",
         "\u2107",
         "\u210a"-"\u2113",
         "\u2115",
         "\u2119"-"\u211d",
         "\u2124",
         "\u2126",
         "\u2128",
         "\u212a"-"\u212d",
         "\u212f"-"\u2131",
         "\u2133"-"\u2139",
         "\u2160"-"\u2183",
         "\u3005"-"\u3007",
         "\u3021"-"\u302f",
         "\u3031"-"\u3035",
         "\u3038"-"\u303a",
         "\u3041"-"\u3094",
         "\u3099"-"\u309a",
         "\u309d"-"\u309e",
         "\u30a1"-"\u30fe",
         "\u3105"-"\u312c",
         "\u3131"-"\u318e",
         "\u31a0"-"\u31b7",
         "\u3400"-"\u4db5",
         "\u4e00"-"\u9fa5",
         "\ua000"-"\ua48c",
         "\uac00"-"\ud7a3",
         "\uf900"-"\ufa2d",
         "\ufb00"-"\ufb06",
         "\ufb13"-"\ufb17",
         "\ufb1d"-"\ufb28",
         "\ufb2a"-"\ufb36",
         "\ufb38"-"\ufb3c",
         "\ufb3e",
         "\ufb40"-"\ufb41",
         "\ufb43"-"\ufb44",
         "\ufb46"-"\ufbb1",
         "\ufbd3"-"\ufd3d",
         "\ufd50"-"\ufd8f",
         "\ufd92"-"\ufdc7",
         "\ufdf0"-"\ufdfb",
         "\ufe20"-"\ufe23",
         "\ufe33"-"\ufe34",
         "\ufe4d"-"\ufe4f",
         "\ufe69",
         "\ufe70"-"\ufe72",
         "\ufe74",
         "\ufe76"-"\ufefc",
         "\ufeff",
         "\uff04",
         "\uff10"-"\uff19",
         "\uff21"-"\uff3a",
         "\uff3f",
         "\uff41"-"\uff5a",
         "\uff65"-"\uffbe",
         "\uffc2"-"\uffc7",
         "\uffca"-"\uffcf",
         "\uffd2"-"\uffd7",
         "\uffda"-"\uffdc",
         "\uffe0"-"\uffe1",
         "\uffe5"-"\uffe6",
         "\ufff9"-"\ufffb"
      ]
  >
}
String javacc_input(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[javacc_options(inTerminal)] "PARSER_BEGIN" "(" ParserNameS(inTerminal) ")" CompilationUnit(inTerminal) "PARSER_END" "(" ParserNameE(inTerminal) ")" (production(inTerminal))+ <EOF> {return productionEndNonTerminal("javacc_input","-","-");}

 )  }

String ParserNameS(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("ParserNameS","-","-","error",first,token);}

 )  }

String ParserNameE(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("ParserNameE","-","-","error",first,token);}

 )  }

String javacc_options(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"options" "{" (option_binding(inTerminal))+ "}" {return productionEndNonTerminal("javacc_options","-","-");}

 )  }

String option_binding(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=OptionName(true){ replaceName("OptionName",n);} "=" OptionValue(true) ";" {return productionEndTerminal("option_binding","{OptionName}","{OptionName}","error",first,token);}

 )  }

String OptionName(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("OptionName1","-","{TOSTRING}","error",first,token);}
 |
	"LOOKAHEAD"  {return productionEndTerminal("OptionName2","-","{TOSTRING}","error",first,token);}
 |
	"IGNORE_CASE"  {return productionEndTerminal("OptionName3","-","{TOSTRING}","error",first,token);}
 |
	"static"  {return productionEndTerminal("OptionName4","-","{TOSTRING}","error",first,token);}

 )  }

String OptionValue(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<INTEGER_LITERAL> {return productionEndTerminal("OptionValue1","-","-","error",first,token);}
 |
	BooleanLiteral(true) {return productionEndTerminal("OptionValue2","-","-","error",first,token);}
 |
	<STRING_LITERAL> {return productionEndTerminal("OptionValue3","-","-","error",first,token);}

 )  }

String production(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(1) javacode_production(true) {return productionEndTerminal("production1","-","-","error",first,token);}
 |
	[regular_expr_productionPrefix(inTerminal)] regexpr_kind(inTerminal) ["[" "IGNORE_CASE" "]" ] ":" "{" regexpr_spec(inTerminal) ("|" regexpr_spec(inTerminal))* "}" {return productionEndNonTerminal("RegExprProduction","{AUTO}","{AUTO}");}
 |
	LOOKAHEAD(1) token_manager_decls(true) {return productionEndTerminal("production3","-","-","error",first,token);}
 |
	[AccessModifier(inTerminal)] ResultType(inTerminal) n=BNFName(inTerminal){ replaceName("BNFName",n);} n=FormalParameters(inTerminal){ replaceName("FormalParameters",n);} [ThrowsClause(inTerminal)] ":" Block(inTerminal) "{" expansion_choices(inTerminal) "}" {return productionEndNonTerminal("BNFProduction","{BNFName}({FormalParameters})","{BNFName}({FormalParameters})");}

 )  }

String javacode_production(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"JAVACODE" [AccessModifier(true)] ResultType(true) <IDENTIFIER> FormalParameters(true) [ThrowsClause(true)] Block(true) {return productionEndTerminal("javacode_production","-","-","error",first,token);}

 )  }

String ThrowsClause(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"throws" Name(true) ("," Name(true))* {return productionEndTerminal("ThrowsClause","-","-","error",first,token);}

 )  }

String bnf_production(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[AccessModifier(true)] ResultType(true) BNFName(true) FormalParameters(true) [ThrowsClause(true)] ":" Block(true) "{" expansion_choices(true) "}" {return productionEndTerminal("bnf_production","-","-","error",first,token);}

 )  }

String BNFName(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("BNFName","-","-","error",first,token);}

 )  }

String AccessModifier(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"public"  {return productionEndTerminal("AccessModifier","-","-","highestScopeModifier",first,token);}
 |
	"protected"  {return productionEndTerminal("AccessModifier","-","-","highestScopeModifier",first,token);}
 |
	"private"  {return productionEndTerminal("AccessModifier","-","-","highestScopeModifier",first,token);}

 )  }

String regular_expr_production(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[regular_expr_productionPrefix(true)] regexpr_kind(true) ["[" "IGNORE_CASE" "]" ] ":" "{" regexpr_spec(true) ("|" regexpr_spec(true))* "}" {return productionEndTerminal("regular_expr_production","-","-","error",first,token);}

 )  }

String regular_expr_productionPrefix(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "<" "*" ">"  {return productionEndTerminal("regular_expr_productionPrefix1","-","-","error",first,token);}
 |
	"<" <IDENTIFIER> ("," <IDENTIFIER>)* ">" {return productionEndTerminal("regular_expr_productionPrefix2","-","-","error",first,token);}

 )  }

String token_manager_decls(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"TOKEN_MGR_DECLS" ":" ClassOrInterfaceBody(true) {return productionEndTerminal("token_manager_decls","-","-","error",first,token);}

 )  }

String regexpr_kind(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"TOKEN"  {return productionEndTerminal("regexpr_kind1","-","-","error",first,token);}
 |
	"SPECIAL_TOKEN"  {return productionEndTerminal("regexpr_kind2","-","-","error",first,token);}
 |
	"SKIP"  {return productionEndTerminal("regexpr_kind3","-","-","error",first,token);}
 |
	"MORE"  {return productionEndTerminal("regexpr_kind4","-","-","error",first,token);}

 )  }

String regexpr_spec(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=regular_expression(true){ replaceName("regular_expression",n);} [Block(true)] [":" <IDENTIFIER>] {return productionEndTerminal("regexpr_spec","{regular_expression}","{regular_expression}","error",first,token);}

 )  }

String expansion_choices(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	expansion(true) ("|" expansion(true))* {return productionEndTerminal("expansion_choices","-","-","composeExpansions",first,token);}

 )  }

String expansion(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[LOOKAHEAD(1) "LOOKAHEAD" "(" local_lookahead(true) ")"] (LOOKAHEAD(0, { notTailOfExpansionUnit() } ) expansion_unit(true))+ {return productionEndTerminal("expansion","-","-","error",first,token);}

 )  }

String local_lookahead(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[LOOKAHEAD(1) <INTEGER_LITERAL>] [LOOKAHEAD(1) "," ] [LOOKAHEAD(0, { getToken(1).kind != RPAREN && getToken(1).kind != LBRACE } ) expansion_choices(true)] [LOOKAHEAD(1) "," ] ["{" Expression(true) "}"] {return productionEndTerminal("local_lookahead","-","-","error",first,token);}

 )  }

String expansion_unit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(1) "LOOKAHEAD" "(" local_lookahead(true) ")" {return productionEndTerminal("expansion_unit1","-","-","error",first,token);}
 |
	Block(true) {return productionEndTerminal("expansion_unit2","-","-","error",first,token);}
 |
	"[" expansion_choices(true) "]" {return productionEndTerminal("expansion_unit3","-","-","error",first,token);}
 |
	"try" "{" expansion_choices(true) "}" (CatchPart(true))* ["finally" Block(true)] {return productionEndTerminal("expansion_unit4","-","-","error",first,token);}
 |
	LOOKAHEAD(<IDENTIFIER> | <STRING_LITERAL> | "<" | PrimaryExpression() "=") [LOOKAHEAD(PrimaryExpression() "=") PrimaryExpression(true) "="] expansion_unitMain(true) {return productionEndTerminal("expansion_unit5","-","-","error",first,token);}
 |
	"(" expansion_choices(true) ")" [ExpModifier(true)] {return productionEndTerminal("expansion_unit6","-","-","error",first,token);}

 )  }

String CatchPart(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"catch" "(" Name(true) <IDENTIFIER> ")" Block(true) {return productionEndTerminal("CatchPart","-","-","error",first,token);}

 )  }

String expansion_unitMain(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD( <IDENTIFIER> "(") <IDENTIFIER> Arguments(true) {return productionEndTerminal("expansion_unitMain1","-","-","error",first,token);}
 |
	regular_expression(true) ["." <IDENTIFIER>] {return productionEndTerminal("expansion_unitMain2","-","-","error",first,token);}

 )  }

String ExpModifier(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"+"  {return productionEndTerminal("ExpModifier1","-","-","error",first,token);}
 |
	"*"  {return productionEndTerminal("ExpModifier2","-","-","error",first,token);}
 |
	"?"  {return productionEndTerminal("ExpModifier3","-","-","error",first,token);}

 )  }

String regular_expression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	t=<STRING_LITERAL>{ replaceName("<STRING_LITERAL>",t.toString());} {return productionEndTerminal("regular_expression1","-","{<STRING_LITERAL>}","error",first,token);}
 |
	LOOKAHEAD(3) "<" [n=RegId(true){ replaceName("RegId",n);}] complex_regular_expression_choices(true) ">" {return productionEndTerminal("regular_expression2","-","{RegId}","error",first,token);}
 |
	LOOKAHEAD(2) "<" t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} ">" {return productionEndTerminal("regular_expression3","-","{<IDENTIFIER>}","error",first,token);}
 |
	"<" "EOF" ">"  {return productionEndTerminal("EOFExpr","-","<EOF>","error",first,token);}

 )  }

String RegId(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["#" ] t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} ":" {return productionEndTerminal("RegId","-","{<IDENTIFIER>}","error",first,token);}

 )  }

String complex_regular_expression_choices(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	complex_regular_expression(true) ("|" complex_regular_expression(true))* {return productionEndTerminal("complex_regular_expression_choices","-","-","error",first,token);}

 )  }

String complex_regular_expression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(complex_regular_expression_unit(true))+ {return productionEndTerminal("complex_regular_expression","-","-","error",first,token);}

 )  }

String complex_regular_expression_unit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<STRING_LITERAL> {return productionEndTerminal("complex_regular_expression_unit1","-","-","error",first,token);}
 |
	"<" <IDENTIFIER> ">" {return productionEndTerminal("complex_regular_expression_unit2","-","-","error",first,token);}
 |
	character_list(true) {return productionEndTerminal("complex_regular_expression_unit3","-","-","error",first,token);}
 |
	"(" complex_regular_expression_choices(true) ")" [CREUPostfix(true)] {return productionEndTerminal("complex_regular_expression_unit4","-","-","error",first,token);}

 )  }

String CREUPostfix(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"+"  {return productionEndTerminal("CREUPostfix1","-","-","error",first,token);}
 |
	"*"  {return productionEndTerminal("CREUPostfix2","-","-","error",first,token);}
 |
	"?"  {return productionEndTerminal("CREUPostfix3","-","-","error",first,token);}
 |
	"{" <INTEGER_LITERAL> [CREUPostfixPP(true)] "}" {return productionEndTerminal("CREUPostfix4","-","-","error",first,token);}

 )  }

String CREUPostfixPP(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"," [<INTEGER_LITERAL>] {return productionEndTerminal("CREUPostfixPP","-","-","error",first,token);}

 )  }

String character_list(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["~" ] "[" [character_descriptorList(true)] "]" {return productionEndTerminal("character_list","-","-","error",first,token);}

 )  }

String character_descriptorList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	character_descriptor(true) ("," character_descriptor(true))* {return productionEndTerminal("character_descriptorList","-","-","error",first,token);}

 )  }

String character_descriptor(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<STRING_LITERAL> ["-" <STRING_LITERAL>] {return productionEndTerminal("character_descriptor","-","-","error",first,token);}

 )  }

String CompilationUnit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[PackageDeclaration(true)] (ImportDeclaration(true))* (TypeDeclaration(true))* {return productionEndTerminal("CompilationUnit","-","-","error",first,token);}

 )  }

String PackageDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"package" Name(true) ";" {return productionEndTerminal("PackageDeclaration","-","-","error",first,token);}

 )  }

String ImportDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"import" ["static" ] Name(true) [ "." "*"] ";" {return productionEndTerminal("ImportDeclaration","-","-","error",first,token);}

 )  }

String Modifiers(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(LOOKAHEAD(1) Modifier(true))* {return productionEndTerminal("Modifiers","-","-","error",first,token);}

 )  }

String Modifier(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"public"  {return productionEndTerminal("Modifier1","-","-","error",first,token);}
 |
	"static"  {return productionEndTerminal("Modifier2","-","-","error",first,token);}
 |
	"protected"  {return productionEndTerminal("Modifier3","-","-","error",first,token);}
 |
	"private"  {return productionEndTerminal("Modifier4","-","-","error",first,token);}
 |
	"final"  {return productionEndTerminal("Modifier5","-","-","error",first,token);}
 |
	"abstract"  {return productionEndTerminal("Modifier6","-","-","error",first,token);}
 |
	"synchronized"  {return productionEndTerminal("Modifier7","-","-","error",first,token);}
 |
	"native"  {return productionEndTerminal("Modifier8","-","-","error",first,token);}
 |
	"transient"  {return productionEndTerminal("Modifier9","-","-","error",first,token);}
 |
	"volatile"  {return productionEndTerminal("Modifier10","-","-","error",first,token);}
 |
	"strictfp"  {return productionEndTerminal("Modifier11","-","-","error",first,token);}
 |
	Annotation(true) {return productionEndTerminal("Modifier12","-","-","error",first,token);}

 )  }

String TypeDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	";"  {return productionEndTerminal("TypeDeclaration1","-","-","error",first,token);}
 |
	LOOKAHEAD(2) Modifiers(true) ClassOrInterfaceDeclaration(true) {return productionEndTerminal("TypeDeclaration2","-","-","error",first,token);}
 |
	LOOKAHEAD(2) Modifiers(true) EnumDeclaration(true) {return productionEndTerminal("TypeDeclaration3","-","-","error",first,token);}
 |
	LOOKAHEAD(2) Modifiers(true) AnnotationTypeDeclaration(true) {return productionEndTerminal("TypeDeclaration4","-","-","error",first,token);}

 )  }

String ClassOrInterfaceDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ClassOrInterface(true) JavaIdentifier(true) [TypeParameters(true)] [ExtendsList(true)] [ImplementsList(true)] ClassOrInterfaceBody(true) {return productionEndTerminal("ClassOrInterfaceDeclaration","-","-","error",first,token);}

 )  }

String ClassOrInterface(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"class"  {return productionEndTerminal("ClassOrInterface1","-","-","error",first,token);}
 |
	"interface"  {return productionEndTerminal("ClassOrInterface2","-","-","error",first,token);}

 )  }

String ExtendsList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extends" ClassOrInterfaceType(true) ("," ClassOrInterfaceType(true))* {return productionEndTerminal("ExtendsList","-","-","error",first,token);}

 )  }

String ImplementsList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"implements" ClassOrInterfaceType(true) ("," ClassOrInterfaceType(true))* {return productionEndTerminal("ImplementsList","-","-","error",first,token);}

 )  }

String EnumDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"enum" JavaIdentifier(true) [ImplementsList(true)] EnumBody(true) {return productionEndTerminal("EnumDeclaration","-","-","error",first,token);}

 )  }

String EnumBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" EnumConstant(true) ("," EnumConstant(true))* [EnumBodyInternal(true)] "}" {return productionEndTerminal("EnumBody","-","-","error",first,token);}

 )  }

String EnumBodyInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	";" (ClassOrInterfaceBodyDeclaration(true))* {return productionEndTerminal("EnumBodyInternal","-","-","error",first,token);}

 )  }

String EnumConstant(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) [Arguments(true)] [ClassOrInterfaceBody(true)] {return productionEndTerminal("EnumConstant","-","-","error",first,token);}

 )  }

String TypeParameters(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<" TypeParameter(true) ("," TypeParameter(true))* ">" {return productionEndTerminal("TypeParameters","-","-","error",first,token);}

 )  }

String TypeParameter(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) [TypeBound(true)] {return productionEndTerminal("TypeParameter","-","-","error",first,token);}

 )  }

String TypeBound(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extends" ClassOrInterfaceType(true) ("&" ClassOrInterfaceType(true))* {return productionEndTerminal("TypeBound","-","-","error",first,token);}

 )  }

String ClassOrInterfaceBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" (ClassOrInterfaceBodyDeclaration(true))* "}" {return productionEndTerminal("ClassOrInterfaceBody","-","-","error",first,token);}

 )  }

String ClassOrInterfaceBodyDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) Initializer(true) {return productionEndTerminal("ClassOrInterfaceBodyDeclaration1","-","-","error",first,token);}
 |
	LOOKAHEAD(Modifiers() ClassOrInterface()) Modifiers(true) ClassOrInterfaceDeclaration(true) {return productionEndTerminal("ClassOrInterfaceBodyDeclaration2","-","-","error",first,token);}
 |
	LOOKAHEAD(Modifiers() "enum") Modifiers(true) EnumDeclaration(true) {return productionEndTerminal("ClassOrInterfaceBodyDeclaration3","-","-","error",first,token);}
 |
	LOOKAHEAD( Modifiers() [ TypeParameters() ] JavaIdentifier() "(") Modifiers(true) ConstructorDeclaration(true) {return productionEndTerminal("ClassOrInterfaceBodyDeclaration4","-","-","error",first,token);}
 |
	LOOKAHEAD(Modifiers() Type() JavaIdentifier() ( "[" "]" )* ( "," | "=" | ";" ) ) Modifiers(true) FieldDeclaration(true) {return productionEndTerminal("ClassOrInterfaceBodyDeclaration5","-","-","error",first,token);}
 |
	LOOKAHEAD(2) Modifiers(true) MethodDeclaration(true) {return productionEndTerminal("ClassOrInterfaceBodyDeclaration6","-","-","error",first,token);}
 |
	";"  {return productionEndTerminal("ClassOrInterfaceBodyDeclaration7","-","-","error",first,token);}

 )  }

String FieldDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Type(true) VariableDeclarator(true) ("," VariableDeclarator(true))* ";" {return productionEndTerminal("FieldDeclaration","-","-","error",first,token);}

 )  }

String VariableDeclarator(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	VariableDeclaratorId(true) ["=" VariableInitializer(true)] {return productionEndTerminal("VariableDeclarator","-","-","error",first,token);}

 )  }

String VariableDeclaratorId(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) ("[" "]" )* {return productionEndTerminal("VariableDeclaratorId","-","-","error",first,token);}

 )  }

String VariableInitializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ArrayInitializer(true) {return productionEndTerminal("VariableInitializer1","-","-","error",first,token);}
 |
	Expression(true) {return productionEndTerminal("VariableInitializer2","-","-","error",first,token);}

 )  }

String ArrayInitializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" [ArrayInitializerInternal(true)] ["," ] "}" {return productionEndTerminal("ArrayInitializer","-","-","error",first,token);}

 )  }

String ArrayInitializerInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	VariableInitializer(true) (LOOKAHEAD(2) "," VariableInitializer(true))* {return productionEndTerminal("ArrayInitializerInternal","-","-","error",first,token);}

 )  }

String MethodDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[TypeParameters(true)] ResultType(true) MethodDeclarator(true) ["throws" NameList(true)] MethodDeclarationBody(true) {return productionEndTerminal("MethodDeclaration","-","-","error",first,token);}

 )  }

String MethodDeclarationBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Block(true) {return productionEndTerminal("MethodDeclarationBody1","-","-","error",first,token);}
 |
	";"  {return productionEndTerminal("MethodDeclarationBody2","-","-","error",first,token);}

 )  }

String MethodDeclarator(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) FormalParameters(true) ("[" "]" )* {return productionEndTerminal("MethodDeclarator","-","-","error",first,token);}

 )  }

String FormalParameters(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"(" [n=FormalParametersInternal(true){ replaceName("FormalParametersInternal",n);}] ")" {return productionEndTerminal("FormalParameters","{FormalParametersInternal}","{FormalParametersInternal}","assumeEqual",first,token);}

 )  }

String FormalParametersInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=FormalParameter(true){ replaceName("FormalParameter",n);} ("," n=FormalParameter(true){ replaceName("FormalParameter",n);})* {return productionEndTerminal("FormalParametersInternal","-","{FormalParameter}^-","error",first,token);}

 )  }

String FormalParameter(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["final" ] n=Type(true){ replaceName("Type",n);} ["..." ] VariableDeclaratorId(true) {return productionEndTerminal("FormalParameter","-","{Type}","error",first,token);}

 )  }

String ConstructorDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[TypeParameters(true)] JavaIdentifier(true) FormalParameters(true) ["throws" NameList(true)] "{" [LOOKAHEAD(ExplicitConstructorInvocation()) ExplicitConstructorInvocation(true)] (BlockStatement(true))* "}" {return productionEndTerminal("ConstructorDeclaration","-","-","error",first,token);}

 )  }

String ExplicitConstructorInvocation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD("this" Arguments() ";") "this" Arguments(true) ";" {return productionEndTerminal("ExplicitConstructorInvocation1","-","-","error",first,token);}
 |
	[LOOKAHEAD(2) PrimaryExpression(true) "."] "super" Arguments(true) ";" {return productionEndTerminal("ExplicitConstructorInvocation2","-","-","error",first,token);}

 )  }

String Initializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["static" ] Block(true) {return productionEndTerminal("Initializer","-","-","error",first,token);}

 )  }

String Type(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) ReferenceTypeP(true) {return productionEndTerminal("Type1","-","{TOSTRING}","error",first,token);}
 |
	PrimitiveType(true) {return productionEndTerminal("Type2","-","{TOSTRING}","error",first,token);}

 )  }

String ReferenceTypeP(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PrimitiveType(true) (LOOKAHEAD(2) "[" "]" )+ {return productionEndTerminal("ReferenceTypeP1","-","-","error",first,token);}
 |
	ClassOrInterfaceType(true) (LOOKAHEAD(2) "[" "]" )* {return productionEndTerminal("ReferenceTypeP2","-","-","error",first,token);}

 )  }

String ClassOrInterfaceType(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) [LOOKAHEAD(2) TypeArguments(true)] (LOOKAHEAD(2) ClassOrInterfaceTypeIntern(true))* {return productionEndTerminal("ClassOrInterfaceType","-","-","error",first,token);}

 )  }

String ClassOrInterfaceTypeIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"." JavaIdentifier(true) [LOOKAHEAD(2) TypeArguments(true)] {return productionEndTerminal("ClassOrInterfaceTypeIntern","-","-","error",first,token);}

 )  }

String TypeArguments(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<" TypeArgument(true) ("," TypeArgument(true))* ">" {return productionEndTerminal("TypeArguments","-","-","error",first,token);}

 )  }

String TypeArgument(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ReferenceTypeP(true) {return productionEndTerminal("TypeArgument1","-","-","error",first,token);}
 |
	"?" [WildcardBounds(true)] {return productionEndTerminal("TypeArgument2","-","-","error",first,token);}

 )  }

String WildcardBounds(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extends" ReferenceTypeP(true) {return productionEndTerminal("WildcardBounds1","-","-","error",first,token);}
 |
	"super" ReferenceTypeP(true) {return productionEndTerminal("WildcardBounds2","-","-","error",first,token);}

 )  }

String PrimitiveType(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"boolean"  {return productionEndTerminal("PrimitiveType1","-","-","error",first,token);}
 |
	"char"  {return productionEndTerminal("PrimitiveType2","-","-","error",first,token);}
 |
	"byte"  {return productionEndTerminal("PrimitiveType3","-","-","error",first,token);}
 |
	"short"  {return productionEndTerminal("PrimitiveType4","-","-","error",first,token);}
 |
	"int"  {return productionEndTerminal("PrimitiveType5","-","-","error",first,token);}
 |
	"long"  {return productionEndTerminal("PrimitiveType6","-","-","error",first,token);}
 |
	"float"  {return productionEndTerminal("PrimitiveType7","-","-","error",first,token);}
 |
	"double"  {return productionEndTerminal("PrimitiveType8","-","-","error",first,token);}

 )  }

String ResultType(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"void"  {return productionEndTerminal("ResultType","-","-","assumeEqual",first,token);}
 |
	Type(true) {return productionEndTerminal("ResultType","-","-","assumeEqual",first,token);}

 )  }

String Name(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) (LOOKAHEAD(2) "." JavaIdentifier(true))* {return productionEndTerminal("Name","-","-","error",first,token);}

 )  }

String NameList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Name(true) ("," Name(true))* {return productionEndTerminal("NameList","-","-","error",first,token);}

 )  }

String Expression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ConditionalExpression(true) [LOOKAHEAD(2) AssignExp(true)] {return productionEndTerminal("Expression","-","-","error",first,token);}

 )  }

String AssignExp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AssignmentOperator(true) Expression(true) {return productionEndTerminal("AssignExp","-","-","error",first,token);}

 )  }

String AssignmentOperator(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"="  {return productionEndTerminal("AssignmentOperator1","-","-","error",first,token);}
 |
	"*="  {return productionEndTerminal("AssignmentOperator2","-","-","error",first,token);}
 |
	"/="  {return productionEndTerminal("AssignmentOperator3","-","-","error",first,token);}
 |
	"%="  {return productionEndTerminal("AssignmentOperator4","-","-","error",first,token);}
 |
	"+="  {return productionEndTerminal("AssignmentOperator5","-","-","error",first,token);}
 |
	"-="  {return productionEndTerminal("AssignmentOperator6","-","-","error",first,token);}
 |
	"<<="  {return productionEndTerminal("AssignmentOperator7","-","-","error",first,token);}
 |
	">>="  {return productionEndTerminal("AssignmentOperator8","-","-","error",first,token);}
 |
	">>>="  {return productionEndTerminal("AssignmentOperator9","-","-","error",first,token);}
 |
	"&="  {return productionEndTerminal("AssignmentOperator10","-","-","error",first,token);}
 |
	"^="  {return productionEndTerminal("AssignmentOperator11","-","-","error",first,token);}
 |
	"|="  {return productionEndTerminal("AssignmentOperator12","-","-","error",first,token);}

 )  }

String ConditionalExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(ConditionalOrExpression() "?") ConditionalExpressionFull(true) {return productionEndTerminal("ConditionalExpression1","-","-","error",first,token);}
 |
	ConditionalOrExpression(true) {return productionEndTerminal("ConditionalExpression2","-","-","error",first,token);}

 )  }

String ConditionalExpressionFull(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ConditionalOrExpression(true) "?" Expression(true) ":" Expression(true) {return productionEndTerminal("ConditionalExpressionFull","-","-","error",first,token);}

 )  }

String ConditionalOrExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ConditionalAndExpression(true) ("||" ConditionalAndExpression(true))* {return productionEndTerminal("ConditionalOrExpression","-","-","error",first,token);}

 )  }

String ConditionalAndExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	InclusiveOrExpression(true) ("&&" InclusiveOrExpression(true))* {return productionEndTerminal("ConditionalAndExpression","-","-","error",first,token);}

 )  }

String InclusiveOrExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ExclusiveOrExpression(true) ("|" ExclusiveOrExpression(true))* {return productionEndTerminal("InclusiveOrExpression","-","-","error",first,token);}

 )  }

String ExclusiveOrExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AndExpression(true) ("^" AndExpression(true))* {return productionEndTerminal("ExclusiveOrExpression","-","-","error",first,token);}

 )  }

String AndExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	EqualityExpression(true) ("&" EqualityExpression(true))* {return productionEndTerminal("AndExpression","-","-","error",first,token);}

 )  }

String EqualityExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	InstanceOfExpression(true) (EqualityExpressionIntern(true))* {return productionEndTerminal("EqualityExpression","-","-","error",first,token);}

 )  }

String EqualityExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	EqualityOp(true) InstanceOfExpression(true) {return productionEndTerminal("EqualityExpressionIntern","-","-","error",first,token);}

 )  }

String EqualityOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"=="  {return productionEndTerminal("EqualityOp1","-","-","error",first,token);}
 |
	"!="  {return productionEndTerminal("EqualityOp2","-","-","error",first,token);}

 )  }

String InstanceOfExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	RelationalExpression(true) ["instanceof" Type(true)] {return productionEndTerminal("InstanceOfExpression","-","-","error",first,token);}

 )  }

String RelationalExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ShiftExpression(true) (RelationalExpressionIntern(true))* {return productionEndTerminal("RelationalExpression","-","-","error",first,token);}

 )  }

String RelationalExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	RelationalOp(true) ShiftExpression(true) {return productionEndTerminal("RelationalExpressionIntern","-","-","error",first,token);}

 )  }

String RelationalOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<"  {return productionEndTerminal("RelationalOp1","-","-","error",first,token);}
 |
	">"  {return productionEndTerminal("RelationalOp2","-","-","error",first,token);}
 |
	"<="  {return productionEndTerminal("RelationalOp3","-","-","error",first,token);}
 |
	">="  {return productionEndTerminal("RelationalOp4","-","-","error",first,token);}

 )  }

String ShiftExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AdditiveExpression(true) (LOOKAHEAD(2) ShiftExpressionRight(true))* {return productionEndTerminal("ShiftExpression","-","-","error",first,token);}

 )  }

String ShiftExpressionRight(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ShiftOp(true) AdditiveExpression(true) {return productionEndTerminal("ShiftExpressionRight","-","-","error",first,token);}

 )  }

String ShiftOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<<"  {return productionEndTerminal("ShiftOp1","-","-","error",first,token);}
 |
	LOOKAHEAD(3) ">" ">" ">"  {return productionEndTerminal("ShiftOp2","-","-","error",first,token);}
 |
	LOOKAHEAD(2) ">" ">"  {return productionEndTerminal("ShiftOp3","-","-","error",first,token);}

 )  }

String AdditiveExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	MultiplicativeExpression(true) (AdditiveExpressionIntern(true))* {return productionEndTerminal("AdditiveExpression","-","-","error",first,token);}

 )  }

String AdditiveExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AdditiveOp(true) MultiplicativeExpression(true) {return productionEndTerminal("AdditiveExpressionIntern","-","-","error",first,token);}

 )  }

String AdditiveOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"+"  {return productionEndTerminal("AdditiveOp1","-","-","error",first,token);}
 |
	"-"  {return productionEndTerminal("AdditiveOp2","-","-","error",first,token);}

 )  }

String MultiplicativeExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	UnaryExpression(true) (MultiplicativeExpressionIntern(true))* {return productionEndTerminal("MultiplicativeExpression","-","-","error",first,token);}

 )  }

String MultiplicativeExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	MultiplicativeOp(true) UnaryExpression(true) {return productionEndTerminal("MultiplicativeExpressionIntern","-","-","error",first,token);}

 )  }

String MultiplicativeOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*"  {return productionEndTerminal("MultiplicativeOp1","-","-","error",first,token);}
 |
	"/"  {return productionEndTerminal("MultiplicativeOp2","-","-","error",first,token);}
 |
	"%"  {return productionEndTerminal("MultiplicativeOp3","-","-","error",first,token);}

 )  }

String UnaryExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AdditiveOp(true) UnaryExpression(true) {return productionEndTerminal("UnaryExpression1","-","-","error",first,token);}
 |
	PreIncrementExpression(true) {return productionEndTerminal("UnaryExpression2","-","-","error",first,token);}
 |
	PreDecrementExpression(true) {return productionEndTerminal("UnaryExpression3","-","-","error",first,token);}
 |
	UnaryExpressionNotPlusMinus(true) {return productionEndTerminal("UnaryExpression4","-","-","error",first,token);}

 )  }

String PreIncrementExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"++" PrimaryExpression(true) {return productionEndTerminal("PreIncrementExpression","-","-","error",first,token);}

 )  }

String PreDecrementExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"--" PrimaryExpression(true) {return productionEndTerminal("PreDecrementExpression","-","-","error",first,token);}

 )  }

String UnaryExpressionNotPlusMinus(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	UnaryOp(true) UnaryExpression(true) {return productionEndTerminal("UnaryExpressionNotPlusMinus1","-","-","error",first,token);}
 |
	LOOKAHEAD(CastLookahead()) CastExpression(true) {return productionEndTerminal("UnaryExpressionNotPlusMinus2","-","-","error",first,token);}
 |
	PostfixExpression(true) {return productionEndTerminal("UnaryExpressionNotPlusMinus3","-","-","error",first,token);}

 )  }

String UnaryOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"~"  {return productionEndTerminal("UnaryOp1","-","-","error",first,token);}
 |
	"!"  {return productionEndTerminal("UnaryOp2","-","-","error",first,token);}

 )  }

String CastLookahead(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "(" PrimitiveType(true) {return productionEndTerminal("CastLookahead1","-","-","error",first,token);}
 |
	LOOKAHEAD("(" Type() "[") "(" Type(true) "[" "]" {return productionEndTerminal("CastLookahead2","-","-","error",first,token);}
 |
	"(" Type(true) ")" CastLAOp(true) {return productionEndTerminal("CastLookahead3","-","-","error",first,token);}

 )  }

String CastLAOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"~"  {return productionEndTerminal("CastLAOp1","-","-","error",first,token);}
 |
	"!"  {return productionEndTerminal("CastLAOp2","-","-","error",first,token);}
 |
	"("  {return productionEndTerminal("CastLAOp3","-","-","error",first,token);}
 |
	"this"  {return productionEndTerminal("CastLAOp4","-","-","error",first,token);}
 |
	"super"  {return productionEndTerminal("CastLAOp5","-","-","error",first,token);}
 |
	"new"  {return productionEndTerminal("CastLAOp6","-","-","error",first,token);}
 |
	JavaIdentifier(true) {return productionEndTerminal("CastLAOp7","-","-","error",first,token);}
 |
	Literal(true) {return productionEndTerminal("CastLAOp8","-","-","error",first,token);}

 )  }

String PostfixExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PrimaryExpression(true) [PostfixOp(true)] {return productionEndTerminal("PostfixExpression","-","-","error",first,token);}

 )  }

String PostfixOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"++"  {return productionEndTerminal("PostfixOp1","-","-","error",first,token);}
 |
	"--"  {return productionEndTerminal("PostfixOp2","-","-","error",first,token);}

 )  }

String CastExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD("(" PrimitiveType()) "(" Type(true) ")" UnaryExpression(true) {return productionEndTerminal("CastExpression1","-","-","error",first,token);}
 |
	"(" Type(true) ")" UnaryExpressionNotPlusMinus(true) {return productionEndTerminal("CastExpression2","-","-","error",first,token);}

 )  }

String PrimaryExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PrimaryPrefix(true) (LOOKAHEAD(2) PrimarySuffix(true))* {return productionEndTerminal("PrimaryExpression","-","-","error",first,token);}

 )  }

String MemberSelector(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"." TypeArguments(true) JavaIdentifier(true) {return productionEndTerminal("MemberSelector","-","-","error",first,token);}

 )  }

String PrimaryPrefix(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Literal(true) {return productionEndTerminal("PrimaryPrefix1","-","-","error",first,token);}
 |
	"this"  {return productionEndTerminal("PrimaryPrefix2","-","-","error",first,token);}
 |
	"super" "." JavaIdentifier(true) {return productionEndTerminal("PrimaryPrefix3","-","-","error",first,token);}
 |
	"(" Expression(true) ")" {return productionEndTerminal("PrimaryPrefix4","-","-","error",first,token);}
 |
	AllocationExpression(true) {return productionEndTerminal("PrimaryPrefix5","-","-","error",first,token);}
 |
	LOOKAHEAD( ResultType() "." "class") ResultType(true) "." "class" {return productionEndTerminal("PrimaryPrefix6","-","-","error",first,token);}
 |
	Name(true) {return productionEndTerminal("PrimaryPrefix7","-","-","error",first,token);}

 )  }

String PrimarySuffix(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "." "this"  {return productionEndTerminal("PrimarySuffix1","-","-","error",first,token);}
 |
	LOOKAHEAD(2) "." AllocationExpression(true) {return productionEndTerminal("PrimarySuffix2","-","-","error",first,token);}
 |
	LOOKAHEAD(3) MemberSelector(true) {return productionEndTerminal("PrimarySuffix3","-","-","error",first,token);}
 |
	"[" Expression(true) "]" {return productionEndTerminal("PrimarySuffix4","-","-","error",first,token);}
 |
	"." JavaIdentifier(true) {return productionEndTerminal("PrimarySuffix5","-","-","error",first,token);}
 |
	Arguments(true) {return productionEndTerminal("PrimarySuffix6","-","-","error",first,token);}

 )  }

String Literal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<INTEGER_LITERAL> {return productionEndTerminal("Literal1","-","-","error",first,token);}
 |
	<FLOATING_POINT_LITERAL> {return productionEndTerminal("Literal2","-","-","error",first,token);}
 |
	<CHARACTER_LITERAL> {return productionEndTerminal("Literal3","-","-","error",first,token);}
 |
	<STRING_LITERAL> {return productionEndTerminal("Literal4","-","-","error",first,token);}
 |
	BooleanLiteral(true) {return productionEndTerminal("Literal5","-","-","error",first,token);}
 |
	NullLiteral(true) {return productionEndTerminal("Literal6","-","-","error",first,token);}

 )  }

String BooleanLiteral(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"true"  {return productionEndTerminal("BooleanLiteral1","-","-","error",first,token);}
 |
	"false"  {return productionEndTerminal("BooleanLiteral2","-","-","error",first,token);}

 )  }

String NullLiteral(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"null"  {return productionEndTerminal("NullLiteral","-","-","error",first,token);}

 )  }

String Arguments(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"(" [ArgumentList(true)] ")" {return productionEndTerminal("Arguments","-","-","error",first,token);}

 )  }

String ArgumentList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Expression(true) ("," Expression(true))* {return productionEndTerminal("ArgumentList","-","-","error",first,token);}

 )  }

String AllocationExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "new" PrimitiveType(true) ArrayDimsAndInits(true) {return productionEndTerminal("AllocationExpression1","-","-","error",first,token);}
 |
	"new" ClassOrInterfaceType(true) [TypeArguments(true)] AllocationExpressionInit(true) {return productionEndTerminal("AllocationExpression2","-","-","error",first,token);}

 )  }

String AllocationExpressionInit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ArrayDimsAndInits(true) {return productionEndTerminal("AllocationExpressionInit1","-","-","error",first,token);}
 |
	Arguments(true) [ClassOrInterfaceBody(true)] {return productionEndTerminal("AllocationExpressionInit2","-","-","error",first,token);}

 )  }

String ArrayDimsAndInits(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "[" Expression(true) "]" (LOOKAHEAD(2) "[" Expression(true) "]")* (LOOKAHEAD(2) "[" "]" )* {return productionEndTerminal("ArrayDimsAndInits1","-","-","error",first,token);}
 |
	("[" "]" )+ ArrayInitializer(true) {return productionEndTerminal("ArrayDimsAndInits2","-","-","error",first,token);}

 )  }

String Statement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) LabeledStatement(true) {return productionEndTerminal("Statement1","-","-","error",first,token);}
 |
	AssertStatement(true) {return productionEndTerminal("Statement2","-","-","error",first,token);}
 |
	Block(true) {return productionEndTerminal("Statement3","-","-","error",first,token);}
 |
	EmptyStatement(true) {return productionEndTerminal("Statement4","-","-","error",first,token);}
 |
	StatementExpression(true) ";" {return productionEndTerminal("Statement5","-","-","error",first,token);}
 |
	SwitchStatement(true) {return productionEndTerminal("Statement6","-","-","error",first,token);}
 |
	IfStatement(true) {return productionEndTerminal("Statement7","-","-","error",first,token);}
 |
	WhileStatement(true) {return productionEndTerminal("Statement8","-","-","error",first,token);}
 |
	DoStatement(true) {return productionEndTerminal("Statement9","-","-","error",first,token);}
 |
	ForStatement(true) {return productionEndTerminal("Statement10","-","-","error",first,token);}
 |
	BreakStatement(true) {return productionEndTerminal("Statement11","-","-","error",first,token);}
 |
	ContinueStatement(true) {return productionEndTerminal("Statement12","-","-","error",first,token);}
 |
	ReturnStatement(true) {return productionEndTerminal("Statement13","-","-","error",first,token);}
 |
	ThrowStatement(true) {return productionEndTerminal("Statement14","-","-","error",first,token);}
 |
	SynchronizedStatement(true) {return productionEndTerminal("Statement15","-","-","error",first,token);}
 |
	TryStatement(true) {return productionEndTerminal("Statement16","-","-","error",first,token);}

 )  }

String AssertStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"assert" Expression(true) [":" Expression(true)] ";" {return productionEndTerminal("AssertStatement","-","-","error",first,token);}

 )  }

String LabeledStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) ":" Statement(true) {return productionEndTerminal("LabeledStatement","-","-","error",first,token);}

 )  }

String Block(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" (BlockStatement(true))* "}" {return productionEndTerminal("Block","-","-","composeStatements",first,token);}

 )  }

String BlockStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD([ "final" ] Type() JavaIdentifier()) LocalVariableDeclaration(true) ";" {return productionEndTerminal("BlockStatement1","-","-","error",first,token);}
 |
	Statement(true) {return productionEndTerminal("BlockStatement2","-","-","error",first,token);}
 |
	ClassOrInterfaceDeclaration(true) {return productionEndTerminal("BlockStatement3","-","-","error",first,token);}

 )  }

String LocalVariableDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["final" ] Type(true) VariableDeclarator(true) ("," VariableDeclarator(true))* {return productionEndTerminal("LocalVariableDeclaration","-","-","error",first,token);}

 )  }

String EmptyStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	";"  {return productionEndTerminal("EmptyStatement","-","-","error",first,token);}

 )  }

String StatementExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PreIncrementExpression(true) {return productionEndTerminal("StatementExpression1","-","-","error",first,token);}
 |
	PreDecrementExpression(true) {return productionEndTerminal("StatementExpression2","-","-","error",first,token);}
 |
	PrimaryExpression(true) [StatementExpressionAssignment(true)] {return productionEndTerminal("StatementExpression3","-","-","error",first,token);}

 )  }

String StatementExpressionAssignment(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"++"  {return productionEndTerminal("StatementExpressionAssignment1","-","-","error",first,token);}
 |
	"--"  {return productionEndTerminal("StatementExpressionAssignment2","-","-","error",first,token);}
 |
	AssignmentOperator(true) Expression(true) {return productionEndTerminal("StatementExpressionAssignment3","-","-","error",first,token);}

 )  }

String SwitchStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"switch" "(" Expression(true) ")" "{" (SwitchStatementLabel(true))* "}" {return productionEndTerminal("SwitchStatement","-","-","error",first,token);}

 )  }

String SwitchStatementLabel(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	SwitchLabel(true) (BlockStatement(true))* {return productionEndTerminal("SwitchStatementLabel","-","-","error",first,token);}

 )  }

String SwitchLabel(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"case" Expression(true) ":" {return productionEndTerminal("SwitchLabel1","-","-","error",first,token);}
 |
	"default" ":"  {return productionEndTerminal("SwitchLabel2","-","-","error",first,token);}

 )  }

String IfStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"if" "(" Expression(true) ")" Statement(true) [LOOKAHEAD(1) "else" Statement(true)] {return productionEndTerminal("IfStatement","-","-","error",first,token);}

 )  }

String WhileStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"while" "(" Expression(true) ")" Statement(true) {return productionEndTerminal("WhileStatement","-","-","error",first,token);}

 )  }

String DoStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"do" Statement(true) "while" "(" Expression(true) ")" ";" {return productionEndTerminal("DoStatement","-","-","error",first,token);}

 )  }

String ForStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"for" "(" ForStatementInternal(true) ")" Statement(true) {return productionEndTerminal("ForStatement","-","-","error",first,token);}

 )  }

String ForStatementInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(Type() JavaIdentifier() ":") Type(true) JavaIdentifier(true) ":" Expression(true) {return productionEndTerminal("ForStatementInternal1","-","-","error",first,token);}
 |
	[ForInit(true)] ";" [Expression(true)] ";" [ForUpdate(true)] {return productionEndTerminal("ForStatementInternal2","-","-","error",first,token);}

 )  }

String ForInit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD([ "final" ] Type() JavaIdentifier()) LocalVariableDeclaration(true) {return productionEndTerminal("ForInit1","-","-","error",first,token);}
 |
	StatementExpressionList(true) {return productionEndTerminal("ForInit2","-","-","error",first,token);}

 )  }

String StatementExpressionList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	StatementExpression(true) ("," StatementExpression(true))* {return productionEndTerminal("StatementExpressionList","-","-","error",first,token);}

 )  }

String ForUpdate(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	StatementExpressionList(true) {return productionEndTerminal("ForUpdate","-","-","error",first,token);}

 )  }

String BreakStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"break" [JavaIdentifier(true)] ";" {return productionEndTerminal("BreakStatement","-","-","error",first,token);}

 )  }

String ContinueStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"continue" [JavaIdentifier(true)] ";" {return productionEndTerminal("ContinueStatement","-","-","error",first,token);}

 )  }

String ReturnStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"return" [Expression(true)] ";" {return productionEndTerminal("ReturnStatement","-","-","error",first,token);}

 )  }

String ThrowStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"throw" Expression(true) ";" {return productionEndTerminal("ThrowStatement","-","-","error",first,token);}

 )  }

String SynchronizedStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"synchronized" "(" Expression(true) ")" Block(true) {return productionEndTerminal("SynchronizedStatement","-","-","error",first,token);}

 )  }

String TryStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"try" Block(true) TryStatementEnd(true) {return productionEndTerminal("TryStatement","-","-","error",first,token);}

 )  }

String TryStatementEnd(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(CatchBlock(true))+ {return productionEndTerminal("TryStatementEnd1","-","-","error",first,token);}
 |
	"finally" Block(true) {return productionEndTerminal("FinallyBlock","-","-","error",first,token);}

 )  }

String CatchBlock(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"catch" "(" FormalParameter(true) ")" Block(true) {return productionEndTerminal("CatchBlock","-","-","error",first,token);}

 )  }

String Annotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD("@" Name() "(" ( JavaIdentifier() "=" | ")" )) NormalAnnotation(true) {return productionEndTerminal("Annotation1","-","-","error",first,token);}
 |
	LOOKAHEAD("@" Name() "(") SingleMemberAnnotation(true) {return productionEndTerminal("Annotation2","-","-","error",first,token);}
 |
	MarkerAnnotation(true) {return productionEndTerminal("Annotation3","-","-","error",first,token);}

 )  }

String NormalAnnotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" Name(true) "(" [MemberValuePairs(true)] ")" {return productionEndTerminal("NormalAnnotation","-","-","error",first,token);}

 )  }

String MarkerAnnotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" Name(true) {return productionEndTerminal("MarkerAnnotation","-","-","error",first,token);}

 )  }

String SingleMemberAnnotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" Name(true) "(" MemberValue(true) ")" {return productionEndTerminal("SingleMemberAnnotation","-","-","error",first,token);}

 )  }

String MemberValuePairs(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	MemberValuePair(true) ("," MemberValuePair(true))* {return productionEndTerminal("MemberValuePairs","-","-","error",first,token);}

 )  }

String MemberValuePair(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	JavaIdentifier(true) "=" MemberValue(true) {return productionEndTerminal("MemberValuePair","-","-","error",first,token);}

 )  }

String MemberValue(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Annotation(true) {return productionEndTerminal("MemberValue1","-","-","error",first,token);}
 |
	MemberValueArrayInitializer(true) {return productionEndTerminal("MemberValue2","-","-","error",first,token);}
 |
	ConditionalExpression(true) {return productionEndTerminal("MemberValue3","-","-","error",first,token);}

 )  }

String MemberValueArrayInitializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" MemberValue(true) (LOOKAHEAD(2) "," MemberValue(true))* ["," ] "}" {return productionEndTerminal("MemberValueArrayInitializer","-","-","error",first,token);}

 )  }

String AnnotationTypeDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" "interface" JavaIdentifier(true) AnnotationTypeBody(true) {return productionEndTerminal("AnnotationTypeDeclaration","-","-","error",first,token);}

 )  }

String AnnotationTypeBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" (AnnotationTypeMemberDeclaration(true))* "}" {return productionEndTerminal("AnnotationTypeBody","-","-","error",first,token);}

 )  }

String AnnotationTypeMemberDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(Modifiers() Type() JavaIdentifier() "(") Modifiers(true) Type(true) JavaIdentifier(true) "(" ")" [DefaultValue(true)] ";" {return productionEndTerminal("AnnotationTypeMemberDeclaration1","-","-","error",first,token);}
 |
	LOOKAHEAD(1) Modifiers(true) ClassOrInterfaceDeclaration(true) {return productionEndTerminal("AnnotationTypeMemberDeclaration2","-","-","error",first,token);}
 |
	LOOKAHEAD(2) Modifiers(true) EnumDeclaration(true) {return productionEndTerminal("AnnotationTypeMemberDeclaration3","-","-","error",first,token);}
 |
	LOOKAHEAD(2) Modifiers(true) AnnotationTypeDeclaration(true) {return productionEndTerminal("AnnotationTypeMemberDeclaration4","-","-","error",first,token);}
 |
	LOOKAHEAD(1) Modifiers(true) FieldDeclaration(true) {return productionEndTerminal("AnnotationTypeMemberDeclaration5","-","-","error",first,token);}
 |
	";"  {return productionEndTerminal("AnnotationTypeMemberDeclaration6","-","-","error",first,token);}

 )  }

String DefaultValue(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"default" MemberValue(true) {return productionEndTerminal("DefaultValue","-","-","error",first,token);}

 )  }

String JavaIdentifier(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("JavaIdentifier1","-","-","error",first,token);}
 |
	"options"  {return productionEndTerminal("JavaIdentifier2","-","-","error",first,token);}
 |
	"LOOKAHEAD"  {return productionEndTerminal("JavaIdentifier3","-","-","error",first,token);}
 |
	"IGNORE_CASE"  {return productionEndTerminal("JavaIdentifier4","-","-","error",first,token);}
 |
	"PARSER_BEGIN"  {return productionEndTerminal("JavaIdentifier5","-","-","error",first,token);}
 |
	"PARSER_END"  {return productionEndTerminal("JavaIdentifier6","-","-","error",first,token);}
 |
	"JAVACODE"  {return productionEndTerminal("JavaIdentifier7","-","-","error",first,token);}
 |
	"TOKEN"  {return productionEndTerminal("JavaIdentifier8","-","-","error",first,token);}
 |
	"SPECIAL_TOKEN"  {return productionEndTerminal("JavaIdentifier9","-","-","error",first,token);}
 |
	"MORE"  {return productionEndTerminal("JavaIdentifier10","-","-","error",first,token);}
 |
	"SKIP"  {return productionEndTerminal("JavaIdentifier11","-","-","error",first,token);}
 |
	"TOKEN_MGR_DECLS"  {return productionEndTerminal("JavaIdentifier12","-","-","error",first,token);}
 |
	"EOF"  {return productionEndTerminal("JavaIdentifier13","-","-","error",first,token);}

 )  }

