
/*
 * Copyright © 2002 Sun Microsystems, Inc., 4150 Network Circle, Santa Clara,
 * California 95054, U.S.A. All rights reserved.  Sun Microsystems, Inc. has
 * intellectual property rights relating to technology embodied in the product
 * that is described in this document. In particular, and without limitation,
 * these intellectual property rights may include one or more of the U.S.
 * patents listed at http://www.sun.com/patents and one or more additional
 * patents or pending patent applications in the U.S. and in other countries.
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.  Use is subject to license terms.
 * Sun,  Sun Microsystems,  the Sun logo and  Java are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.  This
 * product is covered and controlled by U.S. Export Control laws and may be
 * subject to the export or import laws in other countries.  Nuclear, missile,
 * chemical biological weapons or nuclear maritime end uses or end users,
 * whether direct or indirect, are strictly prohibited.  Export or reexport
 * to countries subject to U.S. embargo or to entities identified on U.S.
 * export exclusion lists, including, but not limited to, the denied persons
 * and specially designated nationals lists is strictly prohibited.
 */

options {
  JAVA_UNICODE_ESCAPE = true;
  ERROR_REPORTING = true;
  STATIC = false;
}


PARSER_BEGIN(Java15Parser)
package tmp.generated_java15;

import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;
import de.ovgu.cide.fstgen.ast.*;


/**
 * Grammar to parse Java version 1.5
 * @author Sreenivasa Viswanadha - Simplified and enhanced for 1.5
 */
public class Java15Parser extends AbstractFSTParser
{
 	public Java15Parser(){}
}

PARSER_END(Java15Parser)

/* WHITE SPACE */

SPECIAL_TOKEN :
{
  " "
| "\t"
| "\n"
| "\r"
| "\f"
}

/* COMMENTS */

MORE :
{
  "//" : IN_SINGLE_LINE_COMMENT
|
  <"/**" ~["/"]> { input_stream.backup(1); } : IN_FORMAL_COMMENT
|
  "/*" : IN_MULTI_LINE_COMMENT
}

<IN_SINGLE_LINE_COMMENT>
SPECIAL_TOKEN :
{
  <SINGLE_LINE_COMMENT: "\n" | "\r" | "\r\n" > : DEFAULT
}

<IN_FORMAL_COMMENT>
SPECIAL_TOKEN :
{
  <FORMAL_COMMENT: "*/" > : DEFAULT
}

<IN_MULTI_LINE_COMMENT>
SPECIAL_TOKEN :
{
  <MULTI_LINE_COMMENT: "*/" > : DEFAULT
}

<IN_SINGLE_LINE_COMMENT,IN_FORMAL_COMMENT,IN_MULTI_LINE_COMMENT>
MORE :
{
  < ~[] >
}

/* RESERVED WORDS AND LITERALS */

TOKEN :
{
  < ABSTRACT: "abstract" >
| < ASSERT: "assert" >
| < BOOLEAN: "boolean" >
| < BREAK: "break" >
| < BYTE: "byte" >
| < CASE: "case" >
| < CATCH: "catch" >
| < CHAR: "char" >
| < CLASS: "class" >
| < CONST: "const" >
| < CONTINUE: "continue" >
| < _DEFAULT: "default" >
| < DO: "do" >
| < DOUBLE: "double" >
| < ELSE: "else" >
| < ENUM: "enum" >
| < EXTENDS: "extends" >
| < FALSE: "false" >
| < FINAL: "final" >
| < FINALLY: "finally" >
| < FLOAT: "float" >
| < FOR: "for" >
| < GOTO: "goto" >
| < IF: "if" >
| < IMPLEMENTS: "implements" >
| < IMPORT: "import" >
| < INSTANCEOF: "instanceof" >
| < INT: "int" >
| < INTERFACE: "interface" >
| < LONG: "long" >
| < NATIVE: "native" >
| < NEW: "new" >
| < NULL: "null" >
| < PACKAGE: "package">
| < PRIVATE: "private" >
| < PROTECTED: "protected" >
| < PUBLIC: "public" >
| < RETURN: "return" >
| < SHORT: "short" >
| < STATIC: "static" >
| < STRICTFP: "strictfp" >
| < SUPER: "super" >
| < SWITCH: "switch" >
| < SYNCHRONIZED: "synchronized" >
| < THIS: "this" >
| < THROW: "throw" >
| < THROWS: "throws" >
| < TRANSIENT: "transient" >
| < TRUE: "true" >
| < TRY: "try" >
| < VOID: "void" >
| < VOLATILE: "volatile" >
| < WHILE: "while" >
}

/* LITERALS */

TOKEN :
{
  < INTEGER_LITERAL:
        <DECIMAL_LITERAL> (["l","L"])?
      | <HEX_LITERAL> (["l","L"])?
      | <OCTAL_LITERAL> (["l","L"])?
  >
|
  < #DECIMAL_LITERAL: ["1"-"9"] (["0"-"9"])* >
|
  < #HEX_LITERAL: "0" ["x","X"] (["0"-"9","a"-"f","A"-"F"])+ >
|
  < #OCTAL_LITERAL: "0" (["0"-"7"])* >
|
  < FLOATING_POINT_LITERAL:
        (["0"-"9"])+ "." (["0"-"9"])* (<EXPONENT>)? (["f","F","d","D"])?
      | "." (["0"-"9"])+ (<EXPONENT>)? (["f","F","d","D"])?
      | (["0"-"9"])+ <EXPONENT> (["f","F","d","D"])?
      | (["0"-"9"])+ (<EXPONENT>)? ["f","F","d","D"]
  >
|
  < #EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+ >
|
  < CHARACTER_LITERAL:
      "'"
      (   (~["'","\\","\n","\r"])
        | ("\\"
            ( ["n","t","b","r","f","\\","'","\""]
            | ["0"-"7"] ( ["0"-"7"] )?
            | ["0"-"3"] ["0"-"7"] ["0"-"7"]
            )
          )
      )
      "'"
  >
|
  < STRING_LITERAL:
      "\""
      (   (~["\"","\\","\n","\r"])
        | ("\\"
            ( ["n","t","b","r","f","\\","'","\""]
            | ["0"-"7"] ( ["0"-"7"] )?
            | ["0"-"3"] ["0"-"7"] ["0"-"7"]
            )
          )
      )*
      "\""
  >
}

/* IDENTIFIERS */

TOKEN :
{
  < IDENTIFIER: <LETTER> (<LETTER>|<DIGIT>)* >
|
  < #LETTER:
      [
       "\u0024",
       "\u0041"-"\u005a",
       "\u005f",
       "\u0061"-"\u007a",
       "\u00c0"-"\u00d6",
       "\u00d8"-"\u00f6",
       "\u00f8"-"\u00ff",
       "\u0100"-"\u1fff",
       "\u3040"-"\u318f",
       "\u3300"-"\u337f",
       "\u3400"-"\u3d2d",
       "\u4e00"-"\u9fff",
       "\uf900"-"\ufaff"
      ]
  >
|
  < #DIGIT:
      [
       "\u0030"-"\u0039",
       "\u0660"-"\u0669",
       "\u06f0"-"\u06f9",
       "\u0966"-"\u096f",
       "\u09e6"-"\u09ef",
       "\u0a66"-"\u0a6f",
       "\u0ae6"-"\u0aef",
       "\u0b66"-"\u0b6f",
       "\u0be7"-"\u0bef",
       "\u0c66"-"\u0c6f",
       "\u0ce6"-"\u0cef",
       "\u0d66"-"\u0d6f",
       "\u0e50"-"\u0e59",
       "\u0ed0"-"\u0ed9",
       "\u1040"-"\u1049"
      ]
  >
}

/* SEPARATORS */

TOKEN :
{
  < LPAREN: "(" >
| < RPAREN: ")" >
| < LBRACE: "{" >
| < RBRACE: "}" >
| < LBRACKET: "[" >
| < RBRACKET: "]" >
| < SEMICOLON: ";" >
| < COMMA: "," >
| < DOT: "." >
| < AT: "@" >
}

/* OPERATORS */

TOKEN :
{
  < ASSIGN: "=" >
| < LT: "<" >
| < BANG: "!" >
| < TILDE: "~" >
| < HOOK: "?" >
| < COLON: ":" >
| < EQ: "==" >
| < LE: "<=" >
| < GE: ">=" >
| < NE: "!=" >
| < SC_OR: "||" >
| < SC_AND: "&&" >
| < INCR: "++" >
| < DECR: "--" >
| < PLUS: "+" >
| < MINUS: "-" >
| < STAR: "*" >
| < SLASH: "/" >
| < BIT_AND: "&" >
| < BIT_OR: "|" >
| < XOR: "^" >
| < REM: "%" >
| < LSHIFT: "<<" >
| < PLUSASSIGN: "+=" >
| < MINUSASSIGN: "-=" >
| < STARASSIGN: "*=" >
| < SLASHASSIGN: "/=" >
| < ANDASSIGN: "&=" >
| < ORASSIGN: "|=" >
| < XORASSIGN: "^=" >
| < REMASSIGN: "%=" >
| < LSHIFTASSIGN: "<<=" >
| < RSIGNEDSHIFTASSIGN: ">>=" >
| < RUNSIGNEDSHIFTASSIGN: ">>>=" >
| < ELLIPSIS: "..." >
}

/* >'s need special attention due to generics syntax. */
TOKEN :
{
  < RUNSIGNEDSHIFT: ">>>" >
| < RSIGNEDSHIFT: ">>" >
| < GT: ">" >
}
String CompilationUnit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[PackageDeclaration(inTerminal)] (ImportDeclaration(inTerminal))* (n=TypeDeclaration(inTerminal){ replaceName("TypeDeclaration",n);})* <EOF> {return productionEndNonTerminal("CompilationUnit","{TypeDeclaration}","{TypeDeclaration}");}

 )  }

String PackageDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"package" Name(true) ";" {return productionEndTerminal("PackageDeclaration","-","-","error",first,token);}

 )  }

String ImportDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"import" ["static" ] n=Name(true){ replaceName("Name",n);} [n=ImportPackage(true){ replaceName("ImportPackage",n);}] ";" {return productionEndTerminal("ImportDeclaration","{Name}{ImportPackage}","{Name}{ImportPackage}","error",first,token);}

 )  }

String ImportPackage(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	 "." "*" {return productionEndTerminal("ImportPackage","-",".*","error",first,token);}

 )  }

String Modifiers(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(LOOKAHEAD(2) Modifier(true))* {return productionEndTerminal("Modifiers","-","-","error",first,token);}

 )  }

String Modifier(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"public"  {return productionEndTerminal("Modifier1","-","-","error",first,token);}
 |
	"static"  {return productionEndTerminal("Modifier2","-","-","error",first,token);}
 |
	"protected"  {return productionEndTerminal("Modifier3","-","-","error",first,token);}
 |
	"private"  {return productionEndTerminal("Modifier4","-","-","error",first,token);}
 |
	"final"  {return productionEndTerminal("Modifier5","-","-","error",first,token);}
 |
	"abstract"  {return productionEndTerminal("Modifier6","-","-","error",first,token);}
 |
	"synchronized"  {return productionEndTerminal("Modifier7","-","-","error",first,token);}
 |
	"native"  {return productionEndTerminal("Modifier8","-","-","error",first,token);}
 |
	"transient"  {return productionEndTerminal("Modifier9","-","-","error",first,token);}
 |
	"volatile"  {return productionEndTerminal("Modifier10","-","-","error",first,token);}
 |
	"strictfp"  {return productionEndTerminal("Modifier11","-","-","error",first,token);}
 |
	Annotation(true) {return productionEndTerminal("Modifier12","-","-","error",first,token);}

 )  }

String Id(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} {return productionEndTerminal("Id","{<IDENTIFIER>}","{<IDENTIFIER>}","error",first,token);}

 )  }

String TypeDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	";"  {return productionEndTerminal("EmptyTypeDecl","{AUTO}","{AUTO}","error",first,token);}
 |
	LOOKAHEAD(Modifiers() "@" "interface") Modifiers(inTerminal) "@" "interface" n=Id(inTerminal){ replaceName("Id",n);} "{" (AnnotationTypeMemberDeclaration(inTerminal))* "}" {return productionEndNonTerminal("AnnotationTypeDeclaration","{Id}","{Id}");}
 |
	LOOKAHEAD(2) Modifiers(inTerminal) ClassOrInterface(inTerminal) n=Id(inTerminal){ replaceName("Id",n);} [TypeParameters(inTerminal)] [ExtendsList(inTerminal)] [ImplementsList(inTerminal)] "{" (ClassOrInterfaceBodyDeclaration(inTerminal))* "}" {return productionEndNonTerminal("ClassDeclaration","{Id}","{Id}");}
 |
	LOOKAHEAD(2) Modifiers(inTerminal) "enum" n=Id(inTerminal){ replaceName("Id",n);} [ImplementsList(inTerminal)] "{" EnumConstant(inTerminal) ("," EnumConstant(inTerminal))* [EnumBodyInternal(inTerminal)] "}" {return productionEndNonTerminal("EnumDecl","{Id}","{Id}");}

 )  }

String AnnotationTypeDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" "interface" Id(true) AnnotationTypeBody(true) {return productionEndTerminal("AnnotationTypeDeclaration","-","-","error",first,token);}

 )  }

String ClassOrInterfaceDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ClassOrInterface(true) Id(true) [TypeParameters(true)] [ExtendsList(true)] [ImplementsList(true)] ClassOrInterfaceBody(true) {return productionEndTerminal("ClassOrInterfaceDeclaration","-","-","error",first,token);}

 )  }

String ClassOrInterface(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"class"  {return productionEndTerminal("ClassOrInterface1","-","-","error",first,token);}
 |
	"interface"  {return productionEndTerminal("ClassOrInterface2","-","-","error",first,token);}

 )  }

String ExtendsList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extends" ClassOrInterfaceType(true) ("," ClassOrInterfaceType(true))* {return productionEndTerminal("ExtendsList","-","-","error",first,token);}

 )  }

String ImplementsList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"implements" ClassOrInterfaceType(true) ("," ClassOrInterfaceType(true))* {return productionEndTerminal("ImplementsList","-","-","error",first,token);}

 )  }

String EnumDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"enum" <IDENTIFIER> [ImplementsList(true)] EnumBody(true) {return productionEndTerminal("EnumDeclaration","-","-","error",first,token);}

 )  }

String EnumBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" EnumConstant(true) ("," EnumConstant(true))* [EnumBodyInternal(true)] "}" {return productionEndTerminal("EnumBody","-","-","error",first,token);}

 )  }

String EnumBodyInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	";" (ClassOrInterfaceBodyDeclaration(inTerminal))* {return productionEndNonTerminal("EnumBodyInternal","","");}

 )  }

String EnumConstant(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> [Arguments(true)] [ClassOrInterfaceBody(true)] {return productionEndTerminal("EnumConstant","-","-","error",first,token);}

 )  }

String TypeParameters(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<" TypeParameter(true) ("," TypeParameter(true))* ">" {return productionEndTerminal("TypeParameters","-","-","error",first,token);}

 )  }

String TypeParameter(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> [TypeBound(true)] {return productionEndTerminal("TypeParameter","-","-","error",first,token);}

 )  }

String TypeBound(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extends" ClassOrInterfaceType(true) ("&" ClassOrInterfaceType(true))* {return productionEndTerminal("TypeBound","-","-","error",first,token);}

 )  }

String ClassOrInterfaceBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" (ClassOrInterfaceBodyDeclaration(true))* "}" {return productionEndTerminal("ClassOrInterfaceBody","-","-","error",first,token);}

 )  }

String ClassOrInterfaceBodyDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) Initializer(true) {return productionEndTerminal("InitializerDecl","{AUTO}","{AUTO}","error",first,token);}
 |
	LOOKAHEAD(Modifiers() ClassOrInterface()) Modifiers(inTerminal) ClassOrInterface(inTerminal) Id(inTerminal) [TypeParameters(inTerminal)] [ExtendsList(inTerminal)] [ImplementsList(inTerminal)] "{" (ClassOrInterfaceBodyDeclaration(inTerminal))* "}" {return productionEndNonTerminal("InnerClassDecl","{<IDENTIFIER>}","{<IDENTIFIER>}");}
 |
	LOOKAHEAD(Modifiers() "enum") Modifiers(inTerminal) "enum" t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} [ImplementsList(inTerminal)] "{" EnumConstant(inTerminal) ("," EnumConstant(inTerminal))* [EnumBodyInternal(inTerminal)] "}" {return productionEndNonTerminal("InnerEnumDecl","{<IDENTIFIER>}","{<IDENTIFIER>}");}
 |
	LOOKAHEAD( Modifiers() [ TypeParameters() ] <IDENTIFIER> "(") Modifiers(true) ConstructorDeclaration(true) {return productionEndTerminal("ConstructorDecl","{<IDENTIFIER>}","{<IDENTIFIER>}","error",first,token);}
 |
	LOOKAHEAD(Modifiers() Type() <IDENTIFIER> ( "[" "]" )* ( "," | "=" | ";" ) ) Modifiers(true) n=FieldDeclaration(true){ replaceName("FieldDeclaration",n);} {return productionEndTerminal("FieldDecl","{FieldDeclaration}","{FieldDeclaration}","error",first,token);}
 |
	LOOKAHEAD(2) Modifiers(true) n=MethodDeclaration(true){ replaceName("MethodDeclaration",n);} {return productionEndTerminal("MethodDecl","{MethodDeclaration}","{MethodDeclaration}","error",first,token);}
 |
	";"  {return productionEndTerminal("EmptyDecl","{AUTO}","{AUTO}","error",first,token);}

 )  }

String FieldDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Type(true){ replaceName("Type",n);} n=VariableDeclarator(true){ replaceName("VariableDeclarator",n);} ("," n=VariableDeclarator(true){ replaceName("VariableDeclarator",n);})* ";" {return productionEndTerminal("FieldDeclaration","-","{Type}-{VariableDeclarator}^,","error",first,token);}

 )  }

String VariableDeclarator(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=VariableDeclaratorId(true){ replaceName("VariableDeclaratorId",n);} ["=" VariableInitializer(true)] {return productionEndTerminal("VariableDeclarator","-","{VariableDeclaratorId}","error",first,token);}

 )  }

String VariableDeclaratorId(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} ("[" "]" )* {return productionEndTerminal("VariableDeclaratorId","-","{<IDENTIFIER>}","error",first,token);}

 )  }

String VariableInitializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ArrayInitializer(true) {return productionEndTerminal("VariableInitializer1","-","-","error",first,token);}
 |
	Expression(true) {return productionEndTerminal("VariableInitializer2","-","-","error",first,token);}

 )  }

String ArrayInitializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" [ArrayInitializerInternal(true)] ["," ] "}" {return productionEndTerminal("ArrayInitializer","-","-","error",first,token);}

 )  }

String ArrayInitializerInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	VariableInitializer(true) (LOOKAHEAD(2) "," VariableInitializer(true))* {return productionEndTerminal("ArrayInitializerInternal","-","-","error",first,token);}

 )  }

String MethodDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[TypeParameters(true)] ResultType(true) n=MethodDeclarator(true){ replaceName("MethodDeclarator",n);} ["throws" NameList(true)] MethodDeclarationBody(true) {return productionEndTerminal("MethodDeclaration","-","{MethodDeclarator}","error",first,token);}

 )  }

String MethodDeclarationBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Block(true) {return productionEndTerminal("MethodDeclarationBody1","-","-","error",first,token);}
 |
	";"  {return productionEndTerminal("MethodDeclarationBody2","-","-","error",first,token);}

 )  }

String MethodDeclarator(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} n=FormalParameters(true){ replaceName("FormalParameters",n);} ("[" "]" )* {return productionEndTerminal("MethodDeclarator","-","{<IDENTIFIER>}({FormalParameters})","error",first,token);}

 )  }

String FormalParameters(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"(" [n=FormalParametersInternal(true){ replaceName("FormalParametersInternal",n);}] ")" {return productionEndTerminal("FormalParameters","-","{FormalParametersInternal}","error",first,token);}

 )  }

String FormalParametersInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=FormalParameter(true){ replaceName("FormalParameter",n);} ("," n=FormalParameter(true){ replaceName("FormalParameter",n);})* {return productionEndTerminal("FormalParametersInternal","-","{FormalParameter}^-","error",first,token);}

 )  }

String FormalParameter(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["final" ] n=Type(true){ replaceName("Type",n);} ["..." ] VariableDeclaratorId(true) {return productionEndTerminal("FormalParameter","-","{Type}","error",first,token);}

 )  }

String ConstructorDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[TypeParameters(true)] t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} n=FormalParameters(true){ replaceName("FormalParameters",n);} ["throws" NameList(true)] "{" [LOOKAHEAD(ExplicitConstructorInvocation()) ExplicitConstructorInvocation(true)] (BlockStatement(true))* "}" {return productionEndTerminal("ConstructorDeclaration","-","{<IDENTIFIER>}-{FormalParameters}","error",first,token);}

 )  }

String ExplicitConstructorInvocation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD("this" Arguments() ";") "this" Arguments(true) ";" {return productionEndTerminal("ExplicitConstructorInvocation1","-","-","error",first,token);}
 |
	[LOOKAHEAD(2) PrimaryExpression(true) "."] "super" Arguments(true) ";" {return productionEndTerminal("ExplicitConstructorInvocation2","-","-","error",first,token);}

 )  }

String Initializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["static" ] Block(true) {return productionEndTerminal("Initializer","-","-","error",first,token);}

 )  }

String Type(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) ReferenceTypeP(true) {return productionEndTerminal("Type1","-","{TOSTRING}","error",first,token);}
 |
	PrimitiveType(true) {return productionEndTerminal("Type2","-","{TOSTRING}","error",first,token);}

 )  }

String ReferenceTypeP(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PrimitiveType(true) (LOOKAHEAD(2) "[" "]" )+ {return productionEndTerminal("ReferenceTypeP1","-","-","error",first,token);}
 |
	ClassOrInterfaceType(true) (LOOKAHEAD(2) "[" "]" )* {return productionEndTerminal("ReferenceTypeP2","-","-","error",first,token);}

 )  }

String ClassOrInterfaceType(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> [LOOKAHEAD(2) TypeArguments(true)] (LOOKAHEAD(2) ClassOrInterfaceTypeIntern(true))* {return productionEndTerminal("ClassOrInterfaceType","-","-","error",first,token);}

 )  }

String ClassOrInterfaceTypeIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"." <IDENTIFIER> [LOOKAHEAD(2) TypeArguments(true)] {return productionEndTerminal("ClassOrInterfaceTypeIntern","-","-","error",first,token);}

 )  }

String TypeArguments(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<" TypeArgument(true) ("," TypeArgument(true))* ">" {return productionEndTerminal("TypeArguments","-","-","error",first,token);}

 )  }

String TypeArgument(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ReferenceTypeP(true) {return productionEndTerminal("TypeArgument1","-","-","error",first,token);}
 |
	"?" [WildcardBounds(true)] {return productionEndTerminal("TypeArgument2","-","-","error",first,token);}

 )  }

String WildcardBounds(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extends" ReferenceTypeP(true) {return productionEndTerminal("WildcardBounds1","-","-","error",first,token);}
 |
	"super" ReferenceTypeP(true) {return productionEndTerminal("WildcardBounds2","-","-","error",first,token);}

 )  }

String PrimitiveType(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"boolean"  {return productionEndTerminal("PrimitiveType1","-","-","error",first,token);}
 |
	"char"  {return productionEndTerminal("PrimitiveType2","-","-","error",first,token);}
 |
	"byte"  {return productionEndTerminal("PrimitiveType3","-","-","error",first,token);}
 |
	"short"  {return productionEndTerminal("PrimitiveType4","-","-","error",first,token);}
 |
	"int"  {return productionEndTerminal("PrimitiveType5","-","-","error",first,token);}
 |
	"long"  {return productionEndTerminal("PrimitiveType6","-","-","error",first,token);}
 |
	"float"  {return productionEndTerminal("PrimitiveType7","-","-","error",first,token);}
 |
	"double"  {return productionEndTerminal("PrimitiveType8","-","-","error",first,token);}

 )  }

String ResultType(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"void"  {return productionEndTerminal("ResultType1","-","-","error",first,token);}
 |
	Type(true) {return productionEndTerminal("ResultType2","-","-","error",first,token);}

 )  }

String Name(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} (LOOKAHEAD(2) "." t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());})* {return productionEndTerminal("Name","-","{<IDENTIFIER>}^.","error",first,token);}

 )  }

String NameList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Name(true) ("," Name(true))* {return productionEndTerminal("NameList","-","-","error",first,token);}

 )  }

String Expression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ConditionalExpression(true) [LOOKAHEAD(2) AssignExp(true)] {return productionEndTerminal("Expression","-","-","error",first,token);}

 )  }

String AssignExp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AssignmentOperator(true) Expression(true) {return productionEndTerminal("AssignExp","-","-","error",first,token);}

 )  }

String AssignmentOperator(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"="  {return productionEndTerminal("AssignmentOperator1","-","-","error",first,token);}
 |
	"*="  {return productionEndTerminal("AssignmentOperator2","-","-","error",first,token);}
 |
	"/="  {return productionEndTerminal("AssignmentOperator3","-","-","error",first,token);}
 |
	"%="  {return productionEndTerminal("AssignmentOperator4","-","-","error",first,token);}
 |
	"+="  {return productionEndTerminal("AssignmentOperator5","-","-","error",first,token);}
 |
	"-="  {return productionEndTerminal("AssignmentOperator6","-","-","error",first,token);}
 |
	"<<="  {return productionEndTerminal("AssignmentOperator7","-","-","error",first,token);}
 |
	">>="  {return productionEndTerminal("AssignmentOperator8","-","-","error",first,token);}
 |
	">>>="  {return productionEndTerminal("AssignmentOperator9","-","-","error",first,token);}
 |
	"&="  {return productionEndTerminal("AssignmentOperator10","-","-","error",first,token);}
 |
	"^="  {return productionEndTerminal("AssignmentOperator11","-","-","error",first,token);}
 |
	"|="  {return productionEndTerminal("AssignmentOperator12","-","-","error",first,token);}

 )  }

String ConditionalExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(ConditionalOrExpression() "?") ConditionalExpressionFull(true) {return productionEndTerminal("ConditionalExpression1","-","-","error",first,token);}
 |
	ConditionalOrExpression(true) {return productionEndTerminal("ConditionalExpression2","-","-","error",first,token);}

 )  }

String ConditionalExpressionFull(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ConditionalOrExpression(true) "?" Expression(true) ":" Expression(true) {return productionEndTerminal("ConditionalExpressionFull","-","-","error",first,token);}

 )  }

String ConditionalOrExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ConditionalAndExpression(true) ("||" ConditionalAndExpression(true))* {return productionEndTerminal("ConditionalOrExpression","-","-","error",first,token);}

 )  }

String ConditionalAndExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	InclusiveOrExpression(true) ("&&" InclusiveOrExpression(true))* {return productionEndTerminal("ConditionalAndExpression","-","-","error",first,token);}

 )  }

String InclusiveOrExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ExclusiveOrExpression(true) ("|" ExclusiveOrExpression(true))* {return productionEndTerminal("InclusiveOrExpression","-","-","error",first,token);}

 )  }

String ExclusiveOrExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AndExpression(true) ("^" AndExpression(true))* {return productionEndTerminal("ExclusiveOrExpression","-","-","error",first,token);}

 )  }

String AndExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	EqualityExpression(true) ("&" EqualityExpression(true))* {return productionEndTerminal("AndExpression","-","-","error",first,token);}

 )  }

String EqualityExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	InstanceOfExpression(true) (EqualityExpressionIntern(true))* {return productionEndTerminal("EqualityExpression","-","-","error",first,token);}

 )  }

String EqualityExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	EqualityOp(true) InstanceOfExpression(true) {return productionEndTerminal("EqualityExpressionIntern","-","-","error",first,token);}

 )  }

String EqualityOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"=="  {return productionEndTerminal("EqualityOp1","-","-","error",first,token);}
 |
	"!="  {return productionEndTerminal("EqualityOp2","-","-","error",first,token);}

 )  }

String InstanceOfExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	RelationalExpression(true) ["instanceof" Type(true)] {return productionEndTerminal("InstanceOfExpression","-","-","error",first,token);}

 )  }

String RelationalExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ShiftExpression(true) (RelationalExpressionIntern(true))* {return productionEndTerminal("RelationalExpression","-","-","error",first,token);}

 )  }

String RelationalExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	RelationalOp(true) ShiftExpression(true) {return productionEndTerminal("RelationalExpressionIntern","-","-","error",first,token);}

 )  }

String RelationalOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<"  {return productionEndTerminal("RelationalOp1","-","-","error",first,token);}
 |
	">"  {return productionEndTerminal("RelationalOp2","-","-","error",first,token);}
 |
	"<="  {return productionEndTerminal("RelationalOp3","-","-","error",first,token);}
 |
	">="  {return productionEndTerminal("RelationalOp4","-","-","error",first,token);}

 )  }

String ShiftExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AdditiveExpression(true) (LOOKAHEAD(2) ShiftExpressionRight(true))* {return productionEndTerminal("ShiftExpression","-","-","error",first,token);}

 )  }

String ShiftExpressionRight(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ShiftOp(true) AdditiveExpression(true) {return productionEndTerminal("ShiftExpressionRight","-","-","error",first,token);}

 )  }

String ShiftOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<<"  {return productionEndTerminal("ShiftOp1","-","-","error",first,token);}
 |
	LOOKAHEAD(3) ">" ">" ">"  {return productionEndTerminal("ShiftOp2","-","-","error",first,token);}
 |
	LOOKAHEAD(2) ">" ">"  {return productionEndTerminal("ShiftOp3","-","-","error",first,token);}

 )  }

String AdditiveExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	MultiplicativeExpression(true) (AdditiveExpressionIntern(true))* {return productionEndTerminal("AdditiveExpression","-","-","error",first,token);}

 )  }

String AdditiveExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AdditiveOp(true) MultiplicativeExpression(true) {return productionEndTerminal("AdditiveExpressionIntern","-","-","error",first,token);}

 )  }

String AdditiveOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"+"  {return productionEndTerminal("AdditiveOp1","-","-","error",first,token);}
 |
	"-"  {return productionEndTerminal("AdditiveOp2","-","-","error",first,token);}

 )  }

String MultiplicativeExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	UnaryExpression(true) (MultiplicativeExpressionIntern(true))* {return productionEndTerminal("MultiplicativeExpression","-","-","error",first,token);}

 )  }

String MultiplicativeExpressionIntern(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	MultiplicativeOp(true) UnaryExpression(true) {return productionEndTerminal("MultiplicativeExpressionIntern","-","-","error",first,token);}

 )  }

String MultiplicativeOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*"  {return productionEndTerminal("MultiplicativeOp1","-","-","error",first,token);}
 |
	"/"  {return productionEndTerminal("MultiplicativeOp2","-","-","error",first,token);}
 |
	"%"  {return productionEndTerminal("MultiplicativeOp3","-","-","error",first,token);}

 )  }

String UnaryExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	AdditiveOp(true) UnaryExpression(true) {return productionEndTerminal("UnaryExpression1","-","-","error",first,token);}
 |
	PreIncrementExpression(true) {return productionEndTerminal("UnaryExpression2","-","-","error",first,token);}
 |
	PreDecrementExpression(true) {return productionEndTerminal("UnaryExpression3","-","-","error",first,token);}
 |
	UnaryExpressionNotPlusMinus(true) {return productionEndTerminal("UnaryExpression4","-","-","error",first,token);}

 )  }

String PreIncrementExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"++" PrimaryExpression(true) {return productionEndTerminal("PreIncrementExpression","-","-","error",first,token);}

 )  }

String PreDecrementExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"--" PrimaryExpression(true) {return productionEndTerminal("PreDecrementExpression","-","-","error",first,token);}

 )  }

String UnaryExpressionNotPlusMinus(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	UnaryOp(true) UnaryExpression(true) {return productionEndTerminal("UnaryExpressionNotPlusMinus1","-","-","error",first,token);}
 |
	LOOKAHEAD(CastLookahead()) CastExpression(true) {return productionEndTerminal("UnaryExpressionNotPlusMinus2","-","-","error",first,token);}
 |
	PostfixExpression(true) {return productionEndTerminal("UnaryExpressionNotPlusMinus3","-","-","error",first,token);}

 )  }

String UnaryOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"~"  {return productionEndTerminal("UnaryOp1","-","-","error",first,token);}
 |
	"!"  {return productionEndTerminal("UnaryOp2","-","-","error",first,token);}

 )  }

String CastLookahead(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "(" PrimitiveType(true) {return productionEndTerminal("CastLookahead1","-","-","error",first,token);}
 |
	LOOKAHEAD("(" Type() "[") "(" Type(true) "[" "]" {return productionEndTerminal("CastLookahead2","-","-","error",first,token);}
 |
	"(" Type(true) ")" CastLAOp(true) {return productionEndTerminal("CastLookahead3","-","-","error",first,token);}

 )  }

String CastLAOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"~"  {return productionEndTerminal("CastLAOp1","-","-","error",first,token);}
 |
	"!"  {return productionEndTerminal("CastLAOp2","-","-","error",first,token);}
 |
	"("  {return productionEndTerminal("CastLAOp3","-","-","error",first,token);}
 |
	"this"  {return productionEndTerminal("CastLAOp4","-","-","error",first,token);}
 |
	"super"  {return productionEndTerminal("CastLAOp5","-","-","error",first,token);}
 |
	"new"  {return productionEndTerminal("CastLAOp6","-","-","error",first,token);}
 |
	<IDENTIFIER> {return productionEndTerminal("CastLAOp7","-","-","error",first,token);}
 |
	Literal(true) {return productionEndTerminal("CastLAOp8","-","-","error",first,token);}

 )  }

String PostfixExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PrimaryExpression(true) [PostfixOp(true)] {return productionEndTerminal("PostfixExpression","-","-","error",first,token);}

 )  }

String PostfixOp(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"++"  {return productionEndTerminal("PostfixOp1","-","-","error",first,token);}
 |
	"--"  {return productionEndTerminal("PostfixOp2","-","-","error",first,token);}

 )  }

String CastExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD("(" PrimitiveType()) "(" Type(true) ")" UnaryExpression(true) {return productionEndTerminal("CastExpression1","-","-","error",first,token);}
 |
	"(" Type(true) ")" UnaryExpressionNotPlusMinus(true) {return productionEndTerminal("CastExpression2","-","-","error",first,token);}

 )  }

String PrimaryExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PrimaryPrefix(true) (LOOKAHEAD(2) PrimarySuffix(true))* {return productionEndTerminal("PrimaryExpression","-","-","error",first,token);}

 )  }

String MemberSelector(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"." TypeArguments(true) <IDENTIFIER> {return productionEndTerminal("MemberSelector","-","-","error",first,token);}

 )  }

String PrimaryPrefix(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Literal(true) {return productionEndTerminal("PrimaryPrefix1","-","-","error",first,token);}
 |
	"this"  {return productionEndTerminal("PrimaryPrefix2","-","-","error",first,token);}
 |
	"super" "." <IDENTIFIER> {return productionEndTerminal("PrimaryPrefix3","-","-","error",first,token);}
 |
	"(" Expression(true) ")" {return productionEndTerminal("PrimaryPrefix4","-","-","error",first,token);}
 |
	AllocationExpression(true) {return productionEndTerminal("PrimaryPrefix5","-","-","error",first,token);}
 |
	LOOKAHEAD( ResultType() "." "class") ResultType(true) "." "class" {return productionEndTerminal("PrimaryPrefix6","-","-","error",first,token);}
 |
	Name(true) {return productionEndTerminal("PrimaryPrefix7","-","-","error",first,token);}

 )  }

String PrimarySuffix(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "." "this"  {return productionEndTerminal("PrimarySuffix1","-","-","error",first,token);}
 |
	LOOKAHEAD(2) "." AllocationExpression(true) {return productionEndTerminal("PrimarySuffix2","-","-","error",first,token);}
 |
	LOOKAHEAD(3) MemberSelector(true) {return productionEndTerminal("PrimarySuffix3","-","-","error",first,token);}
 |
	"[" Expression(true) "]" {return productionEndTerminal("PrimarySuffix4","-","-","error",first,token);}
 |
	"." <IDENTIFIER> {return productionEndTerminal("PrimarySuffix5","-","-","error",first,token);}
 |
	Arguments(true) {return productionEndTerminal("PrimarySuffix6","-","-","error",first,token);}

 )  }

String Literal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<INTEGER_LITERAL> {return productionEndTerminal("Literal1","-","-","error",first,token);}
 |
	<FLOATING_POINT_LITERAL> {return productionEndTerminal("Literal2","-","-","error",first,token);}
 |
	<CHARACTER_LITERAL> {return productionEndTerminal("Literal3","-","-","error",first,token);}
 |
	<STRING_LITERAL> {return productionEndTerminal("Literal4","-","-","error",first,token);}
 |
	BooleanLiteral(true) {return productionEndTerminal("Literal5","-","-","error",first,token);}
 |
	NullLiteral(true) {return productionEndTerminal("Literal6","-","-","error",first,token);}

 )  }

String BooleanLiteral(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"true"  {return productionEndTerminal("BooleanLiteral1","-","-","error",first,token);}
 |
	"false"  {return productionEndTerminal("BooleanLiteral2","-","-","error",first,token);}

 )  }

String NullLiteral(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"null"  {return productionEndTerminal("NullLiteral","-","-","error",first,token);}

 )  }

String Arguments(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"(" [ArgumentList(true)] ")" {return productionEndTerminal("Arguments","-","-","error",first,token);}

 )  }

String ArgumentList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Expression(true) ("," Expression(true))* {return productionEndTerminal("ArgumentList","-","-","error",first,token);}

 )  }

String AllocationExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "new" PrimitiveType(true) ArrayDimsAndInits(true) {return productionEndTerminal("AllocationExpression1","-","-","error",first,token);}
 |
	"new" ClassOrInterfaceType(true) [TypeArguments(true)] AllocationExpressionInit(true) {return productionEndTerminal("AllocationExpression2","-","-","error",first,token);}

 )  }

String AllocationExpressionInit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	ArrayDimsAndInits(true) {return productionEndTerminal("AllocationExpressionInit1","-","-","error",first,token);}
 |
	Arguments(true) [ClassOrInterfaceBody(true)] {return productionEndTerminal("AllocationExpressionInit2","-","-","error",first,token);}

 )  }

String ArrayDimsAndInits(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "[" Expression(true) "]" (LOOKAHEAD(2) "[" Expression(true) "]")* (LOOKAHEAD(2) "[" "]" )* {return productionEndTerminal("ArrayDimsAndInits1","-","-","error",first,token);}
 |
	("[" "]" )+ ArrayInitializer(true) {return productionEndTerminal("ArrayDimsAndInits2","-","-","error",first,token);}

 )  }

String Statement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) LabeledStatement(true) {return productionEndTerminal("Statement1","-","-","error",first,token);}
 |
	AssertStatement(true) {return productionEndTerminal("Statement2","-","-","error",first,token);}
 |
	Block(true) {return productionEndTerminal("Statement3","-","-","error",first,token);}
 |
	EmptyStatement(true) {return productionEndTerminal("Statement4","-","-","error",first,token);}
 |
	StatementExpression(true) ";" {return productionEndTerminal("Statement5","-","-","error",first,token);}
 |
	SwitchStatement(true) {return productionEndTerminal("Statement6","-","-","error",first,token);}
 |
	IfStatement(true) {return productionEndTerminal("Statement7","-","-","error",first,token);}
 |
	WhileStatement(true) {return productionEndTerminal("Statement8","-","-","error",first,token);}
 |
	DoStatement(true) {return productionEndTerminal("Statement9","-","-","error",first,token);}
 |
	ForStatement(true) {return productionEndTerminal("Statement10","-","-","error",first,token);}
 |
	BreakStatement(true) {return productionEndTerminal("Statement11","-","-","error",first,token);}
 |
	ContinueStatement(true) {return productionEndTerminal("Statement12","-","-","error",first,token);}
 |
	ReturnStatement(true) {return productionEndTerminal("Statement13","-","-","error",first,token);}
 |
	ThrowStatement(true) {return productionEndTerminal("Statement14","-","-","error",first,token);}
 |
	SynchronizedStatement(true) {return productionEndTerminal("Statement15","-","-","error",first,token);}
 |
	TryStatement(true) {return productionEndTerminal("Statement16","-","-","error",first,token);}

 )  }

String AssertStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"assert" Expression(true) [":" Expression(true)] ";" {return productionEndTerminal("AssertStatement","-","-","error",first,token);}

 )  }

String LabeledStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> ":" Statement(true) {return productionEndTerminal("LabeledStatement","-","-","error",first,token);}

 )  }

String Block(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" (BlockStatement(true))* "}" {return productionEndTerminal("Block","-","-","error",first,token);}

 )  }

String BlockStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD([ "final" ] Type() <IDENTIFIER>) LocalVariableDeclaration(true) ";" {return productionEndTerminal("BlockStatement1","-","-","error",first,token);}
 |
	Statement(true) {return productionEndTerminal("BlockStatement2","-","-","error",first,token);}
 |
	ClassOrInterfaceDeclaration(true) {return productionEndTerminal("BlockStatement3","-","-","error",first,token);}

 )  }

String LocalVariableDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["final" ] Type(true) VariableDeclarator(true) ("," VariableDeclarator(true))* {return productionEndTerminal("LocalVariableDeclaration","-","-","error",first,token);}

 )  }

String EmptyStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	";"  {return productionEndTerminal("EmptyStatement","-","-","error",first,token);}

 )  }

String StatementExpression(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	PreIncrementExpression(true) {return productionEndTerminal("StatementExpression1","-","-","error",first,token);}
 |
	PreDecrementExpression(true) {return productionEndTerminal("StatementExpression2","-","-","error",first,token);}
 |
	PrimaryExpression(true) [StatementExpressionAssignment(true)] {return productionEndTerminal("StatementExpression3","-","-","error",first,token);}

 )  }

String StatementExpressionAssignment(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"++"  {return productionEndTerminal("StatementExpressionAssignment1","-","-","error",first,token);}
 |
	"--"  {return productionEndTerminal("StatementExpressionAssignment2","-","-","error",first,token);}
 |
	AssignmentOperator(true) Expression(true) {return productionEndTerminal("StatementExpressionAssignment3","-","-","error",first,token);}

 )  }

String SwitchStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"switch" "(" Expression(true) ")" "{" (SwitchStatementLabel(true))* "}" {return productionEndTerminal("SwitchStatement","-","-","error",first,token);}

 )  }

String SwitchStatementLabel(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	SwitchLabel(true) (BlockStatement(true))* {return productionEndTerminal("SwitchStatementLabel","-","-","error",first,token);}

 )  }

String SwitchLabel(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"case" Expression(true) ":" {return productionEndTerminal("SwitchLabel1","-","-","error",first,token);}
 |
	"default" ":"  {return productionEndTerminal("SwitchLabel2","-","-","error",first,token);}

 )  }

String IfStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"if" "(" Expression(true) ")" Statement(true) [LOOKAHEAD(1) "else" Statement(true)] {return productionEndTerminal("IfStatement","-","-","error",first,token);}

 )  }

String WhileStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"while" "(" Expression(true) ")" Statement(true) {return productionEndTerminal("WhileStatement","-","-","error",first,token);}

 )  }

String DoStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"do" Statement(true) "while" "(" Expression(true) ")" ";" {return productionEndTerminal("DoStatement","-","-","error",first,token);}

 )  }

String ForStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"for" "(" ForStatementInternal(true) ")" Statement(true) {return productionEndTerminal("ForStatement","-","-","error",first,token);}

 )  }

String ForStatementInternal(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(Type() <IDENTIFIER> ":") Type(true) <IDENTIFIER> ":" Expression(true) {return productionEndTerminal("ForStatementInternal1","-","-","error",first,token);}
 |
	[ForInit(true)] ";" [Expression(true)] ";" [ForUpdate(true)] {return productionEndTerminal("ForStatementInternal2","-","-","error",first,token);}

 )  }

String ForInit(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD([ "final" ] Type() <IDENTIFIER>) LocalVariableDeclaration(true) {return productionEndTerminal("ForInit1","-","-","error",first,token);}
 |
	StatementExpressionList(true) {return productionEndTerminal("ForInit2","-","-","error",first,token);}

 )  }

String StatementExpressionList(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	StatementExpression(true) ("," StatementExpression(true))* {return productionEndTerminal("StatementExpressionList","-","-","error",first,token);}

 )  }

String ForUpdate(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	StatementExpressionList(true) {return productionEndTerminal("ForUpdate","-","-","error",first,token);}

 )  }

String BreakStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"break" [<IDENTIFIER>] ";" {return productionEndTerminal("BreakStatement","-","-","error",first,token);}

 )  }

String ContinueStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"continue" [<IDENTIFIER>] ";" {return productionEndTerminal("ContinueStatement","-","-","error",first,token);}

 )  }

String ReturnStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"return" [Expression(true)] ";" {return productionEndTerminal("ReturnStatement","-","-","error",first,token);}

 )  }

String ThrowStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"throw" Expression(true) ";" {return productionEndTerminal("ThrowStatement","-","-","error",first,token);}

 )  }

String SynchronizedStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"synchronized" "(" Expression(true) ")" Block(true) {return productionEndTerminal("SynchronizedStatement","-","-","error",first,token);}

 )  }

String TryStatement(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"try" Block(true) TryStatementEnd(true) {return productionEndTerminal("TryStatement","-","-","error",first,token);}

 )  }

String TryStatementEnd(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(CatchBlock(true))+ {return productionEndTerminal("TryStatementEnd1","-","-","error",first,token);}
 |
	"finally" Block(true) {return productionEndTerminal("FinallyBlock","-","-","error",first,token);}

 )  }

String CatchBlock(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"catch" "(" FormalParameter(true) ")" Block(true) {return productionEndTerminal("CatchBlock","-","-","error",first,token);}

 )  }

String Annotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD("@" Name() "(" ( <IDENTIFIER> "=" | ")" )) NormalAnnotation(true) {return productionEndTerminal("Annotation1","-","-","error",first,token);}
 |
	LOOKAHEAD("@" Name() "(") SingleMemberAnnotation(true) {return productionEndTerminal("Annotation2","-","-","error",first,token);}
 |
	MarkerAnnotation(true) {return productionEndTerminal("Annotation3","-","-","error",first,token);}

 )  }

String NormalAnnotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" Name(true) "(" [MemberValuePairs(true)] ")" {return productionEndTerminal("NormalAnnotation","-","-","error",first,token);}

 )  }

String MarkerAnnotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" Name(true) {return productionEndTerminal("MarkerAnnotation","-","-","error",first,token);}

 )  }

String SingleMemberAnnotation(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"@" Name(true) "(" MemberValue(true) ")" {return productionEndTerminal("SingleMemberAnnotation","-","-","error",first,token);}

 )  }

String MemberValuePairs(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	MemberValuePair(true) ("," MemberValuePair(true))* {return productionEndTerminal("MemberValuePairs","-","-","error",first,token);}

 )  }

String MemberValuePair(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> "=" MemberValue(true) {return productionEndTerminal("MemberValuePair","-","-","error",first,token);}

 )  }

String MemberValue(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Annotation(true) {return productionEndTerminal("MemberValue1","-","-","error",first,token);}
 |
	MemberValueArrayInitializer(true) {return productionEndTerminal("MemberValue2","-","-","error",first,token);}
 |
	ConditionalExpression(true) {return productionEndTerminal("MemberValue3","-","-","error",first,token);}

 )  }

String MemberValueArrayInitializer(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" MemberValue(true) (LOOKAHEAD(2) "," MemberValue(true))* ["," ] "}" {return productionEndTerminal("MemberValueArrayInitializer","-","-","error",first,token);}

 )  }

String AnnotationTypeBody(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" (AnnotationTypeMemberDeclaration(true))* "}" {return productionEndTerminal("AnnotationTypeBody","-","-","error",first,token);}

 )  }

String AnnotationTypeMemberDeclaration(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(Modifiers() Type() <IDENTIFIER> "(") Modifiers(true) Type(true) t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} "(" ")" [DefaultValue(true)] ";" {return productionEndTerminal("AnnotationMethodDecl","{<IDENTIFIER>}","{<IDENTIFIER>}","error",first,token);}
 |
	LOOKAHEAD(Modifiers() "@" "interface") Modifiers(inTerminal) "@" "interface" Id(inTerminal) "{" (AnnotationTypeMemberDeclaration(inTerminal))* "}" {return productionEndNonTerminal("AnnotationInnerAnnotation","{<IDENTIFIER>}","{<IDENTIFIER>}");}
 |
	LOOKAHEAD(1) Modifiers(inTerminal) ClassOrInterface(inTerminal) Id(inTerminal) [TypeParameters(inTerminal)] [ExtendsList(inTerminal)] [ImplementsList(inTerminal)] "{" (ClassOrInterfaceBodyDeclaration(inTerminal))* "}" {return productionEndNonTerminal("AnnotationInnerClass","{<IDENTIFIER>}","{<IDENTIFIER>}");}
 |
	LOOKAHEAD(2) Modifiers(inTerminal) "enum" t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",t.toString());} [ImplementsList(inTerminal)] "{" EnumConstant(inTerminal) ("," EnumConstant(inTerminal))* [EnumBodyInternal(inTerminal)] "}" {return productionEndNonTerminal("AnnotationInnerEnum","{<IDENTIFIER>}","{<IDENTIFIER>}");}
 |
	LOOKAHEAD(1) Modifiers(true) n=FieldDeclaration(true){ replaceName("FieldDeclaration",n);} {return productionEndTerminal("AnnotationFieldDecl","{FieldDeclaration}","{FieldDeclaration}","error",first,token);}
 |
	";"  {return productionEndTerminal("AnnoationEmptyDecl","{AUTO}","{AUTO}","error",first,token);}

 )  }

String DefaultValue(boolean inTerminal) : { Token first=null,t;String n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"default" MemberValue(true) {return productionEndTerminal("DefaultValue","-","-","error",first,token);}

 )  }

