-- GENERATED by C->Haskell Compiler, version 0.10.17 "Altocumulus Stratiformis Perlucidus Undulatus", 07 Sep 2002 (Haskell)
-- ** Edit the orignal .chs file instead!

--  -*-haskell-*-
--  GIMP Toolkit (GTK) @entry Keys@
--
--  Author : Jens Petersen
--  Created: 24 May 2002
--
--  Version $Revision: 1.1 $ from $Date: 2008-10-14 18:01:20 $
--
--  Copyright (c) 2002 Jens Petersen
--
--  This library is free software; you can redistribute it and/or
--  modify it under the terms of the GNU Library General Public
--  License as published by the Free Software Foundation; either
--  version 2 of the License, or (at your option) any later version.
--
--  This library is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--  Library General Public License for more details.
--
-- @description@ --------------------------------------------------------------
--
--  Gdk keyval functions.
--
-- @documentation@ ------------------------------------------------------------
--
--
-- @todo@ ---------------------------------------------------------------------
--
--  * Documentation
--
module GdkKeys(
  keyvalName,
  keyvalFromName
  ) where

import FFI
import LocalData(unsafePerformIO)



keyvalName :: Integer -> Maybe String
keyvalName a1 =
  let {a1' = fromIntegral a1} in 
  let {res = keyvalName'_ a1'} in
  let {res' = maybePeekCString res} in
  (res')
  where
  maybePeekCString = unsafePerformIO . (maybePeek peekCString)
--   maybePeekCString = maybePeek peekCString

keyvalFromName :: String -> Integer
keyvalFromName a1 =
  unsafePerformIO $
  withCString a1 $ \a1' -> 
  let {res = keyvalFromName'_ a1'} in
  let {res' = fromIntegral res} in
  return (res')


foreign import ccall "gdk_keyval_name"
  keyvalName'_ :: (CUInt -> (Ptr CChar))

foreign import ccall "gdk_keyval_from_name"
  keyvalFromName'_ :: ((Ptr CChar) -> CUInt)
