/* Generated By:JavaCC: Do not edit this line. CApproxParserConstants.java */
package de.ovgu.cide.fstgen.parsers.generated_capprox;

public interface CApproxParserConstants {

  int EOF = 0;
  int LITERAL = 9;
  int INTEGER_LITERAL = 10;
  int DECIMAL_LITERAL = 11;
  int HEX_LITERAL = 12;
  int OCTAL_LITERAL = 13;
  int FLOATING_POINT_LITERAL = 14;
  int EXPONENT = 15;
  int CHARACTER_LITERAL = 16;
  int STRING_LITERAL = 17;
  int INCLUDE = 18;
  int DEFINE = 19;
  int IFDEF = 20;
  int IFNDEF = 21;
  int ENDIF = 22;
  int ELIF = 23;
  int ELSIF = 24;
  int PPLINE = 25;
  int PPUNDEF = 26;
  int PPPRAGMA = 27;
  int PPERROR = 28;
  int TYPEDEF = 29;
  int ENUM = 30;
  int EXTERN = 31;
  int UNSIGNED = 32;
  int CONST = 33;
  int STATIC = 34;
  int STRUCT = 35;
  int INLINE = 36;
  int INLINE2 = 37;
  int INLINE3 = 38;
  int WEIREDSTUFF1 = 39;
  int WEIREDSTUFF2 = 40;
  int IF = 41;
  int ELSE = 42;
  int FOR = 43;
  int WHILE = 44;
  int DO = 45;
  int SWITCH = 46;
  int CASE = 47;
  int SWDEFAULT = 48;
  int SEMI = 49;
  int COLON = 50;
  int COMMA = 51;
  int LT = 52;
  int GT = 53;
  int OB = 54;
  int CB = 55;
  int OCB = 56;
  int CCB = 57;
  int STAR = 58;
  int EQ = 59;
  int HASH = 60;
  int PIPE = 61;
  int IDENTIFIER = 62;
  int LETTER = 63;
  int DIGIT = 64;
  int OTHER = 65;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "<LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"include\"",
    "\"define\"",
    "\"ifdef\"",
    "\"ifndef\"",
    "\"endif\"",
    "\"elif\"",
    "\"elsif\"",
    "\"line\"",
    "\"undef\"",
    "\"pragma\"",
    "\"error\"",
    "\"typedef\"",
    "\"enum\"",
    "\"extern\"",
    "\"unsigned\"",
    "\"const\"",
    "\"static\"",
    "\"struct\"",
    "\"inline\"",
    "\"__inline__\"",
    "\"__inline\"",
    "\"__regbank\"",
    "\"__TIPOFUNC__\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\"=\"",
    "\"#\"",
    "\"|\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<OTHER>",
  };

}
