/* Generated By:JavaCC: Do not edit this line. SDFParserConstants.java */
package de.ovgu.cide.fstgen.parsers.generated_sdf;

public interface SDFParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int MODULE = 13;
  int SPECIFICATION = 14;
  int IMPORTS = 15;
  int EXPORTS = 16;
  int HIDDENS = 17;
  int SORTS = 18;
  int STARTSYMBOL = 19;
  int CF = 20;
  int LEX = 21;
  int SYNTAX = 22;
  int VARIABLES = 23;
  int LEXICALSYNTAX = 24;
  int CFREESYNTAX = 25;
  int LEXICALVARS = 26;
  int CONS = 27;
  int LEFT = 28;
  int ASSOC = 29;
  int AVOID = 30;
  int RIGHT = 31;
  int PREFER = 32;
  int BRACKET = 33;
  int REJECT = 34;
  int NONASSOC = 35;
  int RECOVER = 36;
  int DEPRECATED = 37;
  int INDENTPADDING = 38;
  int PRIORITIES = 39;
  int CFREEPRIORITIES = 40;
  int LEXICALRESTRICTIONS = 41;
  int CFREERESTRICTIONS = 42;
  int INTEGER_LITERAL = 43;
  int DECIMAL_LITERAL = 44;
  int HEX_LITERAL = 45;
  int OCTAL_LITERAL = 46;
  int FLOATING_POINT_LITERAL = 47;
  int EXPONENT = 48;
  int CHARACTER_LITERAL = 49;
  int STRING_LITERAL = 50;
  int CHARCLASS_LITERAL = 51;
  int IDENTIFIER = 52;
  int LETTER = 53;
  int LCCHAR = 54;
  int UCCHAR = 55;
  int DIGIT = 56;
  int LPAREN = 57;
  int RPAREN = 58;
  int LBRACE = 59;
  int RBRACE = 60;
  int LBRACKET = 61;
  int RBRACKET = 62;
  int DLBRACKET = 63;
  int DRBRACKET = 64;
  int LT = 65;
  int GT = 66;
  int PLUS = 67;
  int MINUS = 68;
  int STAR = 69;
  int SLASH = 70;
  int COMMA = 71;
  int SEMICOLON = 72;
  int DDOT = 73;
  int DOT = 74;
  int QUESTIONMARK = 75;
  int EXCLAMATIONMARK = 76;
  int NUMBERSIGN = 77;
  int AT = 78;
  int DOLLAR = 79;
  int VERTICALLINE = 80;
  int TILDE = 81;
  int AMPERSAND = 82;
  int PERCENTAGE = 83;
  int CIRCUMFLEXACCENT = 84;
  int GRAVEACCENT = 85;
  int APOSTROPHE = 86;
  int ARROW = 87;
  int ASSIGN = 88;
  int NOTALLOWED = 89;
  int LOWLINE = 90;
  int QUOTATIONMARK = 91;
  int BACKSLASH = 92;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"%%\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"module\"",
    "\"specification\"",
    "\"imports\"",
    "\"exports\"",
    "\"hiddens\"",
    "\"sorts\"",
    "\"context-free start-symbols\"",
    "\"CF\"",
    "\"LEX\"",
    "\"syntax\"",
    "\"variables\"",
    "\"lexical syntax\"",
    "\"context-free syntax\"",
    "\"lexical variables\"",
    "\"cons\"",
    "\"left\"",
    "\"assoc\"",
    "\"avoid\"",
    "\"right\"",
    "\"prefer\"",
    "\"bracket\"",
    "\"reject\"",
    "\"non-assoc\"",
    "\"recover\"",
    "\"deprecated\"",
    "\"indentpadding\"",
    "\"priorities\"",
    "\"context-free priorities\"",
    "\"lexical restrictions\"",
    "\"context-free restrictions\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<CHARCLASS_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<LCCHAR>",
    "<UCCHAR>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"[[\"",
    "\"]]\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"?\"",
    "\"!\"",
    "\"#\"",
    "\"@\"",
    "\"$\"",
    "\"|\"",
    "\"~\"",
    "\"&\"",
    "\"%\"",
    "\"^\"",
    "\"`\"",
    "\"\\\'\"",
    "\"->\"",
    "\"=\"",
    "\"-/-\"",
    "\"_\"",
    "\"\\\"\"",
    "\"\\\\\"",
  };

}
