// -*- java -*-
// Copyright  Corporation for National Research Initiatives

options {
	STATIC = false;                          // multiple parsers
	COMMON_TOKEN_ACTION = true;              // CommonTokenAction(Token)
	USER_CHAR_STREAM = true;
	UNICODE_INPUT = true;
}


PARSER_BEGIN(PythonParser)

package tmp.generated_python;
import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;
import de.ovgu.cide.fstgen.ast.*;

public class PythonParser extends AbstractFSTParser {
	public PythonParser() {}
}

PARSER_END(PythonParser)

TOKEN_MGR_DECLS: {
	int indentation[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
	int level = 0;
	int dedents = 0;
	int parens = 0;
	int indent;

	boolean expect_indent = false;

	boolean compound = false;

	public boolean single_input = false;

	// parsing of partial sentence (interactive) mode
	public boolean partial = false;
	// control whether empty new lines on EOF force sentence closing NEWLINE even if indent
	// is expected,i.e. classic behavior at jython prompt (different from codeop behavior)
	public boolean stdprompt = false;

	public boolean generator_allowed = true;

	static Token addDedent(Token previous) {
		Token t = new Token();
		t.kind = DEDENT;
		t.beginLine = previous.beginLine;
		t.endLine = previous.endLine;
		t.beginColumn = previous.beginColumn;
		t.endColumn = previous.endColumn;
		t.offset=previous.offset;
		t.length=0;
		t.image = "";
		t.specialToken = null;
		t.next = null;
		previous.next = t;
		return t;
	}

	void CommonTokenAction(Token t) {
		/*
			if not partial: EOF is expanded to token sequences comprising
				if single_input: [NEWLINE] necessary DEDENT NEWLINE (afterward EOF)
				otherwise      : [NEWLINE] necessary DEDENT EOF
			if partial: EOF expansion happens only if EOF preceded by empty line (etc),
			i.e. lexer is in MAYBE_FORCE_NEWLINE_IF_EOF state
		*/
		if (t.kind == EOF) {
		// System.out.println("EOF: "+single_input+", "+curLexState+", "+level);
			if (!partial || curLexState == MAYBE_FORCE_NEWLINE_IF_EOF) {
				if (curLexState == DEFAULT) {
					t.kind = NEWLINE;
				} else {
					t.kind = DEDENT;
					t.length=0;
					if (level >= 0) level -= 1;
				}
				while (level >= 0) {
					level--;
					t = addDedent(t);
				}
				if (!single_input) {
					t.kind = EOF;
					t.image = "<EOF>";
				} else {
					t.kind = NEWLINE;
					t.image = "<FORCENL>";
					single_input = false;
				}
			}
		} else if (t.kind == YIELD) {
			if (!generator_allowed) {
				t.kind = NAME;
			}
		}
	}

	void indenting(int ind) {
		indent = ind;
		if (indent == indentation[level])
			SwitchTo(INDENTATION_UNCHANGED);
		else
			SwitchTo(INDENTING);
	}
}


SKIP : {
	<SPACE: " ">
	|  "\t"
	|  "\014"
	|  <CONTINUATION: ("\\") ("\r\n"|"\n"|"\r")>
	|  <NEWLINE1: ("\r\n"|"\n"|"\r")> {
		if (parens == 0) {
			indent = 0;
			input_stream.backup(1);
			if (level == 0)
				SwitchTo(FORCE_NEWLINE1);
			else
				SwitchTo(FORCE_NEWLINE2);
		}
	}
}

<FORCE_NEWLINE1> TOKEN : {
	<NEWLINE: ("\n" | "\r")> : INDENTATION_UNCHANGED
}

<FORCE_NEWLINE2> TOKEN : {
	<NEWLINE2: ("\n" | "\r")> { matchedToken.kind = NEWLINE; } : INDENTING
}

// causes expected warning
<MAYBE_FORCE_NEWLINE_IF_EOF> SKIP : {
	<""> { indenting(0); }
}

<INDENTING, INDENTATION_UNCHANGED> SKIP : {
	"\t" { indenting((indent/8+1)*8); }
	|  " " { indenting(indent+1); }
	|  "\014" { indenting(0); }
	|  <CRLF1: ("\r\n" | "\n" | "\r")> {
		//System.out.println("empty line");
		// if partial single_input (interactive) mode,
		// empty line (indent==0), and no parens open
		// or indentetion expected (if stdprompt == true, ovveride last cond)
		// consider forcing sentence closing NEWLINE if EOF
		if (partial && single_input && indent == 0 &&
				parens == 0  && (stdprompt || !expect_indent)) {
			//System.out.println("force newline");
			//backup a character!
			// - input_stream.backup(1); -
			SwitchTo(MAYBE_FORCE_NEWLINE_IF_EOF);
		} else
			indenting(0);
	}
}

<INDENTATION_UNCHANGED> SKIP : {
	<""> : DEFAULT
}

<INDENTING> TOKEN : {
	<DEDENT: ""> {
		if (indent > indentation[level]) {
			level++;
			indentation[level] = indent;
			matchedToken.kind=INDENT;
			matchedToken.image = "";
			//for (int i=0;i<indent;i++) matchedToken.image+=" ";
			matchedToken.length=0;
		} else if (level > 0) {
			Token t = matchedToken;
			level -= 1;
			while (level > 0 && indent < indentation[level]) {
				level--;
				t = addDedent(t);
			}
			if (indent != indentation[level]) {
				throw new TokenMgrError("inconsistent dedent",0);//TODO
			}
			t.next = null;
		}
	} : DEFAULT
}

<UNREACHABLE> TOKEN : {
	< INDENT:"<INDENT>">
//|     < DEDENT:"<DEDENT>">
}


<DEFAULT> SPECIAL_TOKEN: /* COMMENTS */ {
	<TRAILING_COMMENT: "#" (~["\n","\r"])* >
}

<INDENTING, INDENTATION_UNCHANGED> SPECIAL_TOKEN: /* COMMENTS */ {
	<SINGLE_LINE_COMMENT: "#" (~["\n","\r"])* ("\r\n" | "\n" | "\r")> {
		indenting(0);
	}
}


TOKEN : /* SEPARATORS */ {
	< LPAREN: "(" > {parens++;}
	|  < RPAREN: ")" > {parens--;}
	|  < LBRACE: "{" > {parens++;}
	|  < RBRACE: "}" > {parens--;}
	|  < LBRACKET: "[" > {parens++;}
	|  < RBRACKET: "]" > {parens--;}
	|  < SEMICOLON: ";" >
	|  < COMMA: "," >
	|  < DOT: "." >
	|  < COLON: ":" >
}


TOKEN : /* OPERATORS */ {
	< PLUS: "+" >
	|  < MINUS: "-" >
	|  < MULTIPLY: "*" >
	|  < DIVIDE: "/" >
	|  < FLOORDIVIDE: "//" >
	|  < POWER: "**" >
	|  < LSHIFT: "<<" >
	|  < RSHIFT: ">>" >
	|  < MODULO: "%" >
	|  < NOT: "~" >
	|  < XOR: "^" >
	|  < OR: "|" >
	|  < AND: "&" >
	|  < EQUAL: "=" >
	|  < GREATER: ">" >
	|  < LESS: "<" >
	|  < EQEQUAL: "==" >
	|  < EQLESS: "<=" >
	|  < EQGREATER: ">=" >
	|  < LESSGREATER: "<>" >
	|  < NOTEQUAL: "!=" >
	|  < PLUSEQ: "+=" >
	|  < MINUSEQ: "-=" >
	|  < MULTIPLYEQ: "*=" >
	|  < DIVIDEEQ: "/=" >
	|  < FLOORDIVIDEEQ: "//=" >
	|  < MODULOEQ: "%=" >
	|  < ANDEQ: "&=" >
	|  < OREQ: "|=" >
	|  < XOREQ: "^=" >
	|  < LSHIFTEQ: "<<=" >
	|  < RSHIFTEQ: ">>=" >
	|  < POWEREQ: "**=" >
}

TOKEN : /* KEYWORDS */ {
	< OR_BOOL: "or" >
	|  < AND_BOOL: "and" >
	|  < NOT_BOOL: "not" >
	|  < IS: "is" >
	|  < IN: "in" >
	|  < LAMBDA: "lambda" >
	|  < IF: "if" >
	|  < ELSE: "else" >
	|  < ELIF: "elif" >
	|  < WHILE: "while" >
	|  < FOR: "for" >
	|  < TRY: "try" >
	|  < EXCEPT: "except" >
	|  < DEF: "def" >
	|  < CLASS: "class" >
	|  < FINALLY: "finally" >
	|  < PRINT: "print" >
	|  < PASS: "pass" >
	|  < BREAK: "break" >
	|  < CONTINUE: "continue" >
	|  < RETURN: "return" >
	|  < YIELD: "yield" >
	|  < IMPORT: "import" >
	|  < FROM: "from" >
	|  < DEL: "del" >
	|  < RAISE: "raise" >
	|  < GLOBAL: "global" >
	|  < EXEC: "exec" >
	|  < ASSERT: "assert" >
	|  < AS: "as" >
}


TOKEN : /* Python identifiers */ {
	< NAME: <LETTER> (<LETTER> | <DIGIT>)* >
	|  < #LETTER: ["_","a"-"z","A"-"Z"] >
}

TOKEN : /* Numeric literals */ {
	< DECNUMBER: ["1"-"9"] (["0"-"9"])* (["l", "L"])? | "0" >
	|  < HEXNUMBER: "0" ["x","X"] (["0"-"9","a"-"f","A"-"F"])+ (["l","L"])? >
	|  < OCTNUMBER: "0" (["0"-"7"])* (["l","L"])? >
	|  < FLOAT: (["0"-"9"])+ "." (["0"-"9"])* (<EXPONENT>)?
		| "." (["0"-"9"])+ (<EXPONENT>)?
		| (["0"-"9"])+ <EXPONENT> >
	|  < COMPLEX: (<DECNUMBER> | <FLOAT> | "0" <DECNUMBER> ) ["j", "J"] >
	|  < #EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+ >
	|  < #DIGIT: ["0" - "9"] >
}

/*TOKEN : { <STRING: (["r", "R"])? ["'", "\"", "'''", "\"\"\""] >
    {
        int nquotes = matchedToken.image.length() > 2 ? 3 : 1;
        char quote = matchedToken.image.charAt(matchedToken.image.length()-1);

    }
}*/


MORE : /* Strings */ {
	< (["u", "U"]) (["r", "R"])? "'" > :  IN_USTRING11
	|  < (["u", "U"]) (["r", "R"])? "\"" > :  IN_USTRING21
	|  < (["u", "U"]) (["r", "R"])? "'''" > :  IN_USTRING13
	|  < (["u", "U"]) (["r", "R"])? "\"\"\"" > :  IN_USTRING23
	|  < (["r", "R"])? "'" > :  IN_STRING11
	|  < (["r", "R"])? "\"" > :  IN_STRING21
	|  < (["r", "R"])? "'''" > :  IN_STRING13
	|  < (["r", "R"])? "\"\"\"" > :  IN_STRING23
}

<IN_STRING11> TOKEN : { <SINGLE_STRING: "'"> {
    matchedToken.image = image.toString(); } : DEFAULT}
<IN_STRING21> TOKEN : { <SINGLE_STRING2: "\""> {
    matchedToken.image = image.toString(); } : DEFAULT}
<IN_STRING13> TOKEN : { <TRIPLE_STRING: "'''"> {
    matchedToken.image = image.toString(); } : DEFAULT}
<IN_STRING23> TOKEN : { <TRIPLE_STRING2: "\"\"\""> {
    matchedToken.image = image.toString(); } : DEFAULT}

<IN_USTRING11> TOKEN : { <SINGLE_USTRING: "'"> {
    matchedToken.image = image.toString(); } : DEFAULT}
<IN_USTRING21> TOKEN : { <SINGLE_USTRING2: "\""> {
    matchedToken.image = image.toString(); } : DEFAULT}
<IN_USTRING13> TOKEN : { <TRIPLE_USTRING: "'''"> {
    matchedToken.image = image.toString(); } : DEFAULT}
<IN_USTRING23> TOKEN : { <TRIPLE_USTRING2: "\"\"\""> {
    matchedToken.image = image.toString(); } : DEFAULT}

<IN_STRING11> MORE: {
	<"\\\r\n">           { image.setLength(image.length()-3); } : IN_STRING1NLC
	|  <("\\" ("\n"|"\r"))> { image.setLength(image.length()-2); } : IN_STRING1NLC
}

<IN_STRING21> MORE: {
	<"\\\r\n">           { image.setLength(image.length()-3); } : IN_STRING2NLC
	|  <("\\" ("\n"|"\r"))> { image.setLength(image.length()-2); } : IN_STRING2NLC
}

<IN_USTRING11> MORE: {
	<"\\\r\n">           { image.setLength(image.length()-3); } : IN_USTRING1NLC
	|  <("\\" ("\n"|"\r"))> { image.setLength(image.length()-2); } : IN_USTRING1NLC
}

<IN_USTRING21> MORE: {
	<"\\\r\n">           { image.setLength(image.length()-3); } : IN_USTRING2NLC
	|  <("\\" ("\n"|"\r"))> { image.setLength(image.length()-2); } : IN_USTRING2NLC
}

<IN_STRING1NLC> MORE: {
	<""> : IN_STRING11
}

<IN_STRING2NLC> MORE: {
	<""> : IN_STRING21
}

<IN_USTRING1NLC> MORE: {
	<""> : IN_USTRING11
}

<IN_USTRING2NLC> MORE: {
	<""> : IN_USTRING21
}

<IN_STRING11, IN_USTRING11> MORE: {
	<("\\" ("\\"|"'")) | ~["\n","\r"]>
}

<IN_STRING21, IN_USTRING21> MORE: {
	<("\\" ("\\"|"\"")) | ~["\n","\r"]>
}

<IN_STRING13, IN_STRING23, IN_USTRING13, IN_USTRING23> MORE: {
	<"\r\n"> {
		int l = image.length();
		image.setLength(l-1);
		image.setCharAt(l-2, '\n');
	}
	|  <"\n">
	|  <"\r"> { image.setCharAt(image.length()-1, '\n'); }
	|  <~["\n","\r"]>
	|  <"\\" ~["\n","\r"]>
}
FSTInfo file_input(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=stmt(inTerminal){ replaceName(n);})* <EOF> {return productionEndNonTerminal("file_input","-","-");}

 )  }

FSTInfo parameters(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"(" [n=varargslist(true){ replaceName("varargslist", n);}{ replaceName(n);}] ")" {return productionEndTerminal("parameters","-","{varargslist}","Replacement",first,token);}

 )  }

FSTInfo varargslist(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=defaultarg(true){ replaceName(n);} (LOOKAHEAD(2) "," n=defaultarg(true){ replaceName(n);})* [LOOKAHEAD(3) "," n=ExtraArgList(true){ replaceName(n);}] [LOOKAHEAD(2) "," n=ExtraKeywordList(true){ replaceName(n);}] ["," ] {return productionEndTerminal("varargslist1","-","{TOSTRING}","Replacement",first,token);}
 |
	LOOKAHEAD(2) n=ExtraArgList(true){ replaceName(n);} ["," n=ExtraKeywordList(true){ replaceName(n);}] {return productionEndTerminal("varargslist2","-","{TOSTRING}","Replacement",first,token);}
 |
	n=ExtraKeywordList(true){ replaceName(n);} {return productionEndTerminal("varargslist3","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo ExtraArgList(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*" n=Name(true){ replaceName(n);} {return productionEndTerminal("ExtraArgList","-","-","Replacement",first,token);}

 )  }

FSTInfo ExtraKeywordList(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=power(true){ replaceName(n);} n=Name(true){ replaceName(n);} {return productionEndTerminal("ExtraKeywordList","-","-","Replacement",first,token);}

 )  }

FSTInfo defaultarg(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=fpdef(true){ replaceName(n);} ["=" n=test(true){ replaceName(n);}] {return productionEndTerminal("defaultarg","-","-","Replacement",first,token);}

 )  }

FSTInfo fpdef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Name(true){ replaceName(n);} {return productionEndTerminal("fpdef1","-","-","Replacement",first,token);}
 |
	"(" n=fplist(true){ replaceName(n);} ")" {return productionEndTerminal("fpdef2","-","-","Replacement",first,token);}

 )  }

FSTInfo fplist(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=fpdef(true){ replaceName(n);} (LOOKAHEAD(2) "," n=fpdef(true){ replaceName(n);})* ["," ] {return productionEndTerminal("fplist","-","-","Replacement",first,token);}

 )  }

FSTInfo stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=simple_stmt(inTerminal){ replaceName(n);} {return productionEndNonTerminal("stmt1","-","-");}
 |
	n=compound_stmt(inTerminal){ replaceName(n);} {return productionEndNonTerminal("stmt2","-","-");}

 )  }

FSTInfo simple_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=small_stmt(true){ replaceName(n);} (LOOKAHEAD(2) ";" n=small_stmt(true){ replaceName(n);})* [";" ] <NEWLINE> {return productionEndTerminal("simple_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo small_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=expr_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt1","-","-","Replacement",first,token);}
 |
	n=print_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt2","-","-","Replacement",first,token);}
 |
	n=del_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt3","-","-","Replacement",first,token);}
 |
	n=pass_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt4","-","-","Replacement",first,token);}
 |
	n=flow_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt5","-","-","Replacement",first,token);}
 |
	n=import_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt6","-","-","Replacement",first,token);}
 |
	n=global_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt7","-","-","Replacement",first,token);}
 |
	n=exec_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt8","-","-","Replacement",first,token);}
 |
	n=assert_stmt(true){ replaceName(n);} {return productionEndTerminal("small_stmt9","-","-","Replacement",first,token);}

 )  }

FSTInfo expr_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=SmartTestList(true){ replaceName(n);} n=expr_stmtEnd(true){ replaceName(n);} {return productionEndTerminal("expr_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo expr_stmtEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<PLUSEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd1","-","-","Replacement",first,token);}
 |
	<MINUSEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd2","-","-","Replacement",first,token);}
 |
	<MULTIPLYEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd3","-","-","Replacement",first,token);}
 |
	<DIVIDEEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd4","-","-","Replacement",first,token);}
 |
	<FLOORDIVIDEEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd5","-","-","Replacement",first,token);}
 |
	<MODULOEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd6","-","-","Replacement",first,token);}
 |
	<ANDEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd7","-","-","Replacement",first,token);}
 |
	<OREQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd8","-","-","Replacement",first,token);}
 |
	<XOREQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd9","-","-","Replacement",first,token);}
 |
	<LSHIFTEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd10","-","-","Replacement",first,token);}
 |
	<RSHIFTEQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd11","-","-","Replacement",first,token);}
 |
	<POWEREQ> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("expr_stmtEnd12","-","-","Replacement",first,token);}
 |
	("=" n=SmartTestList(true){ replaceName(n);})* {return productionEndTerminal("expr_stmtEnd13","-","-","Replacement",first,token);}

 )  }

FSTInfo print_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) <PRINT> <RSHIFT> n=test(true){ replaceName(n);} [n=print_stmtEndP(true){ replaceName(n);}] {return productionEndTerminal("print_stmt1","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(2) <PRINT> n=print_stmtEndA(true){ replaceName(n);} {return productionEndTerminal("print_stmt2","-","-","Replacement",first,token);}
 |
	<PRINT> {return productionEndTerminal("print_stmt3","-","-","Replacement",first,token);}

 )  }

FSTInfo print_stmtEndP(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(LOOKAHEAD(2) "," n=test(true){ replaceName(n);})+ ["," ] {return productionEndTerminal("print_stmtEndP","-","-","Replacement",first,token);}

 )  }

FSTInfo print_stmtEndA(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} (LOOKAHEAD(2) "," n=test(true){ replaceName(n);})* ["," ] {return productionEndTerminal("print_stmtEndA","-","-","Replacement",first,token);}

 )  }

FSTInfo del_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<DEL> n=exprlist(true){ replaceName(n);} {return productionEndTerminal("del_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo pass_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<PASS> {return productionEndTerminal("pass_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo flow_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<BREAK> {return productionEndTerminal("flow_stmt1","-","-","Replacement",first,token);}
 |
	<CONTINUE> {return productionEndTerminal("flow_stmt2","-","-","Replacement",first,token);}
 |
	n=return_stmt(true){ replaceName(n);} {return productionEndTerminal("flow_stmt3","-","-","Replacement",first,token);}
 |
	n=yield_stmt(true){ replaceName(n);} {return productionEndTerminal("flow_stmt4","-","-","Replacement",first,token);}
 |
	n=raise_stmt(true){ replaceName(n);} {return productionEndTerminal("flow_stmt5","-","-","Replacement",first,token);}

 )  }

FSTInfo return_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<RETURN> [n=SmartTestList(true){ replaceName(n);}] {return productionEndTerminal("return_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo yield_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<YIELD> n=SmartTestList(true){ replaceName(n);} {return productionEndTerminal("yield_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo raise_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<RAISE> [n=raise_stmt_end(true){ replaceName(n);}] {return productionEndTerminal("raise_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo raise_stmt_end(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} ["," n=testcommatest(true){ replaceName(n);}] {return productionEndTerminal("raise_stmt_end","-","-","Replacement",first,token);}

 )  }

FSTInfo testcommatest(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} ["," n=test(true){ replaceName(n);}] {return productionEndTerminal("testcommatest","-","-","Replacement",first,token);}

 )  }

FSTInfo import_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IMPORT> n=Import(true){ replaceName(n);} {return productionEndTerminal("import_stmt1","-","-","Replacement",first,token);}
 |
	<FROM> n=ImportFrom(true){ replaceName(n);} {return productionEndTerminal("import_stmt2","-","-","Replacement",first,token);}

 )  }

FSTInfo Import(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=dotted_as_name(true){ replaceName(n);} ("," n=dotted_as_name(true){ replaceName(n);})* {return productionEndTerminal("Import","-","-","Replacement",first,token);}

 )  }

FSTInfo ImportFrom(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=dotted_name(true){ replaceName(n);} <IMPORT> n=ImportFromEnd(true){ replaceName(n);} {return productionEndTerminal("ImportFrom","-","-","Replacement",first,token);}

 )  }

FSTInfo ImportFromEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*"  {return productionEndTerminal("ImportFromEnd1","-","-","Replacement",first,token);}
 |
	n=import_as_name(true){ replaceName(n);} ("," n=import_as_name(true){ replaceName(n);})* {return productionEndTerminal("ImportFromEnd2","-","-","Replacement",first,token);}

 )  }

FSTInfo dotted_as_name(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=dotted_name(true){ replaceName(n);} ["as" n=Name(true){ replaceName(n);}] {return productionEndTerminal("dotted_as_name","-","-","Replacement",first,token);}

 )  }

FSTInfo dotted_name(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=AnyName(true){ replaceName(n);} ("." n=AnyName(true){ replaceName(n);})* {return productionEndTerminal("dotted_name","-","-","Replacement",first,token);}

 )  }

FSTInfo import_as_name(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=AnyName(true){ replaceName(n);} ["as" n=Name(true){ replaceName(n);}] {return productionEndTerminal("import_as_name","-","-","Replacement",first,token);}

 )  }

FSTInfo global_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<GLOBAL> n=Name(true){ replaceName(n);} ("," n=Name(true){ replaceName(n);})* {return productionEndTerminal("global_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo exec_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"exec" n=expr(true){ replaceName(n);} ["in" n=exec_stmt_end(true){ replaceName(n);}] {return productionEndTerminal("exec_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo exec_stmt_end(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} ["," n=test(true){ replaceName(n);}] {return productionEndTerminal("exec_stmt_end","-","-","Replacement",first,token);}

 )  }

FSTInfo assert_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"assert" n=test(true){ replaceName(n);} ["," n=test(true){ replaceName(n);}] {return productionEndTerminal("assert_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo if_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"if" n=test(true){ replaceName(n);} ":" n=suite(true){ replaceName(n);} (n=elif_stmt(true){ replaceName(n);})* ["else" ":" n=suite(true){ replaceName(n);}] {return productionEndTerminal("if_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo elif_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"elif" n=test(true){ replaceName(n);} ":" n=suite(true){ replaceName(n);} {return productionEndTerminal("elif_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo while_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"while" n=test(true){ replaceName(n);} ":" n=suite(true){ replaceName(n);} ["else" ":" n=suite(true){ replaceName(n);}] {return productionEndTerminal("while_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo for_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"for" n=exprlist(true){ replaceName(n);} "in" n=SmartTestList(true){ replaceName(n);} ":" n=suite(true){ replaceName(n);} ["else" ":" n=suite(true){ replaceName(n);}] {return productionEndTerminal("for_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo try_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"try" ":" n=suite(true){ replaceName(n);} n=tryEnd(true){ replaceName(n);} {return productionEndTerminal("try_stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo tryEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=except_clause(true){ replaceName(n);})+ ["else" ":" n=suite(true){ replaceName(n);}] {return productionEndTerminal("tryEnd1","-","-","Replacement",first,token);}
 |
	"finally" ":" n=suite(true){ replaceName(n);} {return productionEndTerminal("tryEnd2","-","-","Replacement",first,token);}

 )  }

FSTInfo except_clause(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"except" [n=testcommatest(true){ replaceName(n);}] ":" n=suite(true){ replaceName(n);} {return productionEndTerminal("except_clause","-","-","Replacement",first,token);}

 )  }

FSTInfo test(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=lambdef(true){ replaceName(n);} {return productionEndTerminal("test1","-","-","Replacement",first,token);}
 |
	n=and_test(true){ replaceName(n);} ("or" n=and_test(true){ replaceName(n);})* {return productionEndTerminal("test2","-","-","Replacement",first,token);}

 )  }

FSTInfo and_test(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=not_test(true){ replaceName(n);} ("and" n=not_test(true){ replaceName(n);})* {return productionEndTerminal("and_test","-","-","Replacement",first,token);}

 )  }

FSTInfo not_test(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"not" n=not_test(true){ replaceName(n);} {return productionEndTerminal("not_test1","-","-","Replacement",first,token);}
 |
	n=comparison(true){ replaceName(n);} {return productionEndTerminal("not_test2","-","-","Replacement",first,token);}

 )  }

FSTInfo comparison(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=expr(true){ replaceName(n);} (n=compEnd(true){ replaceName(n);})* {return productionEndTerminal("comparison","-","-","Replacement",first,token);}

 )  }

FSTInfo compEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=comp_op(true){ replaceName(n);} n=expr(true){ replaceName(n);} {return productionEndTerminal("compEnd","-","-","Replacement",first,token);}

 )  }

FSTInfo comp_op(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<LESS> {return productionEndTerminal("comp_op1","-","-","Replacement",first,token);}
 |
	<GREATER> {return productionEndTerminal("comp_op2","-","-","Replacement",first,token);}
 |
	<EQEQUAL> {return productionEndTerminal("comp_op3","-","-","Replacement",first,token);}
 |
	<EQGREATER> {return productionEndTerminal("comp_op4","-","-","Replacement",first,token);}
 |
	<EQLESS> {return productionEndTerminal("comp_op5","-","-","Replacement",first,token);}
 |
	<LESSGREATER> {return productionEndTerminal("comp_op6","-","-","Replacement",first,token);}
 |
	<NOTEQUAL> {return productionEndTerminal("comp_op7","-","-","Replacement",first,token);}
 |
	<IN> {return productionEndTerminal("comp_op8","-","-","Replacement",first,token);}
 |
	"not" <IN> {return productionEndTerminal("comp_op9","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(2) <IS> "not" {return productionEndTerminal("comp_op10","-","-","Replacement",first,token);}
 |
	<IS> {return productionEndTerminal("comp_op11","-","-","Replacement",first,token);}

 )  }

FSTInfo expr(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=xor_expr(true){ replaceName(n);} ("|" n=xor_expr(true){ replaceName(n);})* {return productionEndTerminal("expr","-","-","Replacement",first,token);}

 )  }

FSTInfo xor_expr(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=and_expr(true){ replaceName(n);} ("^" n=and_expr(true){ replaceName(n);})* {return productionEndTerminal("xor_expr","-","-","Replacement",first,token);}

 )  }

FSTInfo and_expr(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=shift_expr(true){ replaceName(n);} ("&" n=shift_expr(true){ replaceName(n);})* {return productionEndTerminal("and_expr","-","-","Replacement",first,token);}

 )  }

FSTInfo shift_expr(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=arith_expr(true){ replaceName(n);} (n=shift_exprEnd(true){ replaceName(n);})* {return productionEndTerminal("shift_expr","-","-","Replacement",first,token);}

 )  }

FSTInfo shift_exprEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"<<" n=arith_expr(true){ replaceName(n);} {return productionEndTerminal("shift_exprEnd1","-","-","Replacement",first,token);}
 |
	">>" n=arith_expr(true){ replaceName(n);} {return productionEndTerminal("shift_exprEnd2","-","-","Replacement",first,token);}

 )  }

FSTInfo arith_expr(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=term(true){ replaceName(n);} (n=arith_exprEnd(true){ replaceName(n);})* {return productionEndTerminal("arith_expr","-","-","Replacement",first,token);}

 )  }

FSTInfo arith_exprEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<PLUS> n=term(true){ replaceName(n);} {return productionEndTerminal("arith_exprEnd1","-","-","Replacement",first,token);}
 |
	<MINUS> n=term(true){ replaceName(n);} {return productionEndTerminal("arith_exprEnd2","-","-","Replacement",first,token);}

 )  }

FSTInfo term(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=factor(true){ replaceName(n);} (n=termEnd(true){ replaceName(n);})* {return productionEndTerminal("term","-","-","Replacement",first,token);}

 )  }

FSTInfo termEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*" n=factor(true){ replaceName(n);} {return productionEndTerminal("termEnd1","-","-","Replacement",first,token);}
 |
	<DIVIDE> n=factor(true){ replaceName(n);} {return productionEndTerminal("termEnd2","-","-","Replacement",first,token);}
 |
	<FLOORDIVIDE> n=factor(true){ replaceName(n);} {return productionEndTerminal("termEnd3","-","-","Replacement",first,token);}
 |
	<MODULO> n=factor(true){ replaceName(n);} {return productionEndTerminal("termEnd4","-","-","Replacement",first,token);}

 )  }

FSTInfo factor(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<PLUS> n=factor(true){ replaceName(n);} {return productionEndTerminal("factor1","-","-","Replacement",first,token);}
 |
	<MINUS> n=factor(true){ replaceName(n);} {return productionEndTerminal("factor2","-","-","Replacement",first,token);}
 |
	<NOT> n=factor(true){ replaceName(n);} {return productionEndTerminal("factor3","-","-","Replacement",first,token);}
 |
	n=powerfactor(true){ replaceName(n);} {return productionEndTerminal("factor4","-","-","Replacement",first,token);}

 )  }

FSTInfo powerfactor(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=atomtrailer(true){ replaceName(n);} (LOOKAHEAD(2) "**" n=factor(true){ replaceName(n);})* {return productionEndTerminal("powerfactor","-","-","Replacement",first,token);}

 )  }

FSTInfo atomtrailer(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=atom(true){ replaceName(n);} (n=atomtrailerEnd(true){ replaceName(n);})* {return productionEndTerminal("atomtrailer","-","-","Replacement",first,token);}

 )  }

FSTInfo atomtrailerEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "(" ")"  {return productionEndTerminal("atomtrailerEnd1","-","-","Replacement",first,token);}
 |
	"(" n=arglist(true){ replaceName(n);} ")" {return productionEndTerminal("atomtrailerEnd2","-","-","Replacement",first,token);}
 |
	"[" n=subscriptlist(true){ replaceName(n);} "]" {return productionEndTerminal("atomtrailerEnd3","-","-","Replacement",first,token);}
 |
	<DOT> n=AnyName(true){ replaceName(n);} {return productionEndTerminal("atomtrailerEnd4","-","-","Replacement",first,token);}

 )  }

FSTInfo atom(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "(" ")"  {return productionEndTerminal("atom1","-","-","Replacement",first,token);}
 |
	"(" [n=SmartTestList(true){ replaceName(n);}] ")" {return productionEndTerminal("atom2","-","-","Replacement",first,token);}
 |
	<LBRACKET> [n=listmaker(true){ replaceName(n);}] "]" {return productionEndTerminal("atom3","-","-","Replacement",first,token);}
 |
	"{" [n=dictmaker(true){ replaceName(n);}] "}" {return productionEndTerminal("atom4","-","-","Replacement",first,token);}
 |
	"`" n=SmartTestList(true){ replaceName(n);} "`" {return productionEndTerminal("atom5","-","-","Replacement",first,token);}
 |
	n=Name(true){ replaceName(n);} {return productionEndTerminal("atom6","-","-","Replacement",first,token);}
 |
	n=Number(true){ replaceName(n);} {return productionEndTerminal("atom7","-","-","Replacement",first,token);}
 |
	n=StringNode(true){ replaceName(n);} (n=StringNode(true){ replaceName(n);})* {return productionEndTerminal("atom8","-","-","Replacement",first,token);}

 )  }

FSTInfo lambdef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<LAMBDA> [n=varargslist(true){ replaceName(n);}] ":" n=test(true){ replaceName(n);} {return productionEndTerminal("lambdef","-","-","Replacement",first,token);}

 )  }

FSTInfo subscriptlist(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=subscript(true){ replaceName(n);} (LOOKAHEAD(2) "," n=subscript(true){ replaceName(n);})* ["," ] {return productionEndTerminal("subscriptlist","-","-","Replacement",first,token);}

 )  }

FSTInfo subscript(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<DOT> <DOT> <DOT> {return productionEndTerminal("subscript1","-","-","Replacement",first,token);}
 |
	n=test(true){ replaceName(n);} [n=slice(true){ replaceName(n);}] {return productionEndTerminal("subscript2","-","-","Replacement",first,token);}
 |
	n=slice(true){ replaceName(n);} {return productionEndTerminal("subscript3","-","-","Replacement",first,token);}

 )  }

FSTInfo slice(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=ct(true){ replaceName(n);} [n=ct(true){ replaceName(n);}] {return productionEndTerminal("slice","-","-","Replacement",first,token);}

 )  }

FSTInfo ct(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	":" [n=test(true){ replaceName(n);}] {return productionEndTerminal("ct","-","-","Replacement",first,token);}

 )  }

FSTInfo exprlist(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=expr(true){ replaceName(n);} (LOOKAHEAD(2) "," n=expr(true){ replaceName(n);})* ["," ] {return productionEndTerminal("exprlist","-","-","Replacement",first,token);}

 )  }

FSTInfo SmartTestList(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} (LOOKAHEAD(2) "," n=test(true){ replaceName(n);})* ["," ] {return productionEndTerminal("SmartTestList","-","-","Replacement",first,token);}

 )  }

FSTInfo testlist(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} (LOOKAHEAD(2) "," n=test(true){ replaceName(n);})* ["," ] {return productionEndTerminal("testlist","-","-","Replacement",first,token);}

 )  }

FSTInfo dictmaker(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} ":" n=test(true){ replaceName(n);} (LOOKAHEAD(2) n=dictInt(true){ replaceName(n);})* ["," ] {return productionEndTerminal("dictmaker","-","-","Replacement",first,token);}

 )  }

FSTInfo dictInt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"," n=test(true){ replaceName(n);} ":" n=test(true){ replaceName(n);} {return productionEndTerminal("dictInt","-","-","Replacement",first,token);}

 )  }

FSTInfo listmaker(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=test(true){ replaceName(n);} n=listmakerEnd(true){ replaceName(n);} {return productionEndTerminal("listmaker","-","-","Replacement",first,token);}

 )  }

FSTInfo listmakerEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(n=list_for(true){ replaceName(n);})+ {return productionEndTerminal("listmakerEnd1","-","-","Replacement",first,token);}
 |
	(LOOKAHEAD(2) "," n=test(true){ replaceName(n);})* ["," ] {return productionEndTerminal("listmakerEnd2","-","-","Replacement",first,token);}

 )  }

FSTInfo list_for(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"for" n=exprlist(true){ replaceName(n);} "in" n=SmartTestList(true){ replaceName(n);} (n=list_if(true){ replaceName(n);})* {return productionEndTerminal("list_for","-","-","Replacement",first,token);}

 )  }

FSTInfo list_if(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"if" n=test(true){ replaceName(n);} {return productionEndTerminal("list_if","-","-","Replacement",first,token);}

 )  }

FSTInfo compound_stmt(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=if_stmt(true){ replaceName(n);} {return productionEndTerminal("compound_stmt1","-","-","Replacement",first,token);}
 |
	n=while_stmt(true){ replaceName(n);} {return productionEndTerminal("compound_stmt2","-","-","Replacement",first,token);}
 |
	n=for_stmt(true){ replaceName(n);} {return productionEndTerminal("compound_stmt3","-","-","Replacement",first,token);}
 |
	n=try_stmt(true){ replaceName(n);} {return productionEndTerminal("compound_stmt4","-","-","Replacement",first,token);}
 |
	n=funcdef(true){ replaceName("funcdef", n);}{ replaceName(n);} {return productionEndTerminal("FunctionDefinition","{funcdef}","{funcdef}","JavaMethodOverriding",first,token);}
 |
	n=classdef(inTerminal){ replaceName(n);} {return productionEndNonTerminal("ClassDefinition","-","-");}

 )  }

FSTInfo funcdef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"def" t=<NAME>{ replaceName(new FSTInfo("<NAME>",t.image));} n=parameters(true){ replaceName("parameters", n);}{ replaceName(n);} ":" n=suite(true){ replaceName(n);} {return productionEndTerminal("funcdef","-","{<NAME>}({parameters})","Replacement",first,token);}

 )  }

FSTInfo classdef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"class" t=<NAME>{ replaceName(new FSTInfo("<NAME>",t.image));} ["(" n=testlist(inTerminal){ replaceName(n);} ")"] ":" n=suite(inTerminal){ replaceName(n);} {return productionEndNonTerminal("classdef","{<NAME>}","{<NAME>}");}

 )  }

FSTInfo FieldDeclaration(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=Field(true){ replaceName("Field", n);}{ replaceName(n);} (";" n=Field(true){ replaceName("Field", n);}{ replaceName(n);})* {return productionEndTerminal("FieldDeclaration","-","{Field}","Replacement",first,token);}

 )  }

FSTInfo Field(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	t=<NAME>{ replaceName(new FSTInfo("<NAME>",t.image));} "=" n=expr(true){ replaceName(n);} {return productionEndTerminal("Field","-","{<NAME>}","Replacement",first,token);}

 )  }

FSTInfo suite(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<NEWLINE>  {token_source.expect_indent = true;} <INDENT>  {token_source.expect_indent = false;} (n=stmt(inTerminal){ replaceName(n);})+ <DEDENT> {return productionEndNonTerminal("suite","-","-");}

 )  }

FSTInfo arglist(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=normalargs(true){ replaceName(n);} [n=arglist1End(true){ replaceName(n);}] {return productionEndTerminal("arglist1","-","-","Replacement",first,token);}
 |
	[LOOKAHEAD(2) n=arglist1EndEnd(true){ replaceName(n);}] {return productionEndTerminal("arglist2","-","-","Replacement",first,token);}

 )  }

FSTInfo arglist1End(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"," [LOOKAHEAD(2) n=arglist1EndEnd(true){ replaceName(n);}] {return productionEndTerminal("arglist1End","-","-","Replacement",first,token);}

 )  }

FSTInfo arglist1EndEnd(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) n=ExtraArgValueList(true){ replaceName(n);} ["," n=ExtraKeywordValueList(true){ replaceName(n);}] {return productionEndTerminal("arglist1EndEnd1","-","-","Replacement",first,token);}
 |
	n=ExtraKeywordValueList(true){ replaceName(n);} {return productionEndTerminal("arglist1EndEnd2","-","-","Replacement",first,token);}

 )  }

FSTInfo normalargs(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=argument(true){ replaceName(n);} (LOOKAHEAD(2) "," n=argument(true){ replaceName(n);})* {return productionEndTerminal("normalargs","-","-","Replacement",first,token);}

 )  }

FSTInfo ExtraArgValueList(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"*" n=test(true){ replaceName(n);} {return productionEndTerminal("ExtraArgValueList","-","-","Replacement",first,token);}

 )  }

FSTInfo ExtraKeywordValueList(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=power(true){ replaceName(n);} n=test(true){ replaceName(n);} {return productionEndTerminal("ExtraKeywordValueList","-","-","Replacement",first,token);}

 )  }

FSTInfo power(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"**"  {return productionEndTerminal("power1","-","-","Replacement",first,token);}
 |
	"*" "*"  {return productionEndTerminal("power2","-","-","Replacement",first,token);}

 )  }

FSTInfo argument(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	[LOOKAHEAD(2) n=AnyName(true){ replaceName(n);} "="] n=test(true){ replaceName(n);} {return productionEndTerminal("argument","-","-","Replacement",first,token);}

 )  }

FSTInfo Number(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<HEXNUMBER> {return productionEndTerminal("Number1","-","-","Replacement",first,token);}
 |
	<OCTNUMBER> {return productionEndTerminal("Number2","-","-","Replacement",first,token);}
 |
	<DECNUMBER> {return productionEndTerminal("Number3","-","-","Replacement",first,token);}
 |
	<FLOAT> {return productionEndTerminal("Number4","-","-","Replacement",first,token);}
 |
	<COMPLEX> {return productionEndTerminal("Number5","-","-","Replacement",first,token);}

 )  }

FSTInfo Complex(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<FLOAT> {return productionEndTerminal("Complex","-","-","Replacement",first,token);}

 )  }

FSTInfo Name(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<NAME> {return productionEndTerminal("Name1","-","-","Replacement",first,token);}
 |
	<AS> {return productionEndTerminal("Name2","-","-","Replacement",first,token);}

 )  }

FSTInfo StringNode(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<SINGLE_STRING> {return productionEndTerminal("StringNode1","-","-","Replacement",first,token);}
 |
	<SINGLE_STRING2> {return productionEndTerminal("StringNode2","-","-","Replacement",first,token);}
 |
	<TRIPLE_STRING> {return productionEndTerminal("StringNode3","-","-","Replacement",first,token);}
 |
	<TRIPLE_STRING2> {return productionEndTerminal("StringNode4","-","-","Replacement",first,token);}
 |
	<SINGLE_USTRING> {return productionEndTerminal("StringNode5","-","-","Replacement",first,token);}
 |
	<SINGLE_USTRING2> {return productionEndTerminal("StringNode6","-","-","Replacement",first,token);}
 |
	<TRIPLE_USTRING> {return productionEndTerminal("StringNode7","-","-","Replacement",first,token);}
 |
	<TRIPLE_USTRING2> {return productionEndTerminal("StringNode8","-","-","Replacement",first,token);}

 )  }

FSTInfo AnyName(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<NAME> {return productionEndTerminal("AnyName1","-","-","Replacement",first,token);}
 |
	"or"  {return productionEndTerminal("AnyName2","-","-","Replacement",first,token);}
 |
	"and"  {return productionEndTerminal("AnyName3","-","-","Replacement",first,token);}
 |
	"not"  {return productionEndTerminal("AnyName4","-","-","Replacement",first,token);}
 |
	<IS> {return productionEndTerminal("AnyName5","-","-","Replacement",first,token);}
 |
	<IN> {return productionEndTerminal("AnyName6","-","-","Replacement",first,token);}
 |
	<LAMBDA> {return productionEndTerminal("AnyName7","-","-","Replacement",first,token);}
 |
	<IF> {return productionEndTerminal("AnyName8","-","-","Replacement",first,token);}
 |
	<ELSE> {return productionEndTerminal("AnyName9","-","-","Replacement",first,token);}
 |
	<ELIF> {return productionEndTerminal("AnyName10","-","-","Replacement",first,token);}
 |
	<WHILE> {return productionEndTerminal("AnyName11","-","-","Replacement",first,token);}
 |
	<FOR> {return productionEndTerminal("AnyName12","-","-","Replacement",first,token);}
 |
	<TRY> {return productionEndTerminal("AnyName13","-","-","Replacement",first,token);}
 |
	<EXCEPT> {return productionEndTerminal("AnyName14","-","-","Replacement",first,token);}
 |
	<DEF> {return productionEndTerminal("AnyName15","-","-","Replacement",first,token);}
 |
	<CLASS> {return productionEndTerminal("AnyName16","-","-","Replacement",first,token);}
 |
	<FINALLY> {return productionEndTerminal("AnyName17","-","-","Replacement",first,token);}
 |
	<PRINT> {return productionEndTerminal("AnyName18","-","-","Replacement",first,token);}
 |
	<PASS> {return productionEndTerminal("AnyName19","-","-","Replacement",first,token);}
 |
	<BREAK> {return productionEndTerminal("AnyName20","-","-","Replacement",first,token);}
 |
	<CONTINUE> {return productionEndTerminal("AnyName21","-","-","Replacement",first,token);}
 |
	<RETURN> {return productionEndTerminal("AnyName22","-","-","Replacement",first,token);}
 |
	<YIELD> {return productionEndTerminal("AnyName23","-","-","Replacement",first,token);}
 |
	<IMPORT> {return productionEndTerminal("AnyName24","-","-","Replacement",first,token);}
 |
	<FROM> {return productionEndTerminal("AnyName25","-","-","Replacement",first,token);}
 |
	<DEL> {return productionEndTerminal("AnyName26","-","-","Replacement",first,token);}
 |
	<RAISE> {return productionEndTerminal("AnyName27","-","-","Replacement",first,token);}
 |
	<GLOBAL> {return productionEndTerminal("AnyName28","-","-","Replacement",first,token);}
 |
	<EXEC> {return productionEndTerminal("AnyName29","-","-","Replacement",first,token);}
 |
	<ASSERT> {return productionEndTerminal("AnyName30","-","-","Replacement",first,token);}
 |
	<AS> {return productionEndTerminal("AnyName31","-","-","Replacement",first,token);}

 )  }

