/* Generated By:JavaCC: Do not edit this line. JMLParserConstants.java */
package tmp.generated_jml_contract_composition;

public interface JMLParserConstants {

  int EOF = 0;
  int JML_MULTI_LINE_END = 8;
  int REG_MULTI_LINE_END = 9;
  int JML_AT = 10;
  int SINGLE_LINE_COMMENT = 11;
  int FORMAL_COMMENT = 15;
  int MULTI_LINE_COMMENT = 16;
  int ABSTRACT = 18;
  int ASSERT = 19;
  int BOOLEAN = 20;
  int BREAK = 21;
  int BYTE = 22;
  int CASE = 23;
  int CATCH = 24;
  int CHAR = 25;
  int CLASS = 26;
  int CONST = 27;
  int CONTINUE = 28;
  int _DEFAULT = 29;
  int DO = 30;
  int DOUBLE = 31;
  int ELSE = 32;
  int ENUM = 33;
  int EXTENDS = 34;
  int FALSE = 35;
  int FINAL = 36;
  int FINALLY = 37;
  int FLOAT = 38;
  int FOR = 39;
  int GOTO = 40;
  int IF = 41;
  int IMPLEMENTS = 42;
  int IMPORT = 43;
  int INSTANCEOF = 44;
  int INT = 45;
  int INTERFACE = 46;
  int LONG = 47;
  int NATIVE = 48;
  int NEW = 49;
  int NULL = 50;
  int PACKAGE = 51;
  int PRIVATE = 52;
  int PROTECTED = 53;
  int PUBLIC = 54;
  int RETURN = 55;
  int SHORT = 56;
  int STATIC = 57;
  int STRICTFP = 58;
  int SUPER = 59;
  int SWITCH = 60;
  int SYNCHRONIZED = 61;
  int THIS = 62;
  int THROW = 63;
  int THROWS = 64;
  int TRANSIENT = 65;
  int TRUE = 66;
  int TRY = 67;
  int VOID = 68;
  int VOLATILE = 69;
  int WHILE = 70;
  int ORIGINAL_SPEC = 71;
  int ORIGINAL_CASE = 72;
  int ORIGINAL_CLAUSE = 73;
  int ORIGINAL = 74;
  int HENCE_BY = 75;
  int HENCE_BY_REDUNDANTLY = 76;
  int MODEL = 77;
  int SPEC_PROTECTED = 78;
  int GHOST = 79;
  int PURE = 80;
  int INSTANCE = 81;
  int HELPER = 82;
  int UNINITIALIZED = 83;
  int JAVA_MATH = 84;
  int SPEC_JAVA_MATH = 85;
  int SPEC_SAFE_MATH = 86;
  int CODE_JAVA_MATH = 87;
  int CODE_SAFE_MATH = 88;
  int ALSO = 89;
  int SPEC_PUBLIC = 90;
  int SPEC_BIGINT_MATH = 91;
  int CODE_BIGINT_MATH = 92;
  int NON_NULL = 93;
  int NULLABLE = 94;
  int NULLABLE_BY_DEFAULT = 95;
  int EXTRACT = 96;
  int METHOD = 97;
  int CONSTRUCTOR = 98;
  int TYPE = 99;
  int IN = 100;
  int IN_REDUNDANTLY = 101;
  int INTO = 102;
  int MAPS = 103;
  int MAPS_REDUNDANTLY = 104;
  int STATIC_INITIALIZER = 105;
  int MAINTAINING = 106;
  int MAINTAINING_REDUNDANTLY = 107;
  int LOOP_INVARIANT = 108;
  int LOOP_INVARIANT_REDUNDANTLY = 109;
  int DECREASING = 110;
  int DECREASING_REDUNDANTLY = 111;
  int DECREASES = 112;
  int DECREASES_REDUNDANTLY = 113;
  int ASSUME = 114;
  int ASSUME_REDUNDANTLY = 115;
  int SET = 116;
  int REFINING = 117;
  int UNREACHABLE = 118;
  int DEBUG = 119;
  int HENCEBY = 120;
  int HENCEBY_REDUNDANTLY = 121;
  int INVARIANT = 122;
  int INVARIANT_REDUNDANTLY = 123;
  int CONSTRAINT = 124;
  int CONSTRAINT_REDUNDANTLY = 125;
  int EVERYTHING = 126;
  int SUCH_THAT = 127;
  int REPRESENTS = 128;
  int REPRESENTS_REDUNDANTLY = 129;
  int INITIALLY = 130;
  int READABLE = 131;
  int WRITABLE = 132;
  int MONITORS_FOR = 133;
  int CHOOSE = 134;
  int OR = 135;
  int CHOOSE_IF = 136;
  int ABRUPT_BEHAVIOR = 137;
  int ABRUPT_BEHAVIOUR = 138;
  int CONTINUES = 139;
  int CONTINUES_REDUNDANTLY = 140;
  int BREAKS = 141;
  int BREAKS_REDUNDANTLY = 142;
  int RETURNS = 143;
  int RETURNS_REDUNDANTLY = 144;
  int RESULT = 145;
  int OLD = 146;
  int PRE = 147;
  int NOT_ASSIGNED = 148;
  int NOT_MODIFIED = 149;
  int ONLY_ACCESSED = 150;
  int ONLY_CAPTURED = 151;
  int ONLY_CALLED = 152;
  int FRESH = 153;
  int REACH = 154;
  int DURATION = 155;
  int SPACE = 156;
  int WORKING_SPACE = 157;
  int NONNULLELEMENTS = 158;
  int TYPEOF = 159;
  int ELEMTYPE = 160;
  int LOCKSET = 161;
  int MAX = 162;
  int IS_INITIALIZED = 163;
  int INVARIANT_FOR = 164;
  int LBLNEG = 165;
  int FORALL = 166;
  int EXISTS = 167;
  int MIN = 168;
  int NUM_OF = 169;
  int PRODUCT = 170;
  int SUM = 171;
  int NOTHING = 172;
  int NOT_SPECIFIED = 173;
  int LBLPOS = 174;
  int ONLY_ASSIGNED = 175;
  int BEHAVIOR = 176;
  int BEHAVIOUR = 177;
  int NORMAL_BEHAVIOR = 178;
  int NORMAL_BEHAVIOUR = 179;
  int EXCEPTIONAL_BEHAVIOR = 180;
  int EXCEPTIONAL_BEHAVIOUR = 181;
  int SAME = 182;
  int REQUIRES = 183;
  int REQUIRES_REDUNDANTLY = 184;
  int PRE_REDUNDANTLY = 185;
  int ENSURES = 186;
  int POST = 187;
  int ENSURES_REDUNDANTLY = 188;
  int POST_REDUNDANTLY = 189;
  int SIGNALS = 190;
  int SIGNALS_REDUNDANTLY = 191;
  int EXSURES = 192;
  int EXSURES_REDUNDANTLY = 193;
  int SIGNALS_ONLY = 194;
  int SIGNALS_ONLY_REDUNDANTLY = 195;
  int DIVERGES = 196;
  int DIVERGES_REDUNDANTLY = 197;
  int WHEN = 198;
  int WHEN_REDUNDANTLY = 199;
  int ASSIGNABLE = 200;
  int ASSIGNABLE_REDUNDANTLY = 201;
  int MODIFIABLE = 202;
  int MODIFIABLE_REDUNDANTLY = 203;
  int CALLABLE = 204;
  int CALLABLE_REDUNDANTLY = 205;
  int MEASURED_BY = 206;
  int MEASURED_BY_REDUNDANTLY = 207;
  int CAPTURES = 208;
  int CAPTURES_REDUNDANTLY = 209;
  int WORKING_SPACE_REDUNDANTLY = 210;
  int DURATION_REDUNDANTLY = 211;
  int MODIFIES = 212;
  int MODIFIES_REDUNDANTLY = 213;
  int CODE = 214;
  int ASSERT_REDUNDANTLY = 215;
  int AXIOM = 216;
  int ACCESSIBLE = 217;
  int ACCESSIBLE_REDUNDANTLY = 218;
  int IMPLIES_THAT = 219;
  int FOR_EXAMPLE = 220;
  int EXCEPTIONAL_EXAMPLE = 221;
  int NORMAL_EXAMPLE = 222;
  int MODEL_PROGRAM = 223;
  int INTEGER_LITERAL = 224;
  int DECIMAL_LITERAL = 225;
  int HEX_LITERAL = 226;
  int OCTAL_LITERAL = 227;
  int FLOATING_POINT_LITERAL = 228;
  int EXPONENT = 229;
  int CHARACTER_LITERAL = 230;
  int STRING_LITERAL = 231;
  int BOOLEAN_LITERAL = 232;
  int IDENTIFIER = 233;
  int LETTER = 234;
  int DIGIT = 235;
  int LPAREN = 236;
  int RPAREN = 237;
  int LBRACE = 238;
  int RBRACE = 239;
  int LBRACKET = 240;
  int RBRACKET = 241;
  int SEMICOLON = 242;
  int COMMA = 243;
  int DOT = 244;
  int AT = 245;
  int ASSIGN = 246;
  int LT = 247;
  int BANG = 248;
  int TILDE = 249;
  int HOOK = 250;
  int COLON = 251;
  int EQ = 252;
  int LE = 253;
  int GE = 254;
  int NE = 255;
  int SC_OR = 256;
  int SC_AND = 257;
  int INCR = 258;
  int DECR = 259;
  int PLUS = 260;
  int MINUS = 261;
  int STAR = 262;
  int SLASH = 263;
  int BIT_AND = 264;
  int BIT_OR = 265;
  int XOR = 266;
  int REM = 267;
  int LSHIFT = 268;
  int PLUSASSIGN = 269;
  int MINUSASSIGN = 270;
  int STARASSIGN = 271;
  int SLASHASSIGN = 272;
  int ANDASSIGN = 273;
  int ORASSIGN = 274;
  int XORASSIGN = 275;
  int REMASSIGN = 276;
  int LSHIFTASSIGN = 277;
  int RSIGNEDSHIFTASSIGN = 278;
  int RUNSIGNEDSHIFTASSIGN = 279;
  int ELLIPSIS = 280;
  int LARROW = 281;
  int BSLASH = 282;
  int RARROW = 283;
  int RLONGARROW = 284;
  int LLONGARROW = 285;
  int JMLEQUAL = 286;
  int JMLNOTEQUAL = 287;
  int LTCOLON = 288;
  int RUNSIGNEDSHIFT = 289;
  int RSIGNEDSHIFT = 290;
  int GT = 291;
  int INF_DESC_START = 292;
  int INF_DESC_END = 293;

  int DEFAULT = 0;
  int IN_JML_SINGLE_LINE = 1;
  int IN_JML_MULTI_LINE = 2;
  int IN_SINGLE_LINE_COMMENT = 3;
  int IN_FORMAL_COMMENT = 4;
  int IN_MULTI_LINE_COMMENT = 5;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//@\"",
    "\"/*@\"",
    "\"@*/\"",
    "\"*/\"",
    "<JML_AT>",
    "<SINGLE_LINE_COMMENT>",
    "\"//\"",
    "<token of kind 13>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 17>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"\\\\original_spec\"",
    "\"\\\\original_case\"",
    "\"\\\\original_clause\"",
    "\"\\\\original\"",
    "\"hence_by\"",
    "\"hence_by_redundantly\"",
    "\"model\"",
    "\"spec_protected\"",
    "\"ghost\"",
    "\"pure\"",
    "\"instance\"",
    "\"helper\"",
    "\"uninitialized\"",
    "\"\\\\java_math\"",
    "\"spec_java_math\"",
    "\"spec_safe_math\"",
    "\"code_java_math\"",
    "\"code_safe_math\"",
    "\"also\"",
    "\"spec_public\"",
    "\"spec_bigint_math\"",
    "\"code_bigint_math\"",
    "\"non_null\"",
    "\"nullable\"",
    "\"nullable_by_default\"",
    "\"extract\"",
    "\"method\"",
    "\"constructor\"",
    "\"\\\\TYPE\"",
    "\"in\"",
    "\"in_redundantly\"",
    "\"\\\\into\"",
    "\"maps\"",
    "\"maps_redundantly\"",
    "\"static_initializer\"",
    "\"maintaining\"",
    "\"maintaining_redundantly\"",
    "\"loop_invariant\"",
    "\"loop_invariant_redundantly\"",
    "\"decreasing\"",
    "\"decreasing_redundantly\"",
    "\"decreases\"",
    "\"decreases_redundantly\"",
    "\"assume\"",
    "\"assume_redundantly\"",
    "\"set\"",
    "\"refining\"",
    "\"unreachable\"",
    "\"debug\"",
    "\"henceby\"",
    "\"henceby_redundantly\"",
    "\"invariant\"",
    "\"invariant_redundantly\"",
    "\"constraint\"",
    "\"constraint_redundantly\"",
    "\"\\\\everything\"",
    "\"\\\\such_that\"",
    "\"represents\"",
    "\"represents_redundantly\"",
    "\"initially\"",
    "\"readable\"",
    "\"writable\"",
    "\"monitors_for\"",
    "\"choose\"",
    "\"or\"",
    "\"choose_if\"",
    "\"abrupt_behavior\"",
    "\"abrupt_behaviour\"",
    "\"continues\"",
    "\"continues_redundantly\"",
    "\"breaks\"",
    "\"breaks_redundantly\"",
    "\"returns\"",
    "\"returns_redundantly\"",
    "\"\\\\result\"",
    "\"\\\\old\"",
    "\"\\\\pre\"",
    "\"\\\\not_assigned\"",
    "\"\\\\not_modified\"",
    "\"\\\\only_accessed\"",
    "\"\\\\only_captured\"",
    "\"\\\\only_called\"",
    "\"\\\\fresh\"",
    "\"\\\\reach\"",
    "\"\\\\duration\"",
    "\"space\"",
    "\"\\\\working_space\"",
    "\"\\\\nonnullelements\"",
    "\"\\\\typeof\"",
    "\"\\\\elemtype\"",
    "\"lockset\"",
    "\"\\\\max\"",
    "\"\\\\is_initialized\"",
    "\"\\\\invariant_for\"",
    "\"\\\\lblneg\"",
    "\"\\\\forall\"",
    "\"\\\\exists\"",
    "\"\\\\min\"",
    "\"\\\\num_of\"",
    "\"\\\\product\"",
    "\"\\\\sum\"",
    "\"\\\\nothing\"",
    "\"\\\\not_specified\"",
    "\"\\\\lblpos\"",
    "\"\\\\only_assigned\"",
    "\"behavior\"",
    "\"behaviour\"",
    "\"normal_behavior\"",
    "\"normal_behaviour\"",
    "\"exceptional_behavior\"",
    "\"exceptional_behaviour\"",
    "\"same\"",
    "\"requires\"",
    "\"requires_redundantly\"",
    "\"pre_redundantly\"",
    "\"ensures\"",
    "\"post\"",
    "\"ensures_redundantly\"",
    "\"post_redundantly\"",
    "\"signals\"",
    "\"signals_redundantly\"",
    "\"exsures\"",
    "\"exsures_redundantly\"",
    "\"signals_only\"",
    "\"signals_only_redundantly\"",
    "\"diverges\"",
    "\"diverges_redundantly\"",
    "\"when\"",
    "\"when_redundantly\"",
    "\"assignable\"",
    "\"assignable_redundantly\"",
    "\"modifiable\"",
    "\"modifiable_redundantly\"",
    "\"callable\"",
    "\"callable_redundantly\"",
    "\"measured_by\"",
    "\"measured_by_redundantly\"",
    "\"captures\"",
    "\"captures_redundantly\"",
    "\"working_space_redundantly\"",
    "\"duration_redundantly\"",
    "\"modifies\"",
    "\"modifies_redundantly\"",
    "\"code\"",
    "\"assert_redundantly\"",
    "\"axiom\"",
    "\"accessible\"",
    "\"accessible_redundantly\"",
    "\"implies_that\"",
    "\"for_example\"",
    "\"exceptional_example\"",
    "\"normal_example\"",
    "\"model_program\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"<-\"",
    "\"\\\\\"",
    "\"->\"",
    "\"==>\"",
    "\"<==\"",
    "\"<==>\"",
    "\"<=!=>\"",
    "\"<:\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"(*\"",
    "\"*)\"",
  };

}
