// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.



public class GPattern extends Pat {

    final public static int ARG_LENGTH = 1 ;
    final public static int TOK_LENGTH = 2 ;

    public AstToken getIDENTIFIER () {
        
        return (AstToken) tok [1] ;
    }

    public TermList getTermList () {
        
        return (TermList) arg [0] ;
    }

    public boolean[] printorder () {
        
        return new boolean[] {false, true, true} ;
    }

    public GPattern setParms (TermList arg0, AstToken tok0, AstToken tok1) {
        
        arg = new AstNode [ARG_LENGTH] ;
        tok = new AstTokenInterface [TOK_LENGTH] ;
        
        arg [0] = arg0 ;            /* TermList */
        tok [0] = tok0 ;            /* "::" */
        tok [1] = tok1 ;            /* IDENTIFIER */
        
        InitChildren () ;
        return (GPattern) this ;
    }

}
