// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.



public class ExprListElem extends AstListNode {

    public EExpr getEExpr () {
        
        return (EExpr) arg [0] ;
    }

    public ExprListElem setParms (AstToken tok0, EExpr arg0) {
        
        tok = new AstToken [1] ;
        tok [0] = tok0 ;            /* "," */
        return setParms (arg0) ;    /* EExpr */
    }

    public ExprListElem setParms (EExpr arg0) {
        
        original(arg0) ;     /* EExpr */
        return (ExprListElem) this ;
    }

}
