// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.



public class OptsElem extends AstListNode {

    public Opt getOpt () {
        
        return (Opt) arg [0] ;
    }

    public OptsElem setParms (Opt arg0) {
        
        original(arg0) ;     /* Opt */
        return (OptsElem) this ;
    }

}
