options {
  STATIC = false;
}

PARSER_BEGIN(CApproxParser)

package tmp.generated_capprox;

import java.io.*;
import java.util.*;
import cide.gast.*;
import cide.gparser.*;
import de.ovgu.cide.fstgen.ast.*;

public class CApproxParser extends AbstractFSTParser {

	public CApproxParser() {}

    // Run the parser
    public static void main ( String args [ ] ) {
      CApproxParser parser ;

  	
      if(args.length == 0){
        System.out.println("C (approx) Parser Version 0.1Alpha:  Reading from standard input . . .");
        parser = new CApproxParser(new OffsetCharStream(System.in));
      }
      else if(args.length == 1){
        System.out.println("C (approx) Parser Version 0.1Alpha:  Reading from file " + args[0] + " . . ." );
      try {
        parser = new CApproxParser(new OffsetCharStream(new java.io.FileInputStream(args[0])));
      }
      catch(java.io.FileNotFoundException e){
        System.out.println("C (approx) Parser Version 0.1:  File " + args[0] + " not found.");
        return ;
        }
      }
      else {
        System.out.println("C (approx) Parser Version 0.1Alpha:  Usage is one of:");
        System.out.println("         java CParser < inputfile");
        System.out.println("OR");
        System.out.println("         java CParser inputfile");
        return ;
      }
      try {
        parser.TranslationUnit(false);
        System.out.println("C (approx) Parser Version 0.1Alpha:  Java program parsed successfully.");
      }
      catch(ParseException e){
        System.out.println("C (approx) Parser Version 0.1Alpha:  Encountered errors during parse.");
        e.printStackTrace();
      }
    }

        
         /**
     * Append the given {@link Token} and any preceding special tokens to a
     * given {@link StringBuffer}.
     *
     * @param token the given JavaCC {@link Token} object
     * @param buffer the buffer to which to append <code>token</code>
     **/
    final private static void accumulate (Token token, StringBuffer buffer) {

	// Append preceding special tokens to <code>buffer</code>:
	//
	Token special = firstSpecial (token) ;
	if (special != token)
	    while (special != null) {
		buffer.append (special.toString ()) ;
		special = special.next ;
	    }

	// Finally, append the token itself:
	//
	buffer.append (token.toString ()) ;
    }
      
    /**
     * Accumulate {@list Token} objects from the token stream, respecting
     * nested code inside <code>open</code> and <code>close</code> pairs,
     * until an unmatched <code>close</code> is the next token in the stream.
     * This method assumes that an <code>open</code> token has just been read
     * from the stream so the initial nesting level is 1.  The method returns
     * when a matching <code>close</code> token is the next token in the token
     * stream.  <em>The <code>close</code> token is left in the stream!</em>
     *
     * @return the accumulated tokens as a {@link String}.
     *
     * @throws ParseException
     * if an end-of-file is found before an unmatched <code>close</code> token.
     **/
    final private Token accumulateNestedRegion (int open, int close)
    throws ParseException {

	StringBuffer buffer = new StringBuffer () ;

	// Initialize result with known information (starting position, etc.):
	//
	Token result = Token.newToken (OTHER) ;
	result.specialToken = null ;

	Token startToken = firstSpecial (getToken (1)) ;
	result.beginColumn = startToken.beginColumn ;
	result.beginLine = startToken.beginLine ;

	// Accumulate tokens until a <code>close</code> token is found:
	//
	for (int nesting = 1 ; nesting > 0 ; ) {

	    getNextToken () ;

	    // Update information in result:
	    //
	    result.endColumn = token.endColumn ;
	    result.endLine = token.endLine ;
	    result.next = token.next ;

	    if (token.kind == EOF)
		throw new ParseException (
		    "accumulating from line "
		    + result.beginLine
		    + " at column "
		    + result.beginColumn
		    + ": EOF reached before ending "
		    + tokenImage [close]
		    + " found"
		) ;

		accumulate (token, buffer) ;
	    if (token.kind == open)
			++ nesting ;
	    else if (token.kind == close) {
			if (nesting == 1)
		    	break ;
			-- nesting ;
	    }

	    
	    
	}

	result.image = buffer.toString () ;
	return result ;
    }

    /**
     * Accumulate {@link Token} objects from the token stream until a token
     * matching <code>tokenKind</code> is consumed from the stream.  The
     * tokens are accumulated in <code>buffer</code>, including the terminating
     * token.
     *
     * @return a {@link Token}
     * formed by concatenating all intervening tokens and special tokens.
     **/
    final private Token accumulateUntilToken (int tokenKind)
    throws ParseException {

	StringBuffer buffer = new StringBuffer () ;
	Token token = getNextToken () ;

	// Initialize result with known information (starting position, etc.):
	//
	Token result = Token.newToken (OTHER) ;
	result.specialToken = null ;

	Token startToken = firstSpecial (token) ;
	result.beginColumn = startToken.beginColumn ;
	result.beginLine = startToken.beginLine ;

	// Accumulate tokens until a <code>tokenKind</code> token is found:
	//
	while (token.kind != tokenKind) {

	    // Update information in result:
	    //
	    result.endColumn = token.endColumn ;
	    result.endLine = token.endLine ;
	    result.next = token.next ;

	    if (token.kind == EOF)
		throw new ParseException (
		    "from line "
		    + result.beginLine
		    + " at column "
		    + result.beginColumn
		    + ": EOF reached before "
		    + tokenImage [tokenKind]
		    + " found"
		) ;

	    accumulate (token, buffer) ;
	    token = getNextToken () ;
	}

	accumulate (token, buffer) ;

	result.image = buffer.toString () ;
	return result ;
    }
	/**
	 * finds the end of the current line for preprocessor instructions. handles
	 * also multiline makros ending with \
	 * 
	 * @return
	 * @throws ParseException
	 */
	final private Token accumulateUntilLineEnd() throws ParseException {
		StringBuffer buffer = new StringBuffer();
		Token nextToken = peekNext();

		// Initialize result with known information (starting position, etc.):
		//
		Token result = Token.newToken(OTHER);
		result.specialToken = null;

		Token startToken = firstSpecial(nextToken);
		result.beginColumn = startToken.beginColumn;
		result.beginLine = startToken.beginLine;

		// Accumulate tokens until a <code>tokenKind</code> token is found:
		//
		while (!preceededByLinebreak(nextToken) || token.image.equals("\\")) {
			getNextToken();

			// Update information in result:
			//
			result.endColumn = token.endColumn;
			result.endLine = token.endLine;
			result.next = token.next;

			if (token.kind == EOF)
				throw new ParseException("from line " + result.beginLine
						+ " at column " + result.beginColumn
						+ ": EOF reached before special token" + " found");

			accumulate(token, buffer);
			nextToken = peekNext();
		}

		result.image = buffer.toString();
		return result;
	}

	private boolean preceededByLinebreak(Token t) {
		assert t != null;
		Token specialToken = t.specialToken;
		while (specialToken != null) {
			if (specialToken.image.indexOf('\n')>=0)
				return true;
			specialToken = specialToken.specialToken;
		}
		return false;
	}
	private Token peekNext() {
		if (token.next == null)
			token.next = token_source.getNextToken();
		return token.next;
	}	
    /**
     * Finds the first token, special or otherwise, in the list of special
     * tokens preceding this {@link Token}.  If this list is non-empty, the
     * result will be a special token.  Otherwise, it will be the starting
     * token.
     *
     * @param token the given {@link Token}.
     * @return the first special token preceding <code>token</code>.
     **/
    final private static Token firstSpecial (Token token) {

	while (token.specialToken != null)
	    token = token.specialToken ;

	return token ;
    }
  }

PARSER_END(CApproxParser)

SPECIAL_TOKEN : {
 " "
|  "\t"
|  "\r"
|  "\n"
|  <"//" (~["\n","\r"])* ("\n" | "\r" | "\r\n")>
|  <"/*" (~["*"])* "*" ("*" | ~["*","/"] (~["*"])* "*")* "/">
| <"__attribute__((" (~[")"])* "))">
| <"__attribute__((format(" (~[")"])* ")))">
}


TOKEN : {
	<LITERAL: <INTEGER_LITERAL> | <FLOATING_POINT_LITERAL> | <STRING_LITERAL>|<CHARACTER_LITERAL>>
|  <#INTEGER_LITERAL: <DECIMAL_LITERAL> (["l","L"])? | <HEX_LITERAL> (["l","L"])? | <OCTAL_LITERAL> (["l","L"])?>
|  <#DECIMAL_LITERAL: ["1"-"9"] (["0"-"9"])*>
|  <#HEX_LITERAL: "0" ["x","X"] (["0"-"9","a"-"f","A"-"F"])+>
|  <#OCTAL_LITERAL: "0" (["0"-"7"])*>
|  <#FLOATING_POINT_LITERAL: (["0"-"9"])+ "." (["0"-"9"])* (<EXPONENT>)? (["f","F","d","D"])? | "." (["0"-"9"])+ (<EXPONENT>)? (["f","F","d","D"])? | (["0"-"9"])+ <EXPONENT> (["f","F","d","D"])? | (["0"-"9"])+ (<EXPONENT>)? ["f","F","d","D"]>
|  <#EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+>
|  <#CHARACTER_LITERAL: "\'" (~["\'","\\","\n","\r"] | "\\" (["n","t","b","r","f","\\","\'","\""] | ["0"-"7"] (["0"-"7"])? | ["0"-"3"] ["0"-"7"] ["0"-"7"])) "\'">
|  <#STRING_LITERAL: "\"" ( ~["\"","\\","\n","\r"] | "\\" ( ["n","t","b","r","f","\\","\'","\""] | ["0"-"7"] (["0"-"7"])?  | ["0"-"3"] ["0"-"7"] ["0"-"7"] | ( ["\n","\r"] | "\r\n")))* "\"">
}

TOKEN : {
	<INCLUDE: "include"> 
|	<DEFINE: "define"> 
|	<IFDEF: "ifdef"> 
|	<IFNDEF: "ifndef"> 
|	<ENDIF: "endif"> 
|	<ELIF: "elif"> 
|	<ELSIF: "elsif"> 
|	<PPLINE: "line"> 
|	<PPUNDEF: "undef"> 
|	<PPPRAGMA: "pragma"> 
|	<PPERROR: "error"> 
|	<TYPEDEF: "typedef"> 
//|	<LONG: "long"> 
//|	<STRUCT: "struct"> 
|	<ENUM: "enum"> 
|	<EXTERN: "extern"> 
|	<UNSIGNED: "unsigned"> 
|	<CONST: "const"> 
|	<STATIC: "static"> 
|	<STRUCT: "struct"> 
|	<INLINE: "inline"> 
|	<INLINE2: "__inline__">
|	<INLINE3: "__inline">
|	<WEIREDSTUFF1: "__regbank">
|	<WEIREDSTUFF2: "__TIPOFUNC__">
|	<IF: "if"> 
|	<ELSE: "else"> 
|	<FOR: "for"> 
|	<WHILE: "while"> 
|	<DO: "do"> 
|	<SWITCH: "switch"> 
|	<CASE: "case"> 
|	<SWDEFAULT: "default"> 
|	<SEMI: ";"> 
|	<COLON: ":"> 
|	<COMMA: ","> 
|	<LT: "<"> 
|	<GT: ">"> 
|	<OB: "("> 
|	<CB: ")"> 
|	<OCB: "{"> 
|	<CCB: "}"> 
|	<STAR: "*"> 
|	<EQ: "="> 
|	<HASH: "#"> 
| 	<PIPE: "|">
}

TOKEN : {
 <IDENTIFIER: <LETTER> (<LETTER> | <DIGIT>)* | "long long">
|  <#LETTER: ["$","A"-"Z","_","a"-"z"]>
|  <#DIGIT: ["0"-"9"]>
| <OTHER: ~[]>
}

JAVACODE
Token findEndGT () {
    return accumulateNestedRegion (LT, GT) ;
}
JAVACODE
Token findLineEnd () {
    return accumulateUntilLineEnd() ;
}
JAVACODE
Token findEndCB () {
    return accumulateNestedRegion(OB, CB) ;
}
JAVACODE
Token findEndCCB () {
    return accumulateNestedRegion(OCB, CCB) ;
}
FSTInfo TranslationUnit(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	Sequence_CodeUnit_TopLevel(inTerminal) <EOF> {return productionEndNonTerminal("TranslationUnit","-","-");}

 )  }

FSTInfo Sequence_CodeUnit_TopLevel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(LOOKAHEAD(2) CodeUnit_TopLevel(inTerminal))* {return productionEndNonTerminal("Sequence_CodeUnit_TopLevel","-","-");}

 )  }

FSTInfo CodeUnit_TopLevel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) n=PPIncludeStatement(true){ replaceName("PPIncludeStatement",n);} {return productionEndTerminal("Include","{PPIncludeStatement}","{PPIncludeStatement}","Replacement",first,token);}
 |
	LOOKAHEAD(2) n=PPDefineStatement(true){ replaceName("PPDefineStatement",n);} {return productionEndTerminal("Define","{PPDefineStatement}","{PPDefineStatement}","Replacement",first,token);}
 |
	LOOKAHEAD(2) n=PPIfDef_TopLevel(true){ replaceName("PPIfDef_TopLevel",n);} {return productionEndTerminal("IfDefTL","{PPIfDef_TopLevel}","{PPIfDef_TopLevel}","Replacement",first,token);}
 |
	LOOKAHEAD(2) "#" n=PPOtherIgnore(true){ replaceName("PPOtherIgnore",n);} findLineEnd() {return productionEndTerminal("Preprocessor","{PPOtherIgnore}","{PPOtherIgnore}","Replacement",first,token);}
 |
	LOOKAHEAD(FunctionHeader()) n=Function(true){ replaceName("Function",n);} {return productionEndTerminal("Func","{Function}","{Function}","JavaMethodOverriding",first,token);}
 |
	n=TypeDef(true){ replaceName("TypeDef",n);} {return productionEndTerminal("TypeDef_","{TypeDef}","{TypeDef}","Replacement",first,token);}
 |
	LOOKAHEAD(3) n=ExternDecl(true){ replaceName("ExternDecl",n);} {return productionEndTerminal("ExternDec","{ExternDecl}","{ExternDecl}","Replacement",first,token);}
 |
	n=Statement(true){ replaceName("Statement",n);} {return productionEndTerminal("StmtTL","{Statement}","{Statement}","Replacement",first,token);}

 )  }

FSTInfo CodeUnit_InBlock(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) PPIfDef_BlockLevel(true) {return productionEndTerminal("IfDefBL","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(2) PPIncludeStatement(true) {return productionEndTerminal("IncludeBL","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(2) PPDefineStatement(true) {return productionEndTerminal("DefineBL","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(2) "#" PPOtherIgnore(true) findLineEnd() {return productionEndTerminal("PreprocessorBL","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(1) IfStatement(true) {return productionEndTerminal("If","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(1) ForStatement(true) {return productionEndTerminal("For","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(1) WhileStatement(true) {return productionEndTerminal("While","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(1) DoStatement(true) {return productionEndTerminal("Do","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(1) SwitchStatement(true) {return productionEndTerminal("Switch","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(2) GotoLabel(true) {return productionEndTerminal("CodeUnit_InBlock10","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(1) Block(true) {return productionEndTerminal("Blck","-","-","Replacement",first,token);}
 |
	Statement(true) {return productionEndTerminal("Stmt","-","-","Replacement",first,token);}

 )  }

FSTInfo Statement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(AnyStmtToken(true))* ";" {return productionEndTerminal("Statement","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo IfStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"if" "(" findEndCB() BlockOrSingleStatement(true) [LOOKAHEAD(1) ElseBlock(true)] {return productionEndTerminal("IfStatement","-","-","Replacement",first,token);}

 )  }

FSTInfo ElseBlock(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"else"  {return productionEndTerminal("ElseBlock","-","-","Replacement",first,token);}

 )  }

FSTInfo ForStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"for" "(" findEndCB() BlockOrSingleStatement(true) {return productionEndTerminal("ForStatement","-","-","Replacement",first,token);}

 )  }

FSTInfo WhileStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"while" "(" findEndCB() BlockOrSingleStatement(true) {return productionEndTerminal("WhileStatement","-","-","Replacement",first,token);}

 )  }

FSTInfo DoStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"do" BlockOrSingleStatement(true) "while" "(" findEndCB() ";" {return productionEndTerminal("DoStatement","-","-","Replacement",first,token);}

 )  }

FSTInfo SwitchStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"switch" "(" findEndCB() "{" (SwCase(true))* "}" {return productionEndTerminal("SwitchStatement","-","-","Replacement",first,token);}

 )  }

FSTInfo SwCase(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"default" ":" Sequence_CodeUnit_InBlock(true) {return productionEndTerminal("SwCase1","-","-","Replacement",first,token);}
 |
	"case" [LOOKAHEAD(1) "(" <IDENTIFIER> ")"] SwCaseLabel(true) (MoreSwCaseLabel(true))* ":" Sequence_CodeUnit_InBlock(true) {return productionEndTerminal("SwCase2","-","-","Replacement",first,token);}

 )  }

FSTInfo SwCaseLabel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("SwCaseLabel1","-","-","Replacement",first,token);}
 |
	[<OTHER>] <LITERAL> {return productionEndTerminal("SwCaseLabel2","-","-","Replacement",first,token);}

 )  }

FSTInfo MoreSwCaseLabel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"|" SwCaseLabel(true) {return productionEndTerminal("MoreSwCaseLabel","-","-","Replacement",first,token);}

 )  }

FSTInfo ExternDecl(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"extern" <LITERAL> Block(true) {return productionEndTerminal("ExternDecl","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo PPIncludeStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"#" "include" findLineEnd() {return productionEndTerminal("PPIncludeStatement","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo PPDefineStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "#" "define" findLineEnd() {return productionEndTerminal("PPDefineStatement1","-","{TOSTRING}","Replacement",first,token);}
 |
	LOOKAHEAD(2) "#" "undef" findLineEnd() {return productionEndTerminal("PPDefineStatement2","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo PPIfDef_TopLevel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	IfDefLine(true) Sequence_CodeUnit_TopLevel(true) (LOOKAHEAD(2) IfElseIf_TopLevel(true))* [LOOKAHEAD(2) "#" "else" Sequence_CodeUnit_TopLevel(true)] "#" "endif" {return productionEndTerminal("PPIfDef_TopLevel","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo PPIfDef_BlockLevel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	IfDefLine(true) Sequence_CodeUnit_InBlock(true) (LOOKAHEAD(2) IfElseIf_BlockLevel(true))* [LOOKAHEAD(2) "#" "else" Sequence_CodeUnit_InBlock(true)] "#" "endif" {return productionEndTerminal("PPIfDef_BlockLevel","-","-","Replacement",first,token);}

 )  }

FSTInfo PPOtherIgnore(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"line"  {return productionEndTerminal("PPOtherIgnore1","-","{TOSTRING}","Replacement",first,token);}
 |
	"pragma"  {return productionEndTerminal("PPOtherIgnore2","-","{TOSTRING}","Replacement",first,token);}
 |
	"error"  {return productionEndTerminal("PPOtherIgnore3","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo IfDefLine(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "#" "ifdef" <IDENTIFIER> {return productionEndTerminal("IfDefLine1","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(2) "#" "ifndef" <IDENTIFIER> {return productionEndTerminal("IfDefLine2","-","-","Replacement",first,token);}
 |
	"#" "if" findLineEnd() {return productionEndTerminal("IfDefLine3","-","-","Replacement",first,token);}

 )  }

FSTInfo IfElseIf(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "#" "elif"  {return productionEndTerminal("IfElseIf1","-","-","Replacement",first,token);}
 |
	"#" "elsif"  {return productionEndTerminal("IfElseIf2","-","-","Replacement",first,token);}

 )  }

FSTInfo IfElseIf_BlockLevel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	IfElseIf(true) findLineEnd() Sequence_CodeUnit_InBlock(true) {return productionEndTerminal("IfElseIf_BlockLevel","-","-","Replacement",first,token);}

 )  }

FSTInfo IfElseIf_TopLevel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	IfElseIf(true) findLineEnd() Sequence_CodeUnit_TopLevel(true) {return productionEndTerminal("IfElseIf_TopLevel","-","-","Replacement",first,token);}

 )  }

FSTInfo Function(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	n=FunctionHeader(true){ replaceName("FunctionHeader",n);} [n=FunctionParameterList(true){ replaceName("FunctionParameterList",n);}] ")" BlockOrSemi(true) {return productionEndTerminal("Function","-","{FunctionHeader}({FunctionParameterList})","Replacement",first,token);}

 )  }

FSTInfo FunctionHeader(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(Modifier(true))* FunctionReturnType(true) ["*" ] [LOOKAHEAD(1) FunctionExoticStuff(true)] t=<IDENTIFIER>{ replaceName("<IDENTIFIER>",new FSTInfo(t.toString()));} "(" {return productionEndTerminal("FunctionHeader","-","{<IDENTIFIER>}","Replacement",first,token);}

 )  }

FSTInfo FunctionReturnType(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	["const" ] ["struct" ] ["unsigned" ] <IDENTIFIER> {return productionEndTerminal("FunctionReturnType","-","-","Replacement",first,token);}

 )  }

FSTInfo Modifier(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"static"  {return productionEndTerminal("Modifier1","-","-","Replacement",first,token);}
 |
	"inline"  {return productionEndTerminal("Modifier2","-","-","Replacement",first,token);}
 |
	"__inline__"  {return productionEndTerminal("Modifier3","-","-","Replacement",first,token);}
 |
	"__inline"  {return productionEndTerminal("Modifier4","-","-","Replacement",first,token);}
 |
	"extern"  {return productionEndTerminal("Modifier5","-","-","Replacement",first,token);}
 |
	"__TIPOFUNC__"  {return productionEndTerminal("Modifier6","-","-","Replacement",first,token);}

 )  }

FSTInfo FunctionExoticStuff(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"__regbank" "(" <LITERAL> ")" {return productionEndTerminal("FunctionExoticStuff","-","-","Replacement",first,token);}

 )  }

FSTInfo FunctionParameterList(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	FunctionParameter(true) ("," FunctionParameter(true))* {return productionEndTerminal("FunctionParameterList","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo FunctionParameter(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(VarDeclToken(true))+ {return productionEndTerminal("FunctionParameter","-","-","Replacement",first,token);}

 )  }

FSTInfo Block(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"{" Sequence_CodeUnit_InBlock(true) "}" {return productionEndTerminal("Block","-","-","Replacement",first,token);}

 )  }

FSTInfo GotoLabel(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> ":" {return productionEndTerminal("GotoLabel","-","-","Replacement",first,token);}

 )  }

FSTInfo Sequence_CodeUnit_InBlock(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(LOOKAHEAD(2) CodeUnit_InBlock(true))* {return productionEndTerminal("Sequence_CodeUnit_InBlock","-","-","Replacement",first,token);}

 )  }

FSTInfo BlockOrSemi(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(1) ";"  {return productionEndTerminal("BlockOrSemi1","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(1) Block(true) {return productionEndTerminal("BlockOrSemi2","-","-","Replacement",first,token);}
 |
	(VarDecl(true))+ Block(true) {return productionEndTerminal("BlockOrSemi3","-","-","Replacement",first,token);}

 )  }

FSTInfo BlockOrSingleStatement(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(1) Block(true) {return productionEndTerminal("BlockOrSingleStatement1","-","-","Replacement",first,token);}
 |
	CodeUnit_InBlock(true) {return productionEndTerminal("BlockOrSingleStatement2","-","-","Replacement",first,token);}

 )  }

FSTInfo TypeDef(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(2) "typedef" "enum" (AnyTypeDefToken(true))* ";" {return productionEndTerminal("TypeDef1","-","{TOSTRING}","Replacement",first,token);}
 |
	"typedef" (AnyStmtToken(true))* ";" {return productionEndTerminal("TypeDef2","-","{TOSTRING}","Replacement",first,token);}

 )  }

FSTInfo BlockAssignment(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"=" [Cast(true)] "{" findEndCCB() {return productionEndTerminal("BlockAssignment","-","-","Replacement",first,token);}

 )  }

FSTInfo EnumBlock(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"enum" [<IDENTIFIER>] "{" findEndCCB() {return productionEndTerminal("EnumBlock","-","-","Replacement",first,token);}

 )  }

FSTInfo Cast(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	"(" FunctionReturnType(true) ")" {return productionEndTerminal("Cast","-","-","Replacement",first,token);}

 )  }

FSTInfo AnyTypeDefToken(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	LOOKAHEAD(1) "{"  {return productionEndTerminal("AnyTypeDefToken1","-","-","Replacement",first,token);}
 |
	"}"  {return productionEndTerminal("AnyTypeDefToken2","-","-","Replacement",first,token);}
 |
	AnyStmtToken(true) {return productionEndTerminal("AnyTypeDefToken3","-","-","Replacement",first,token);}

 )  }

FSTInfo AnyStmtToken(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("AnyStmtToken1","-","-","Replacement",first,token);}
 |
	<LITERAL> {return productionEndTerminal("AnyStmtToken2","-","-","Replacement",first,token);}
 |
	<OTHER> {return productionEndTerminal("AnyStmtToken3","-","-","Replacement",first,token);}
 |
	","  {return productionEndTerminal("AnyStmtToken4","-","-","Replacement",first,token);}
 |
	"|"  {return productionEndTerminal("AnyStmtToken5","-","-","Replacement",first,token);}
 |
	"<"  {return productionEndTerminal("AnyStmtToken6","-","-","Replacement",first,token);}
 |
	">"  {return productionEndTerminal("AnyStmtToken7","-","-","Replacement",first,token);}
 |
	"("  {return productionEndTerminal("AnyStmtToken8","-","-","Replacement",first,token);}
 |
	")"  {return productionEndTerminal("AnyStmtToken9","-","-","Replacement",first,token);}
 |
	Block(true) {return productionEndTerminal("AnyStmtToken10","-","-","Replacement",first,token);}
 |
	"if"  {return productionEndTerminal("AnyStmtToken11","-","-","Replacement",first,token);}
 |
	"else"  {return productionEndTerminal("AnyStmtToken12","-","-","Replacement",first,token);}
 |
	"for"  {return productionEndTerminal("AnyStmtToken13","-","-","Replacement",first,token);}
 |
	"while"  {return productionEndTerminal("AnyStmtToken14","-","-","Replacement",first,token);}
 |
	LOOKAHEAD(3) EnumBlock(true) {return productionEndTerminal("AnyStmtToken15","-","-","Replacement",first,token);}
 |
	"enum"  {return productionEndTerminal("AnyStmtToken16","-","-","Replacement",first,token);}
 |
	"*"  {return productionEndTerminal("AnyStmtToken17","-","-","Replacement",first,token);}
 |
	LOOKAHEAD("=" [Cast()]"{") BlockAssignment(true) {return productionEndTerminal("AnyStmtToken18","-","-","Replacement",first,token);}
 |
	"="  {return productionEndTerminal("AnyStmtToken19","-","-","Replacement",first,token);}
 |
	":"  {return productionEndTerminal("AnyStmtToken20","-","-","Replacement",first,token);}
 |
	Modifier(true) {return productionEndTerminal("AnyStmtToken21","-","-","Replacement",first,token);}
 |
	"ifdef"  {return productionEndTerminal("AnyStmtToken22","-","-","Replacement",first,token);}
 |
	"ifndef"  {return productionEndTerminal("AnyStmtToken23","-","-","Replacement",first,token);}
 |
	"define"  {return productionEndTerminal("AnyStmtToken24","-","-","Replacement",first,token);}
 |
	"include"  {return productionEndTerminal("AnyStmtToken25","-","-","Replacement",first,token);}
 |
	"elif"  {return productionEndTerminal("AnyStmtToken26","-","-","Replacement",first,token);}
 |
	"elsif"  {return productionEndTerminal("AnyStmtToken27","-","-","Replacement",first,token);}
 |
	PPOtherIgnore(true) {return productionEndTerminal("AnyStmtToken28","-","-","Replacement",first,token);}
 |
	"const"  {return productionEndTerminal("AnyStmtToken29","-","-","Replacement",first,token);}
 |
	"struct"  {return productionEndTerminal("AnyStmtToken30","-","-","Replacement",first,token);}
 |
	"unsigned"  {return productionEndTerminal("AnyStmtToken31","-","-","Replacement",first,token);}

 )  }

FSTInfo VarDecl(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	(VarDeclTokenOrComma(true))* ";" {return productionEndTerminal("VarDecl","-","-","Replacement",first,token);}

 )  }

FSTInfo VarDeclTokenOrComma(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	VarDeclToken(true) {return productionEndTerminal("VarDeclTokenOrComma1","-","-","Replacement",first,token);}
 |
	","  {return productionEndTerminal("VarDeclTokenOrComma2","-","-","Replacement",first,token);}

 )  }

FSTInfo VarDeclToken(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<IDENTIFIER> {return productionEndTerminal("VarDeclToken1","-","-","Replacement",first,token);}
 |
	<LITERAL> {return productionEndTerminal("VarDeclToken2","-","-","Replacement",first,token);}
 |
	"*"  {return productionEndTerminal("VarDeclToken3","-","-","Replacement",first,token);}
 |
	<OTHER> {return productionEndTerminal("VarDeclToken4","-","-","Replacement",first,token);}
 |
	"|"  {return productionEndTerminal("VarDeclToken5","-","-","Replacement",first,token);}
 |
	"const"  {return productionEndTerminal("VarDeclToken6","-","-","Replacement",first,token);}
 |
	"struct"  {return productionEndTerminal("VarDeclToken7","-","-","Replacement",first,token);}
 |
	"unsigned"  {return productionEndTerminal("VarDeclToken8","-","-","Replacement",first,token);}
 |
	"enum"  {return productionEndTerminal("VarDeclToken9","-","-","Replacement",first,token);}
 |
	PPOtherIgnore(true) {return productionEndTerminal("VarDeclToken10","-","-","Replacement",first,token);}
 |
	Modifier(true) {return productionEndTerminal("VarDeclToken11","-","-","Replacement",first,token);}
 |
	"(" findEndCB() {return productionEndTerminal("VarDeclToken12","-","-","Replacement",first,token);}

 )  }

FSTInfo Literal(boolean inTerminal) : { Token first=null,t;FSTInfo n; 
} { {first=getToken(1); productionStart(inTerminal); } (
	<LITERAL> {return productionEndTerminal("Literal","-","-","Replacement",first,token);}

 )  }

